import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	overlay: {
		flex: 1,
		justifyContent: "flex-end",
	},
	backdrop: {
		...StyleSheet.absoluteFillObject,
	},
	backdropPressable: {
		flex: 1,
	},
	sheetDock: {
		paddingHorizontal: 12,
		paddingTop: 24,
	},
	sheet: {
		width: "100%",
		maxWidth: 430,
		alignSelf: "center",
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderBottomLeftRadius: 30,
		borderBottomRightRadius: 30,
		paddingHorizontal: 20,
		paddingTop: 12,
		paddingBottom: 18,
		overflow: "hidden",
		shadowColor: "#020617",
		shadowOpacity: 0.2,
		shadowRadius: 28,
		shadowOffset: { width: 0, height: 18 },
		elevation: 18,
	},
	sheetScroll: {
		flex: 1,
	},
	sheetScrollContent: {
		paddingBottom: 10,
	},
	sheetWash: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		height: 120,
	},
	handle: {
		width: 42,
		height: 5,
		borderRadius: 999,
		alignSelf: "center",
		marginBottom: 12,
	},
	headerRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 16,
	},
	progressWrap: {
		flex: 1,
		gap: 8,
	},
	progressLabel: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	progressDots: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	progressDot: {
		width: 8,
		height: 8,
		borderRadius: 4,
	},
	progressDotActive: {
		width: 22,
	},
	closeButton: {
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: "center",
		justifyContent: "center",
	},
	stepStage: {
		marginTop: 18,
	},
	stepIntro: {
		gap: 6,
	},
	eyebrow: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	title: {
		fontSize: 28,
		lineHeight: 32,
		fontWeight: "800",
		letterSpacing: -0.45,
	},
	body: {
		fontSize: 15,
		lineHeight: 21,
		fontWeight: "500",
		maxWidth: 320,
	},
	previewWrap: {
		marginTop: 20,
	},
	previewSurface: {
		borderRadius: 28,
		paddingHorizontal: 18,
		paddingVertical: 18,
		minHeight: 164,
		justifyContent: "center",
	},
	toolbarRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	toolbarGhost: {
		width: 42,
		height: 42,
		borderRadius: 21,
		backgroundColor: "rgba(148,163,184,0.14)",
	},
	toolbarTarget: {
		width: 72,
		height: 72,
		borderRadius: 24,
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#86100E",
		shadowOpacity: 0.16,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 8 },
		elevation: 6,
	},
	previewCaptionPill: {
		alignSelf: "center",
		marginTop: 18,
		paddingHorizontal: 12,
		paddingVertical: 7,
		borderRadius: 999,
	},
	previewCaptionText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
	},
	previewListSurface: {
		gap: 10,
	},
	listRow: {
		minHeight: 46,
		borderRadius: 18,
		paddingHorizontal: 14,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	listRowHighlight: {
		shadowColor: "#86100E",
		shadowOpacity: 0.12,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 6 },
		elevation: 4,
	},
	listRowText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
	},
	previewHomeSurface: {
		alignItems: "center",
	},
	homeGrid: {
		width: "100%",
		flexDirection: "row",
		alignItems: "flex-end",
		justifyContent: "center",
		gap: 16,
	},
	homeGhostTile: {
		width: 72,
		height: 92,
		borderRadius: 24,
		opacity: 0.6,
	},
	homeAppTile: {
		width: 102,
		height: 108,
		borderRadius: 28,
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		shadowColor: "#86100E",
		shadowOpacity: 0.14,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 8 },
		elevation: 7,
	},
	homeAppIcon: {
		width: 52,
		height: 52,
		borderRadius: 12,
	},
	homeAppLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "800",
		letterSpacing: -0.1,
	},
	accentPill: {
		marginTop: 16,
		alignSelf: "flex-start",
		paddingHorizontal: 12,
		paddingVertical: 9,
		borderRadius: 999,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	accentPillText: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	actionsRow: {
		marginTop: 22,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	secondaryButton: {
		flex: 1,
		minHeight: 48,
		borderRadius: 18,
		alignItems: "center",
		justifyContent: "center",
	},
	secondaryButtonText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	primaryButton: {
		flex: 1.28,
		minHeight: 48,
		borderRadius: 18,
		paddingHorizontal: 16,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
	},
	primaryButtonText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "800",
		color: "#FFFFFF",
	},
});

export default styles;
