import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

const styles = StyleSheet.create({
	bodyScrollContent: {
		paddingBottom: 6,
	},
	topRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		marginTop: 6,
		marginBottom: 20,
	},
	searchModeBody: {
		gap: 12,
	},
	searchPill: {
		flex: 1,
		flexShrink: 1,
		minWidth: 0,
		minHeight: 44,
		paddingHorizontal: 15,
		flexDirection: "row",
		alignItems: "center",
		gap: 9,
		borderRadius: 22,
		borderCurve: "continuous",
	},
	searchInputPill: {
		paddingVertical: 0,
		minWidth: 0,
	},
	searchInput: {
		flex: 1,
		minWidth: 0,
		paddingVertical: 0,
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "500",
	},
	searchText: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "500",
	},
	avatarPressable: {
		width: 44,
		height: 44,
	},
	avatarImageShell: {
		width: 42,
		height: 42,
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
	},
	pressedScale: {
		opacity: 0.82,
		transform: [{ scale: 0.98 }],
	},
	rowPressed: {
		opacity: 0.88,
		transform: [{ scale: 0.99 }],
	},
	sectionTriggerPressed: {
		opacity: 0.78,
	},
	sectionLabel: {
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "600",
	},
	intentSectionHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
		marginBottom: 16,
	},
	intentSectionHeaderBiased: {
		justifyContent: "flex-start",
		alignSelf: "flex-start",
	},
	intentSectionHeaderTrigger: {
		marginBottom: 16,
	},
	currentCard: {
		position: "relative",
		overflow: "hidden",
		paddingHorizontal: 14,
		paddingVertical: 14,
		marginBottom: 22,
		shadowColor: "#0F172A",
		shadowOpacity: 0.18,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 12 },
		elevation: 8,
		...squircle(26),
	},
	currentCardGradient: {
		...StyleSheet.absoluteFillObject,
		opacity: 0.95,
	},
	currentCardGlow: {
		position: "absolute",
		right: -36,
		top: -42,
		width: 112,
		height: 112,
		borderRadius: 999,
		opacity: 0.28,
	},
	currentCardContent: {
		position: "relative",
		flexDirection: "row",
		alignItems: "center",
		gap: 11,
		minHeight: 48,
	},
	currentCardMainAction: {
		flex: 1,
		minWidth: 0,
		flexDirection: "row",
		alignItems: "center",
		gap: 11,
		borderRadius: 18,
		borderCurve: "continuous",
	},
	currentCardAvatar: {
		width: 44,
		height: 44,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
	},
	currentCardCopy: {
		flex: 1,
		gap: 2,
		minWidth: 0,
	},
	currentCardMeta: {
		maxWidth: 104,
		minHeight: 28,
		paddingHorizontal: 9,
		paddingVertical: 6,
		borderRadius: 999,
		borderCurve: "continuous",
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
	},
	currentCardMetaText: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "700",
		textTransform: "uppercase",
	},
	currentCardAddress: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
	},
	currentCardBody: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "400",
	},
	orbRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		gap: 12,
		marginBottom: 18,
	},
	orbItem: {
		flex: 1,
		alignItems: "center",
		gap: 6,
	},
	orbCircle: {
		width: 50,
		height: 50,
		borderRadius: 25,
		alignItems: "center",
		justifyContent: "center",
	},
	orbLabelBelow: {
		fontSize: 12,
		fontWeight: "600",
	},
	listCard: {
		borderRadius: 22,
		borderCurve: "continuous",
		overflow: "hidden",
	},
	recentsSection: {
		marginTop: 4,
	},
	recentsHubBody: {
		gap: 12,
		paddingBottom: 8,
	},
	placesHubBody: {
		gap: 12,
		paddingBottom: 8,
	},
	placesHubSectionBlock: {
		gap: 6,
		marginTop: 4,
	},
	placesHubSectionHeading: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 4,
	},
	placesHubSectionIconOrb: {
		width: 20,
		height: 20,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
	},
	placesHubSectionLabel: {
		fontSize: 12,
		fontWeight: "600",
		letterSpacing: 0.1,
	},
	emptyGroup: {
		borderRadius: 22,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	recentsEmptyGroup: {
		marginTop: 4,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	emptyGroupCopy: {
		flex: 1,
		minWidth: 0,
	},
	emptyGroupTitle: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	emptyGroupBody: {
		marginTop: 2,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	listRow: {
		paddingVertical: 12,
		paddingHorizontal: 14,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	listRowTextWrap: {
		flex: 1,
		paddingRight: 10,
	},
	listRowTitle: {
		fontSize: 14,
		fontWeight: "600",
	},
	listRowSubtitle: {
		fontSize: 12,
		marginTop: 2,
	},
	rowDivider: {
		height: StyleSheet.hairlineWidth,
		marginLeft: 14,
	},
	manualIntroCard: {
		flexDirection: "row",
		alignItems: "center",
		borderRadius: 22,
		borderCurve: "continuous",
		paddingHorizontal: 12,
		paddingVertical: 11,
		gap: 10,
		marginBottom: 20,
	},
	manualFallbackCard: {
		marginTop: 0,
		marginBottom: 18,
	},
	manualIntroIcon: {
		width: 38,
		height: 38,
		borderRadius: 19,
		alignItems: "center",
		justifyContent: "center",
	},
	manualIntroCopy: {
		flex: 1,
		minWidth: 0,
	},
	manualTitle: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	manualBody: {
		fontSize: 12,
		lineHeight: 16,
	},
	manualAction: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
		flexShrink: 0,
	},
	manualActionLabel: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
	},
	manualStepBody: {
		gap: 12,
		paddingTop: 4,
		paddingBottom: 80,
	},
	manualProgressRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		marginBottom: 4,
	},
	manualProgressDot: {
		borderRadius: 999,
	},
	manualProgressDotActive: {
		width: 20,
		height: 5,
		borderRadius: 999,
	},
	manualProgressDotDone: {
		width: 5,
		height: 5,
	},
	manualProgressDotPending: {
		width: 5,
		height: 5,
	},
	manualStepQuestion: {
		fontSize: 20,
		lineHeight: 26,
		fontWeight: "700",
		letterSpacing: -0.3,
	},
	manualStepHelper: {
		marginTop: -6,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "400",
	},
	manualOptionalText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	manualErrorRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
	},
	manualErrorText: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "500",
		color: "#EF4444",
	},
	manualStepButtonLabel: {
		fontSize: 13,
		fontWeight: "600",
	},
	draftAddressPreview: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 7,
		paddingVertical: 9,
		paddingHorizontal: 12,
		borderRadius: 12,
		borderCurve: "continuous",
		marginBottom: 2,
	},
	draftAddressLine: {
		flex: 1,
		fontSize: 12,
		lineHeight: 17,
		fontWeight: "500",
		fontStyle: "italic",
	},
	confirmBackAction: {
		marginRight: "auto",
	},
	confirmUseAction: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
	},
	saveDecisionRow: {
		marginTop: 4,
		flexDirection: "row",
		gap: 8,
	},
	saveDecisionChip: {
		flex: 1,
		minHeight: 36,
		borderRadius: 12,
		borderCurve: "continuous",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 6,
		paddingHorizontal: 10,
	},
	saveDecisionText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
	},
	candidateDecisionStack: {
		gap: 12,
	},
	candidateActionGroup: {
		overflow: "hidden",
		borderRadius: 24,
		borderCurve: "continuous",
	},
	saveDetailsCard: {
		borderRadius: 24,
		borderCurve: "continuous",
		padding: 14,
		gap: 10,
	},
	saveDetailsHeader: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		marginBottom: 2,
	},
	saveDetailsCopy: {
		flex: 1,
		minWidth: 0,
	},
	saveDetailsPrimaryAction: {
		height: 46,
		borderRadius: 22,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
	},
	candidateActionRow: {
		minHeight: 54,
		paddingHorizontal: 14,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	disabledRow: {
		opacity: 0.58,
	},
	candidateActionIcon: {
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: "center",
		justifyContent: "center",
	},
	// PULLBACK NOTE: [LS-UI-5] Reduce font weight and increase size for CTA text
	// OLD: fontSize 14, fontWeight 700
	// NEW: fontSize 15, fontWeight 600 for better readability
	candidateActionText: {
		flex: 1,
		minWidth: 0,
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "600",
	},
	candidateActionDivider: {
		height: StyleSheet.hairlineWidth,
		marginLeft: 60,
	},
	// Manual step redesign styles
	manualCompletedRow: {
		minHeight: 44,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingHorizontal: 2,
		paddingVertical: 8,
	},
	manualCompletedIcon: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	manualCompletedLabel: {
		flex: 1,
		minWidth: 0,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "500",
	},
	manualCompletedValue: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
		flexShrink: 0,
	},
	manualDropSearch: {
		minHeight: 46,
		borderRadius: 14,
		borderCurve: "continuous",
		paddingHorizontal: 12,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	manualDropSearchInput: {
		flex: 1,
		minWidth: 0,
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "500",
	},
	manualDropList: {
		marginTop: 4,
		gap: 0,
	},
	manualDropItem: {
		minHeight: 48,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingHorizontal: 2,
		paddingVertical: 10,
	},
	manualDropItemLabel: {
		flex: 1,
		minWidth: 0,
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "600",
	},
	manualDropItemSub: {
		marginTop: 2,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	manualDropDivider: {
		height: StyleSheet.hairlineWidth,
		marginLeft: 40,
	},
	manualStickyFooter: {
		flexDirection: "row",
		gap: 8,
		paddingHorizontal: 14,
		paddingTop: 10,
		paddingBottom: 8,
	},
});


export default styles;
