// Service types for filtering and UI
export const SERVICE_TYPES = [
  {
    id: "premium",
    label: "Premium",
    description: "Fastest response, advanced life support, specialized team",
    icon: "shield-checkmark",
    priceRange: "$150-$250",
    features: ["ALS Ambulance", "Paramedic Team", "Cardiac Monitor", "Priority Dispatch"],
  },
  {
    id: "standard",
    label: "Standard",
    description: "Quick response, basic life support, quality care",
    icon: "medical",
    priceRange: "$70-$130",
    features: ["BLS Ambulance", "EMT Team", "First Aid", "Oxygen Support"],
  },
  {
    id: "critical",
    label: "Critical Care",
    description: "ICU-level transport with specialized equipment",
    icon: "pulse",
    priceRange: "$300-$500",
    features: ["Mobile ICU", "Ventilator", "Critical Care Nurse", "Physician On-Board"],
  },
];

// Available specialties for bed booking
export const SPECIALTIES = [
  "General Care",
  "Emergency",
  "Cardiology",
  "Neurology",
  "Oncology",
  "Pediatrics",
  "Orthopedics",
  "ICU",
  "Trauma",
  "Urgent Care",
  "Psychiatry",
  "Obstetrics",
  "Gynecology",
  "Pulmonology",
  "Gastroenterology",
  "Dermatology",
  "Ophthalmology",
  "ENT",
  "Urology",
  "Nephrology",
  "Rheumatology",
  "Endocrinology",
  "Infectious Disease",
  "Palliative Care",
  "Rehabilitation",
  "Sports Medicine",
  "Geriatrics",
  "Neonatology",
  "Burn Care",
  "Transplant",
];

// Emergency levels for filtering
export const EMERGENCY_LEVELS = [
  "Level 1 Trauma Center",
  "Level 2 Trauma Center",
  "Level 3 Trauma Center",
  "Level 1 Pediatric Trauma",
  "Comprehensive Stroke Center",
  "Level 1 Cardiac Center",
  "Verified Burn Center",
  "NCI-Designated Cancer Center",
  "Psychiatric Emergency",
  "Emergency Department",
  "Urgent Care Center",
  "Urgent Care",
  "Community Hospital",
  "General Hospital",
  "Specialty Center",
  "Outpatient Center",
  "Family Practice",
  "Surgical Center",
];

// Hospital features for filtering
export const HOSPITAL_FEATURES = [
  "24/7 Emergency",
  "Helicopter Landing",
  "ICU",
  "Surgery",
  "Pediatric Care",
  "Cardiac Care",
  "Stroke Center",
  "Trauma",
  "Burn Unit",
  "NICU",
  "PICU",
  "Transplant Unit",
  "Research Center",
  "Teaching Hospital",
  "Telehealth",
  "Walk-in Welcome",
  "Bilingual Staff",
  "Rehabilitation",
  "Physical Therapy",
  "MRI",
  "CT Scanner",
  "Lab Services",
  "Blood Bank",
  "Pharmacy",
];
