export const MAP_CONFIG = {
	DEFAULT_ZOOM: 15,
	HOSPITAL_ZOOM: 16,
	HOSPITAL_SELECT_ZOOM: 17,
	CITY_ZOOM: 12,
	DEFAULT_LATITUDE: 37.7749,
	DEFAULT_LONGITUDE: -122.4194,
	INITIAL_LATITUDE_DELTA: 0.05,
	INITIAL_LONGITUDE_DELTA: 0.05,
	ANIMATION_DURATION: 500,
	ROUTE_ANIMATION_DURATION: 3000,
	ZOOM_PADDING: 100,
};

export const MARKER_CONFIG = {
	HOSPITAL_SIZE: 40,
	USER_SIZE: 50,
	AMBULANCE_SIZE: 45,
	CLUSTER_SIZE: 45,
	CLUSTER_ANIMATION_DURATION: 300,
};

export const ROUTE_CONFIG = {
	POLYLINE_WIDTH: 4,
	POLYLINE_COLOR: "#3B82F6",
	SELECTED_POLYLINE_COLOR: "#1E40AF",
	ROUTE_FETCH_TIMEOUT: 10000,
	FALLBACK_ROUTE_API: "OSRM",
	PRIMARY_ROUTE_API: "GOOGLE",
};

export const AMBULANCE_CONFIG = {
	ANIMATION_INTERVAL: 100,
	UPDATE_FREQUENCY_MS: 1000,
	PATH_SEGMENT_DURATION_MS: 30000,
	MAX_SPEED_MPS: 30,
};

export const LOCATION_CONFIG = {
	ACCURACY: 6,
	MAX_AGE: 5000,
	TIMEOUT: 10000,
	DISTANCE_INTERVAL: 10,
};

export const MAP_PADDING = {
	INITIAL: { top: 50, right: 0, bottom: 50, left: 0 },
	WITH_SHEET: { top: 50, right: 0, bottom: 150, left: 0 },
	EXPANDED_SHEET: { top: 50, right: 0, bottom: 400, left: 0 },
};
