import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export const styles = StyleSheet.create({
	scrollContent: {
		paddingTop: 0,
		paddingHorizontal: 14,
		paddingBottom: 32,
		gap: 16,
	},
	skeletonBlock: {
		borderRadius: 999,
		borderCurve: "continuous",
	},
	heroCanvas: {
		minHeight: 240,
		overflow: "hidden",
		...squircle(30),
	},
	heroCanvasImage: {
		...squircle(30),
	},
	heroTopMask: {
		...StyleSheet.absoluteFillObject,
		bottom: undefined,
		height: 124,
	},
	heroCanvasInner: {
		flex: 1,
		paddingTop: 26,
		paddingHorizontal: 18,
		paddingBottom: 20,
		justifyContent: "space-between",
	},
	skeletonHeroCard: {
		minHeight: 228,
	},
	skeletonHeroInner: {
		flex: 1,
		paddingTop: 26,
		paddingHorizontal: 18,
		paddingBottom: 20,
		justifyContent: "space-between",
	},
	skeletonHeroBadgeRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	skeletonHeroBadge: {
		width: 88,
		height: 28,
	},
	skeletonHeroStatus: {
		width: 84,
		height: 28,
	},
	skeletonHeroCopy: {
		gap: 10,
	},
	skeletonHeroTitle: {
		width: "74%",
		height: 34,
		borderRadius: 14,
	},
	skeletonHeroSubtitle: {
		width: "46%",
		height: 20,
	},
	skeletonHeroSupport: {
		width: "58%",
		height: 18,
	},
	heroCanvasMetaRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 12,
	},
	heroBadgeRail: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		flex: 1,
	},
	heroBadge: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	heroBadgeText: {
		color: "#F8FAFC",
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
	},
	heroStatusChip: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	heroStatusText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		letterSpacing: 0.1,
	},
	heroCanvasBody: {
		gap: 6,
		paddingHorizontal: 14,
		paddingVertical: 14,
		borderRadius: 24,
		borderCurve: "continuous",
	},
	heroTitle: {
		color: "#F8FAFC",
		fontSize: 28,
		lineHeight: 32,
		fontWeight: "800",
	},
	heroSubtitle: {
		color: "rgba(248,250,252,0.94)",
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "600",
	},
	heroSupportLine: {
		color: "rgba(226,232,240,0.95)",
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "500",
	},
	heroFacilityLine: {
		color: "rgba(203,213,225,0.92)",
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	primaryButton: {
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 15,
		...squircle(18),
	},
	skeletonPrimaryButton: {
		height: 54,
		...squircle(18),
	},
	primaryButtonText: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
	},
	sectionCard: {
		paddingHorizontal: 16,
		paddingVertical: 16,
		...squircle(24),
		gap: 14,
	},
	sectionHeaderStatic: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	sectionHeaderPressable: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	sectionHeaderPressed: {
		opacity: 0.76,
	},
	sectionHeaderMeta: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		maxWidth: "52%",
	},
	sectionTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "600",
		flex: 1,
	},
	sectionSummary: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
		textAlign: "right",
	},
	detailList: {
		gap: 0,
	},
	detailRow: {
		minHeight: 46,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
		paddingVertical: 9,
	},
	skeletonDetailRow: {
		minHeight: 46,
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		paddingVertical: 9,
	},
	skeletonDetailIcon: {
		width: 30,
		height: 30,
		borderRadius: 15,
	},
	skeletonDetailCopy: {
		flex: 1,
		gap: 8,
	},
	skeletonDetailLabel: {
		width: "36%",
		height: 14,
	},
	skeletonDetailValue: {
		width: "58%",
		height: 16,
	},
	detailLeading: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		flex: 1,
		minWidth: 0,
	},
	detailIconWrap: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	detailLabel: {
		flex: 1,
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "500",
	},
	detailValue: {
		maxWidth: "48%",
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
		textAlign: "right",
	},
	detailRatingWrap: {
		flexShrink: 0,
		paddingLeft: 12,
	},
	ratingStarsRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 2,
	},
	detailHairline: {
		height: 1,
		marginLeft: 42,
	},
	routeCardChrome: {
		overflow: "hidden",
		borderRadius: 20,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 14,
		gap: 14,
	},
	routeCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	routeMetricRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	routeMetricPill: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	routeMetricText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
	},
	routeStatusText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		flexShrink: 1,
		textAlign: "right",
	},
	routeHeader: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 10,
	},
	routePill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 10,
		paddingVertical: 7,
		borderRadius: 999,
		borderCurve: "continuous",
	},
	routePillText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "600",
	},
	routeStops: {
		gap: 16,
		paddingLeft: 2,
	},
	routeConnectorTrack: {
		position: "absolute",
		left: 13,
		top: 6,
		bottom: 6,
		width: 2,
		borderRadius: 999,
	},
	routeConnectorProgress: {
		position: "absolute",
		left: 13,
		bottom: 6,
		width: 2,
		borderRadius: 999,
	},
	routeStopRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 12,
	},
	routeStopIconWrap: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	routeStopCopyWrap: {
		flex: 1,
		minWidth: 0,
		position: "relative",
		paddingRight: 8,
	},
	routeStopCopy: {
		flex: 1,
		minWidth: 0,
	},
	routeStopLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
	},
	routeStopTitle: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "600",
		marginTop: 2,
	},
	routeStopSubtitle: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 2,
	},
	routeStopFade: {
		position: "absolute",
		top: 0,
		right: 0,
		bottom: 0,
		width: 36,
	},
	preparationRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 10,
	},
	preparationDot: {
		width: 6,
		height: 6,
		borderRadius: 999,
		marginTop: 9,
	},
	preparationText: {
		flex: 1,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "400",
	},
	actionRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 4,
		gap: 14,
	},
	actionLabel: {
		flex: 1,
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "600",
	},
	actionHairline: {
		height: 1,
		marginLeft: 40,
	},
	cancelButton: {
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 15,
		...squircle(18),
	},
	cancelButtonText: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "700",
	},
});
