import { StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export const styles = StyleSheet.create({
	scrollContent: {
		paddingTop: 0,
		paddingHorizontal: 14,
		paddingBottom: 32,
		gap: 16,
	},
	skeletonBlock: {
		borderRadius: 999,
		borderCurve: "continuous",
	},
	heroCanvas: {
		minHeight: 240,
		overflow: "hidden",
		...squircle(30),
	},
	heroCanvasImage: {
		...squircle(30),
	},
	heroTopMask: {
		...StyleSheet.absoluteFillObject,
		bottom: undefined,
		height: 124,
	},
	heroCanvasInner: {
		flex: 1,
		paddingTop: 26,
		paddingHorizontal: 18,
		paddingBottom: 20,
		justifyContent: "space-between",
	},
	skeletonHeroCard: {
		minHeight: 228,
	},
	skeletonHeroInner: {
		flex: 1,
		paddingTop: 26,
		paddingHorizontal: 18,
		paddingBottom: 20,
		justifyContent: "space-between",
	},
	skeletonHeroBadgeRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	skeletonHeroBadge: {
		width: 88,
		height: 28,
	},
	skeletonHeroStatus: {
		width: 84,
		height: 28,
	},
	skeletonHeroCopy: {
		gap: 10,
	},
	skeletonHeroTitle: {
		width: "74%",
		height: 34,
		borderRadius: 14,
	},
	skeletonHeroSubtitle: {
		width: "46%",
		height: 20,
	},
	skeletonHeroSupport: {
		width: "58%",
		height: 18,
	},
	heroCanvasMetaRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 12,
	},
	heroBadgeRail: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		flex: 1,
	},
	heroBadge: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingHorizontal: 9,
		paddingVertical: 6,
		...squircle(999),
	},
	heroBadgeText: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	heroStatusChip: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	heroStatusText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		letterSpacing: 0.1,
	},
	heroCanvasBody: {
		gap: 6,
		paddingHorizontal: 14,
		paddingVertical: 14,
		borderRadius: 24,
		borderCurve: "continuous",
	},
	heroTitle: {
		color: "#F8FAFC",
		fontSize: 28,
		lineHeight: 32,
		fontWeight: "700",
	},
	heroSubtitle: {
		color: "rgba(248,250,252,0.94)",
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "500",
	},
	heroSupportLine: {
		color: "rgba(226,232,240,0.95)",
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "500",
	},
	heroFacilityLine: {
		color: "rgba(203,213,225,0.92)",
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	primaryButton: {
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 15,
		...squircle(18),
	},
	skeletonPrimaryButton: {
		height: 54,
		...squircle(18),
	},
	primaryButtonText: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
	},
	sectionCard: {
		paddingHorizontal: 16,
		paddingVertical: 16,
		...squircle(24),
		gap: 14,
	},
	skeletonDetailRow: {
		minHeight: 46,
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		paddingVertical: 9,
	},
	skeletonDetailIcon: {
		width: 30,
		height: 30,
		borderRadius: 15,
	},
	skeletonDetailCopy: {
		flex: 1,
		gap: 8,
	},
	skeletonDetailLabel: {
		width: "36%",
		height: 14,
	},
	skeletonDetailValue: {
		width: "58%",
		height: 16,
	},
	routeCardChrome: {
		overflow: "hidden",
		borderRadius: 20,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 14,
		gap: 14,
	},
	routeCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	routeMetricRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	routeMetricPill: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	routeMetricText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
	},
	routeStatusText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		flexShrink: 1,
		textAlign: "right",
	},
	routeHeader: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 10,
	},
	routePill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 10,
		paddingVertical: 7,
		borderRadius: 999,
		borderCurve: "continuous",
	},
	routePillText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "500",
	},
	routeStops: {
		gap: 16,
		paddingLeft: 2,
	},
	routeConnectorTrack: {
		position: "absolute",
		left: 13,
		top: 6,
		bottom: 6,
		width: 2,
		borderRadius: 999,
	},
	routeConnectorProgress: {
		position: "absolute",
		left: 13,
		bottom: 6,
		width: 2,
		borderRadius: 999,
	},
	routeStopRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 12,
	},
	routeStopIconWrap: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	routeStopCopyWrap: {
		flex: 1,
		minWidth: 0,
		position: "relative",
		paddingRight: 8,
	},
	routeStopCopy: {
		flex: 1,
		minWidth: 0,
	},
	routeStopLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
	},
	routeStopTitle: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "500",
		marginTop: 2,
	},
	routeStopSubtitle: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 2,
	},
	routeStopFade: {
		position: "absolute",
		top: 0,
		right: 0,
		bottom: 0,
		width: 36,
	},
	// ───────────────────────────────────────────────
	// Expanded passport layout (1:1 with mapHospitalDetail.styles.js).
	// Used when the sheet is at EXPANDED snap: the hero image hosts the place
	// header (orb + title + subtitle) overlaid on top, and the expandedBody
	// holds actions / stats / route / CTAs / sections.
	// ───────────────────────────────────────────────
	expandedCardWrap: {
		marginHorizontal: -14,
		overflow: "visible",
	},
	expandedHero: {
		height: 320,
		justifyContent: "space-between",
		zIndex: 1,
	},
	expandedHeroTopMask: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 118,
		zIndex: 1,
	},
	expandedHeroBottomMerge: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 144,
		zIndex: 1,
	},
	expandedHeroImage: {
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderCurve: "continuous",
	},
	expandedHeroBadgeRow: {
		paddingTop: 34,
		paddingHorizontal: 14,
		paddingRight: 62,
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
		zIndex: 2,
	},
	expandedHeaderBlock: {
		marginTop: "auto",
		paddingHorizontal: 20,
		paddingBottom: 10,
		alignItems: "center",
		zIndex: 2,
	},
	expandedHeaderMeasure: {
		width: "100%",
		alignItems: "center",
	},
	expandedPlaceMark: {
		width: 64,
		height: 64,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 10,
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		...squircle(19),
	},
	expandedPlaceTitle: {
		fontSize: 22,
		lineHeight: 27,
		fontWeight: "700",
		textAlign: "center",
		letterSpacing: -0.2,
	},
	expandedPlaceSubtitle: {
		marginTop: 2,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
		textAlign: "center",
		paddingHorizontal: 10,
	},
	expandedBody: {
		position: "relative",
		zIndex: 2,
		paddingHorizontal: 14,
		paddingTop: 8,
		paddingBottom: 20,
		gap: 12,
	},
	// ───────────────────────────────────────────────
	// Hospital-detail-style mid-snap layout
	// Matches hospital detail exactly (placeMark / placeTitle / placeSubtitle
	// live in placeHeader, revealed only in expanded; topSlot owns mid-snap identity).
	// ───────────────────────────────────────────────
	heroRevealFrame: {
		width: "100%",
		overflow: "hidden",
		marginHorizontal: -14,
	},
	hero: {
		height: 270,
		marginTop: 0,
		marginHorizontal: 0,
		overflow: "hidden",
		justifyContent: "space-between",
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderCurve: "continuous",
	},
	heroImage: {
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderCurve: "continuous",
	},
	heroBlend: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 168,
		zIndex: 1,
	},
	heroBottomMerge: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 126,
		zIndex: 1,
	},
	heroTopMask: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 104,
		zIndex: 1,
	},
	heroBadgeRow: {
		paddingTop: 34,
		paddingHorizontal: 14,
		paddingRight: 62,
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
		zIndex: 2,
	},
	heroFooter: {
		height: 44,
	},
	detailPanel: {
		marginHorizontal: -14,
		paddingHorizontal: 14,
		paddingTop: 46,
		paddingBottom: 20,
		gap: 10,
		overflow: "visible",
		...squircle(34),
	},
	detailPanelContent: {
		gap: 10,
	},
	midBodyContentGroup: {
		gap: 18,
	},
	placeHeaderReveal: {
		overflow: "hidden",
	},
	placeHeader: {
		alignItems: "center",
		paddingHorizontal: 16,
		gap: 4,
	},
	placeMark: {
		width: 64,
		height: 64,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 6,
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.24)",
		...squircle(19),
	},
	placeTitle: {
		fontSize: 23,
		lineHeight: 28,
		fontWeight: "700",
		textAlign: "center",
		letterSpacing: -0.2,
	},
	placeSubtitle: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
		textAlign: "center",
		paddingHorizontal: 10,
	},
	// Action row (matches hospital detail exactly)
	placeActionRow: {
		flexDirection: "row",
		gap: 7,
		paddingHorizontal: 0,
	},
	placeActionPressable: {
		flex: 1,
		minWidth: 0,
	},
	placeActionButton: {
		minHeight: 42,
		paddingHorizontal: 7,
		paddingVertical: 3,
		alignItems: "center",
		justifyContent: "center",
		gap: 2,
		...squircle(14),
	},
	placeActionButtonPrimary: {
		backgroundColor: COLORS.brandPrimary,
		shadowColor: COLORS.brandPrimary,
		shadowOpacity: 0.22,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 8 },
	},
	placeActionButtonPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.985 }],
	},
	placeActionButtonDisabled: {
		opacity: 0.48,
	},
	placeActionLabel: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		textAlign: "center",
	},
	// Stats card (matches hospital detail exactly)
	placeStatsCard: {
		marginTop: 6,
		marginBottom: 10,
		paddingHorizontal: 10,
		paddingVertical: 0,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 22,
	},
	placeStatsCardScroll: {
		marginTop: 8,
		marginBottom: 10,
		flexDirection: "row",
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		gap: 16,
	},
	placeStatItem: {
		alignItems: "center",
		gap: 4,
		minWidth: 58,
	},
	placeStatLabel: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "500",
	},
	placeStatValueRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 4,
	},
	placeStatValue: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
	},
	placeStatStars: {
		flexDirection: "row",
		alignItems: "center",
		gap: 1,
	},
});
