export const HELP_SUPPORT_SCREEN_COPY = {
  screen: {
    title: "Help & support",
    subtitle: "Concierge",
  },
  center: {
    title: "Support requests",
    faqTitle: "Common questions",
    newRequest: "New request",
    emptyTitle: "No support requests yet",
    emptyBody:
      "Start a request when you need help with visits, billing, or account issues.",
    emptyFaqTitle: "No answers yet",
    emptyFaqBody: "Refresh and try again.",
  },
  ask: {
    title: "Ask iVisit",
    body: "Get a quick answer from the support FAQs.",
    inputLabel: "Ask a support question",
    placeholder: "Ask about your account, coverage, or SOS",
    askAction: "Find an FAQ answer",
    sourceLabel: "Source",
    feedbackPrompt: "Was this useful?",
    usefulAction: "Useful",
    notUsefulAction: "Not useful",
    escalateAction: "Review a support request",
  },
  context: {
    title: "Support desk",
    body: "Open a request or check quick answers before you wait.",
    openLabel: "Open",
    answeredLabel: "Answered",
    faqLabel: "Answers",
    primaryAction: "New request",
  },
  island: {
    title: "Support actions",
    openLabel: "Open requests",
    latestLabel: "Latest request",
    statusLabel: "Status",
    faqLabel: "Quick answers",
    latestFallback: "No requests yet",
    refreshAction: "Refresh",
    retryAction: "Retry sync",
    composeAction: "New request",
  },
  rows: {
    response: "Response",
    awaitingReply: "Awaiting reply",
    openGroup: "Open",
    resolvedGroup: "Resolved",
    ticketDateFallback: "Just now",
    composerTitle: "New request",
    composerSubject: "Topic",
    composerSubjectPlaceholder: "What do you need help with?",
    composerMessage: "Message",
    composerMessagePlaceholder: "Tell us what happened and what you need next.",
    composerSubmit: "Send request",
    composerSubmitting: "Sending...",
    composerDiscard: "Discard",
  },
  messages: {
    ready: "Support ready",
    faqReady: "Answers ready",
    syncFailed: "Support sync needs a retry.",
  },
};

export default HELP_SUPPORT_SCREEN_COPY;
