import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

const TITLE_TEXT = Platform.select({
	ios: { fontSize: 27, lineHeight: 31, fontWeight: "800", letterSpacing: -0.65 },
	android: { fontSize: 27, lineHeight: 31, fontWeight: "800", letterSpacing: -0.65 },
	web: { fontSize: 25, lineHeight: 29, fontWeight: "700", letterSpacing: -0.45 },
	default: { fontSize: 27, lineHeight: 31, fontWeight: "800", letterSpacing: -0.65 },
});

const HERO_TITLE_TEXT = Platform.select({
	ios: { fontSize: 22, lineHeight: 26, fontWeight: "800", letterSpacing: -0.45 },
	android: { fontSize: 22, lineHeight: 26, fontWeight: "800", letterSpacing: -0.45 },
	web: { fontSize: 21, lineHeight: 25, fontWeight: "700", letterSpacing: -0.3 },
	default: { fontSize: 22, lineHeight: 26, fontWeight: "800", letterSpacing: -0.45 },
});

const styles = StyleSheet.create({
	bodyContent: {
		paddingBottom: 28,
	},
	webWideContentInset: {
		paddingHorizontal: 20,
	},
	topSlot: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 12,
		paddingTop: 4,
		paddingBottom: 10,
	},
	webWideTopSlotInset: {
		paddingHorizontal: 18,
	},
	topSlotCopy: {
		flex: 1,
		paddingHorizontal: 12,
		alignItems: "center",
	},
	topSlotTitle: {
		...TITLE_TEXT,
		textAlign: "center",
	},
	topSlotSubtitle: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		color: COLORS.textSecondary,
		marginTop: 2,
		textAlign: "center",
	},
	closeButton: {
		width: 38,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
	},
	sectionGap: {
		height: 14,
	},
	midSwitchSpacingTop: {
		height: 0,
	},
	midSwitchSpacingBottom: {
		height: 14,
	},
	heroCard: {
		borderRadius: 28,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingTop: 13,
		paddingBottom: 13,
		minHeight: 154,
		overflow: "hidden",
	},
	heroPressable: {
		borderRadius: 28,
	},
	heroArtworkLayer: {
		position: "absolute",
		right: -10,
		bottom: -4,
		left: 48,
		top: 6,
		alignItems: "center",
		justifyContent: "center",
	},
	heroImage: {
		width: "100%",
		height: "100%",
	},
	heroHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
		marginBottom: 8,
		zIndex: 2,
	},
	heroDetailChip: {
		width: 30,
		height: 30,
		alignItems: "center",
		justifyContent: "center",
	},
	heroRow: {
		flexDirection: "row",
		alignItems: "flex-end",
		zIndex: 2,
	},
	heroCopy: {
		flex: 1,
		paddingRight: 16,
		maxWidth: "58%",
	},
	heroTitle: {
		...HERO_TITLE_TEXT,
	},
	heroMetaRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginTop: 11,
	},
	metaPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		height: 30,
		paddingHorizontal: 11,
		borderRadius: 15,
		borderCurve: "continuous",
	},
	metaLabel: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "500",
	},
	metaSkeleton: {
		height: 10,
		borderRadius: 999,
		backgroundColor: "rgba(148,163,184,0.32)",
	},
	metaSkeletonShort: {
		width: 54,
	},
	metaSkeletonMedium: {
		width: 66,
	},
	switchRail: {
		marginHorizontal: -2,
	},
	switchScroller: {
		overflow: "visible",
	},
	switchRailContent: {
		paddingHorizontal: 2,
		gap: 8,
	},
	switchPill: {
		minHeight: 42,
		minWidth: 0,
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 16,
		borderCurve: "continuous",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: 1,
	},
	switchPillLabel: {
		fontSize: 11,
		lineHeight: 12,
		fontWeight: "400",
		textAlign: "center",
		flexShrink: 1,
		maxWidth: "100%",
	},
	routeCard: {
		borderRadius: 26,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingVertical: 10,
	},
	routeRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	routeTrack: {
		alignItems: "center",
		marginRight: 12,
	},
	routeNode: {
		width: 32,
		height: 32,
		borderRadius: 12,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	routeConnector: {
		width: 2,
		height: 24,
		borderRadius: 999,
		marginVertical: 3,
	},
	routeStops: {
		flex: 1,
		minWidth: 0,
	},
	routeStop: {
		minHeight: 28,
		justifyContent: "center",
	},
	routeStopGap: {
		height: 16,
	},
	routeStopTitle: {
		fontSize: Platform.OS === "web" ? 15 : 16,
		lineHeight: Platform.OS === "web" ? 18 : 19,
		fontWeight: Platform.OS === "web" ? "500" : "600",
		letterSpacing: -0.18,
		marginBottom: 1,
	},
	routeStopMetaWrap: {
		position: "relative",
		paddingRight: 18,
		minWidth: 0,
	},
	routeStopMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	routeStopMetaFade: {
		position: "absolute",
		top: "50%",
		right: 0,
		marginTop: -8,
		width: 24,
		height: 16,
		borderRadius: 8,
		borderCurve: "continuous",
	},
	routeMetrics: {
		marginLeft: 10,
		alignItems: "flex-end",
		justifyContent: "center",
		maxWidth: 82,
	},
	routeMetricPrimary: {
		fontSize: Platform.OS === "web" ? 15 : 16,
		lineHeight: Platform.OS === "web" ? 19 : 20,
		fontWeight: Platform.OS === "web" ? "700" : "800",
		textAlign: "right",
	},
	routeMetricSecondary: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		textAlign: "right",
		marginTop: 2,
	},
	savedTransportCard: {
		borderRadius: 24,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 12,
	},
	savedTransportHeader: {
		marginBottom: 10,
	},
	savedTransportPill: {
		alignSelf: "flex-start",
		height: 24,
		paddingHorizontal: 10,
		borderRadius: 12,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	savedTransportPillText: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "700",
		color: COLORS.brandPrimary,
	},
	savedTransportRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	savedTransportIconWrap: {
		width: 34,
		height: 34,
		borderRadius: 17,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	savedTransportCopy: {
		flex: 1,
		minWidth: 0,
	},
	savedTransportTitle: {
		fontSize: 15,
		lineHeight: 18,
		fontWeight: "700",
		letterSpacing: -0.18,
	},
	savedTransportMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 3,
	},
	expandedList: {
		gap: 10,
	},
	expandedRow: {
		minHeight: 78,
		borderRadius: 20,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
	},
	expandedLead: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		minWidth: 0,
	},
	expandedIconWrap: {
		width: 36,
		height: 36,
		borderRadius: 18,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	expandedCopy: {
		flex: 1,
		minWidth: 0,
		paddingRight: 10,
	},
	expandedTitle: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "700",
		letterSpacing: -0.25,
	},
	expandedMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 4,
	},
	expandedMetaSkeletonRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginTop: 6,
	},
	expandedMetaSkeletonShort: {
		width: 70,
	},
	expandedMetaSkeletonMedium: {
		width: 84,
	},
	expandedImage: {
		width: 72,
		height: 56,
		marginHorizontal: 8,
	},
	expandedActionWrap: {
		width: 24,
		height: 24,
		alignItems: "center",
		justifyContent: "center",
	},
	transportList: {
		gap: 10,
	},
	transportRow: {
		minHeight: 78,
		borderRadius: 20,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
	},
	transportLead: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		minWidth: 0,
	},
	transportIconWrap: {
		width: 36,
		height: 36,
		borderRadius: 18,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	transportCopy: {
		flex: 1,
		minWidth: 0,
		paddingRight: 10,
	},
	transportTitle: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "700",
		letterSpacing: -0.25,
	},
	transportMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 4,
	},
	transportArtworkWrap: {
		width: 84,
		height: 58,
		alignItems: "center",
		justifyContent: "center",
		marginHorizontal: 8,
	},
	detailsCard: {
		borderRadius: 24,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	detailsHeader: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 8,
		marginBottom: 10,
	},
	detailsPill: {
		height: 28,
		paddingHorizontal: 10,
		borderRadius: 14,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	detailsPillText: {
		fontSize: 11,
		lineHeight: 13,
		fontWeight: "500",
		color: COLORS.brandPrimary,
	},
	detailsSummary: {
		fontSize: 14,
		lineHeight: 19,
		fontWeight: "500",
		marginBottom: 10,
	},
	detailsFeatureRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginTop: 8,
	},
	detailsFeatureDot: {
		width: 6,
		height: 6,
		borderRadius: 999,
		backgroundColor: "rgba(134,16,14,0.72)",
		marginTop: 6,
		marginRight: 10,
	},
	detailsFeatureText: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "400",
	},
	emptyCard: {
		borderRadius: 26,
		borderCurve: "continuous",
		paddingHorizontal: 20,
		paddingVertical: 18,
	},
	emptyTitle: {
		fontSize: 20,
		lineHeight: 24,
		fontWeight: "800",
		letterSpacing: -0.35,
		marginBottom: 6,
	},
	emptyBody: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "600",
	},
	footerDock: {
		paddingHorizontal: 12,
		paddingTop: 8,
		paddingBottom: 10,
	},
	primaryButton: {
		width: "100%",
		shadowOffset: { width: 0, height: 10 },
		shadowRadius: 18,
	},
	secondaryAction: {
		height: 46,
		marginTop: 10,
		borderRadius: 23,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: 8,
	},
	secondaryActionText: {
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "700",
		color: COLORS.brandPrimary,
	},
});

export default styles;
