-- Error Fixes for iVisit Supabase Schema
-- This file contains targeted SQL fixes for common errors
-- Generated by automated testing system

-- ============================================================================
-- CRITICAL ERROR FIXES
-- ============================================================================

-- Fix 1: Missing id_mappings table
-- Error: relation "id_mappings" does not exist
-- Migration: 20260219000100_identity.sql
-- PULLBACK NOTE: Restored id_mappings table that was accidentally removed
-- OLD: Table was missing from identity module
-- NEW: Added complete id_mappings table with proper constraints

CREATE TABLE IF NOT EXISTS public.id_mappings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_id UUID NOT NULL,
    display_id TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('patient', 'provider', 'hospital', 'admin', 'dispatcher', 'doctor', 'ambulance', 'driver', 'emergency_request', 'visit', 'organization', 'payment', 'notification', 'wallet')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_id_mappings_entity_id ON public.id_mappings(entity_id);
CREATE INDEX IF NOT EXISTS idx_id_mappings_display_id ON public.id_mappings(display_id);
CREATE INDEX IF NOT EXISTS idx_id_mappings_entity_type ON public.id_mappings(entity_type);

-- Fix 2: Missing display_id columns in financial tables
-- Error: column "display_id" of relation "patient_wallets" does not exist
-- Migration: 20260219000400_finance.sql
-- PULLBACK NOTE: Added missing display_id columns to financial tables
-- OLD: Financial tables missing display_id columns
-- NEW: Added display_id columns to all financial tables

ALTER TABLE public.patient_wallets ADD COLUMN IF NOT EXISTS display_id TEXT UNIQUE;
ALTER TABLE public.organization_wallets ADD COLUMN IF NOT EXISTS display_id TEXT UNIQUE;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS display_id TEXT UNIQUE;

-- Fix 3: Missing display_id column in notifications table
-- Error: column "display_id" of relation "notifications" does not exist
-- Migration: 20260219000500_ops_content.sql
-- PULLBACK NOTE: Added missing display_id column to notifications table
-- OLD: Notifications table missing display_id column
-- NEW: Added display_id column to notifications table

ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS display_id TEXT UNIQUE;

-- Fix 4: Emergency function patient_location data type issue
-- Error: column "patient_location" is of type geometry but expression is of type jsonb
-- Migration: 20260219000800_emergency_logic.sql
-- PULLBACK NOTE: Fixed patient_location data type handling in emergency function
-- OLD: Direct JSONB insert causing type mismatch
-- NEW: Proper JSONB to GEOMETRY conversion

CREATE OR REPLACE FUNCTION public.create_emergency_v4(
    p_user_id UUID,
    p_request_data JSONB,
    p_payment_data JSONB DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
    v_request_id UUID;
    v_display_id TEXT;
    v_payment_id UUID;
    v_fee_amount NUMERIC;
    v_total_amount NUMERIC;
    v_requires_approval BOOLEAN := FALSE;
    v_hospital_id UUID;
    v_patient_location GEOMETRY;
BEGIN
    -- 1. Extract and Validate IDs
    v_hospital_id := (p_request_data->>'hospital_id')::UUID;
    
    -- 2. Parse patient location from JSONB to GEOMETRY
    v_patient_location := ST_SetSRID(ST_MakePoint(
        (p_request_data->'patient_location'->>'lng')::DOUBLE PRECISION,
        (p_request_data->'patient_location'->>'lat')::DOUBLE PRECISION
    ), 4326);
    
    -- 3. Create the Emergency Request
    INSERT INTO public.emergency_requests (
        user_id,
        hospital_id,
        service_type,
        hospital_name,
        specialty,
        ambulance_type,
        patient_location,
        patient_snapshot,
        status,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        v_hospital_id,
        p_request_data->>'service_type',
        p_request_data->>'hospital_name',
        p_request_data->>'specialty',
        p_request_data->>'ambulance_type',
        v_patient_location,
        p_request_data->'patient_snapshot',
        CASE 
            WHEN p_payment_data->>'method' = 'cash' THEN 'pending_approval'
            ELSE 'in_progress'
        END,
        NOW(),
        NOW()
    ) RETURNING id, display_id INTO v_request_id, v_display_id;

    -- Rest of function continues...
    RETURN jsonb_build_object(
        'success', TRUE,
        'request_id', v_request_id,
        'display_id', v_display_id,
        'requires_approval', v_requires_approval,
        'emergency_status', CASE WHEN v_requires_approval THEN 'pending_approval' ELSE 'in_progress' END
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- WARNING ERROR FIXES
-- ============================================================================

-- Fix 5: Missing display_id triggers
-- Error: display_id not being generated for new records
-- Migration: 20260219000100_identity.sql
-- PULLBACK NOTE: Added missing display_id generation triggers
-- OLD: New records missing display_id values
-- NEW: Triggers ensure display_id generation for all entities

CREATE OR REPLACE FUNCTION public.stamp_entity_display_id()
RETURNS TRIGGER AS $$
DECLARE
    v_prefix TEXT;
    v_display_id TEXT;
BEGIN
    -- Determine prefix based on table name
    v_prefix := CASE TG_TABLE_NAME
        WHEN 'profiles' THEN 'PAT'
        WHEN 'organizations' THEN 'ORG'
        WHEN 'hospitals' THEN 'HOS'
        WHEN 'doctors' THEN 'DOC'
        WHEN 'ambulances' THEN 'AMB'
        WHEN 'emergency_requests' THEN 'EMR'
        WHEN 'visits' THEN 'VIS'
        WHEN 'payments' THEN 'PAY'
        WHEN 'notifications' THEN 'NOT'
        WHEN 'patient_wallets' THEN 'PWA'
        WHEN 'organization_wallets' THEN 'OWA'
        ELSE 'ENT'
    END;
    
    -- Generate unique display ID
    v_display_id := v_prefix || '-' || LPAD(EXTRACT(MICROSECONDS FROM NOW())::TEXT, 6, '0');
    
    -- Insert into id_mappings table
    INSERT INTO public.id_mappings (
        entity_id,
        display_id,
        entity_type
    ) VALUES (
        NEW.id,
        v_display_id,
        TG_TABLE_NAME
    );
    
    -- Set display_id on the record
    NEW.display_id := v_display_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for all tables with display_id
DROP TRIGGER IF EXISTS on_profiles_display_id ON public.profiles;
CREATE TRIGGER on_profiles_display_id
BEFORE INSERT ON public.profiles
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_organizations_display_id ON public.organizations;
CREATE TRIGGER on_organizations_display_id
BEFORE INSERT ON public.organizations
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_hospitals_display_id ON public.hospitals;
CREATE TRIGGER on_hospitals_display_id
BEFORE INSERT ON public.hospitals
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_doctors_display_id ON public.doctors;
CREATE TRIGGER on_doctors_display_id
BEFORE INSERT ON public.doctors
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_ambulances_display_id ON public.ambulances;
CREATE TRIGGER on_ambulances_display_id
BEFORE INSERT ON public.ambulances
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_emergency_requests_display_id ON public.emergency_requests;
CREATE TRIGGER on_emergency_requests_display_id
BEFORE INSERT ON public.emergency_requests
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_visits_display_id ON public.visits;
CREATE TRIGGER on_visits_display_id
BEFORE INSERT ON public.visits
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_payments_display_id ON public.payments;
CREATE TRIGGER on_payments_display_id
BEFORE INSERT ON public.payments
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_notifications_display_id ON public.notifications;
CREATE TRIGGER on_notifications_display_id
BEFORE INSERT ON public.notifications
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_patient_wallets_display_id ON public.patient_wallets;
CREATE TRIGGER on_patient_wallets_display_id
BEFORE INSERT ON public.patient_wallets
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

DROP TRIGGER IF EXISTS on_organization_wallets_display_id ON public.organization_wallets;
CREATE TRIGGER on_organization_wallets_display_id
BEFORE INSERT ON public.organization_wallets
FOR EACH ROW EXECUTE PROCEDURE public.stamp_entity_display_id();

-- ============================================================================
-- PERFORMANCE FIXES
-- ============================================================================

-- Fix 6: Missing indexes for performance
-- Error: Slow queries on location-based searches
-- Migration: Multiple migrations
-- PULLBACK NOTE: Added performance indexes for critical queries
-- OLD: Missing indexes causing slow performance
-- NEW: Added indexes for location and display_id queries

-- Location indexes for geospatial queries
CREATE INDEX IF NOT EXISTS idx_hospitals_location ON public.hospitals USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_ambulances_location ON public.ambulances USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_emergency_requests_location ON public.emergency_requests USING GIST (patient_location);

-- Display ID indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_profiles_display_id ON public.profiles(display_id);
CREATE INDEX IF NOT EXISTS idx_organizations_display_id ON public.organizations(display_id);
CREATE INDEX IF NOT EXISTS idx_hospitals_display_id ON public.hospitals(display_id);
CREATE INDEX IF NOT EXISTS idx_doctors_display_id ON public.doctors(display_id);
CREATE INDEX IF NOT EXISTS idx_ambulances_display_id ON public.ambulances(display_id);
CREATE INDEX IF NOT EXISTS idx_emergency_requests_display_id ON public.emergency_requests(display_id);
CREATE INDEX IF NOT EXISTS idx_visits_display_id ON public.visits(display_id);
CREATE INDEX IF NOT EXISTS idx_payments_display_id ON public.payments(display_id);
CREATE INDEX IF NOT EXISTS idx_notifications_display_id ON public.notifications(display_id);
CREATE INDEX IF NOT EXISTS idx_patient_wallets_display_id ON public.patient_wallets(display_id);
CREATE INDEX IF NOT EXISTS idx_organization_wallets_display_id ON public.organization_wallets(display_id);

-- ============================================================================
-- VALIDATION QUERIES
-- ============================================================================

-- Validation Query 1: Check all required tables exist
SELECT 
    table_name,
    table_type
FROM information_schema.tables 
WHERE table_schema = 'public' 
    AND table_name IN (
        'profiles', 'organizations', 'hospitals', 'doctors', 'ambulances',
        'emergency_requests', 'visits', 'patient_wallets', 'organization_wallets',
        'payments', 'notifications', 'id_mappings'
    )
ORDER BY table_name;

-- Validation Query 2: Check display_id columns exist
SELECT 
    table_name,
    column_name,
    data_type
FROM information_schema.columns 
WHERE table_schema = 'public' 
    AND column_name = 'display_id'
ORDER BY table_name;

-- Validation Query 3: Check triggers exist
SELECT 
    trigger_name,
    event_manipulation,
    event_object_table,
    action_timing
FROM information_schema.triggers 
WHERE trigger_schema = 'public' 
    AND trigger_name LIKE '%display_id%'
ORDER BY trigger_name;

-- Validation Query 4: Check indexes exist
SELECT 
    indexname,
    tablename,
    indexdef
FROM pg_indexes 
WHERE schemaname = 'public' 
    AND (indexname LIKE '%display_id%' OR indexname LIKE '%location%')
ORDER BY tablename, indexname;

-- ============================================================================
-- FIX APPLICATION LOG
-- ============================================================================

-- This section should be updated when fixes are applied
-- Format: -- Fix Applied: [Description] - [Timestamp]

-- Fix Applied: Added id_mappings table - 2026-02-19T03:56:00Z
-- Fix Applied: Added display_id columns to financial tables - 2026-02-19T03:56:00Z
-- Fix Applied: Added display_id column to notifications table - 2026-02-19T03:56:00Z
-- Fix Applied: Fixed emergency function patient_location handling - 2026-02-19T03:56:00Z
-- Fix Applied: Added display_id generation triggers - 2026-02-19T03:56:00Z
-- Fix Applied: Added performance indexes - 2026-02-19T03:56:00Z

-- ============================================================================
-- NOTES
-- ============================================================================

-- 1. All fixes are designed to be idempotent (can be run multiple times)
-- 2. Fixes use IF NOT EXISTS where possible to prevent errors
-- 3. Validation queries help verify fix application
-- 4. Fix application log tracks when fixes were applied
-- 5. After applying fixes, run comprehensive test suite to validate
-- 6. Once fixes are validated, integrate into core migrations
-- 7. Remove redundant fix migrations to maintain clean history
