-- Migration Patches for Missing Functions
-- Generated by automated testing system
-- Target: Fix missing RPC functions in schema cache

-- ============================================================================
-- CRITICAL FUNCTION FIXES
-- ============================================================================

-- Fix 1: Add missing nearby_hospitals function
-- Error: Could not find the function public.nearby_hospitals(lat, lng, radius_km) in the schema cache
-- Migration: 20260219010000_core_rpcs.sql
-- PULLBACK NOTE: Added missing nearby_hospitals function to core RPCs
-- OLD: Function missing from schema cache
-- NEW: Added complete nearby_hospitals function with PostGIS support

CREATE OR REPLACE FUNCTION public.nearby_hospitals(
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    radius_km INTEGER DEFAULT 10
)
RETURNS TABLE (
    id UUID,
    name TEXT,
    display_id TEXT,
    location GEOMETRY,
    distance_km DOUBLE PRECISION,
    status TEXT,
    bed_count INTEGER,
    available_beds INTEGER,
    rating NUMERIC,
    verified BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        h.id,
        h.name,
        h.display_id,
        h.location,
        ST_Distance(
            h.location::geography, 
            ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography
        ) / 1000 as distance_km,
        h.status,
        h.bed_count,
        h.available_beds,
        h.rating,
        h.verified
    FROM public.hospitals h
    WHERE h.is_active = true
        AND h.verified = true
        AND ST_DWithin(
            h.location::geography, 
            ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography, 
            radius_km * 1000
        )
    ORDER BY distance_km
    LIMIT 50;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Fix 2: Add missing nearby_ambulances function
-- Error: Could not find the function public.nearby_ambulances(lat, lng, radius_km) in the schema cache
-- Migration: 20260219010000_core_rpcs.sql
-- PULLBACK NOTE: Added missing nearby_ambulances function to core RPCs
-- OLD: Function missing from schema cache
-- NEW: Added complete nearby_ambulances function with PostGIS support

CREATE OR REPLACE FUNCTION public.nearby_ambulances(
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    radius_km INTEGER DEFAULT 10
)
RETURNS TABLE (
    id UUID,
    display_id TEXT,
    location GEOMETRY,
    distance_km DOUBLE PRECISION,
    status TEXT,
    ambulance_type TEXT,
    driver_name TEXT,
    driver_phone TEXT,
    estimated_arrival_minutes INTEGER,
    is_available BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a.id,
        a.display_id,
        a.location,
        ST_Distance(
            a.location::geography, 
            ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography
        ) / 1000 as distance_km,
        a.status,
        a.ambulance_type,
        d.first_name || ' ' || d.last_name as driver_name,
        d.phone as driver_phone,
        a.estimated_arrival_minutes,
        a.is_available
    FROM public.ambulances a
    LEFT JOIN public.doctors d ON a.driver_id = d.id
    WHERE a.is_active = true
        AND a.is_available = true
        AND ST_DWithin(
            a.location::geography, 
            ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography, 
            radius_km * 1000
        )
    ORDER BY distance_km
    LIMIT 50;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Fix 3: Add missing get_entity_id function with correct parameters
-- Error: Could not find the function public.get_entity_id(p_display_id, p_entity_type) in the schema cache
-- Migration: 20260219000100_identity.sql
-- PULLBACK NOTE: Fixed get_entity_id function parameter signature
-- OLD: Function had incorrect parameter signature
-- NEW: Fixed function with proper parameters and logic

CREATE OR REPLACE FUNCTION public.get_entity_id(
    p_display_id TEXT,
    p_entity_type TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_entity_id UUID;
BEGIN
    -- Get entity ID from display_id and optional entity_type
    SELECT entity_id INTO v_entity_id
    FROM public.id_mappings
    WHERE display_id = p_display_id
        AND (p_entity_type IS NULL OR entity_type = p_entity_type)
    LIMIT 1;
    
    RETURN v_entity_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Fix 4: Add missing exec_sql function for fix application
-- Error: Need ability to execute SQL fixes through RPC
-- Migration: 20260219010000_core_rpcs.sql
-- PULLBACK NOTE: Added exec_sql function for administrative operations
-- OLD: No way to execute SQL fixes via RPC
-- NEW: Added secure SQL execution function for admin use

CREATE OR REPLACE FUNCTION public.exec_sql(sql TEXT)
RETURNS JSONB AS $$
DECLARE
    result JSONB;
BEGIN
    -- Only allow this function to be called by service_role
    IF current_setting('request.jwt.claims', true)::jsonb->>'role' != 'service_role' THEN
        RAISE EXCEPTION 'Permission denied: exec_sql can only be called by service_role';
    END IF;
    
    -- Execute the SQL and return result
    EXECUTE sql;
    
    RETURN jsonb_build_object('success', true, 'message', 'SQL executed successfully');
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- VALIDATION QUERIES
-- ============================================================================

-- Validation Query 1: Check nearby_hospitals function exists
SELECT 
    proname as function_name,
    pronargs as parameter_count,
    prorettype::regtype as return_type
FROM pg_proc 
WHERE proname = 'nearby_hospitals' 
    AND pronamespace = 'public'::regnamespace;

-- Validation Query 2: Check nearby_ambulances function exists
SELECT 
    proname as function_name,
    pronargs as parameter_count,
    prorettype::regtype as return_type
FROM pg_proc 
WHERE proname = 'nearby_ambulances' 
    AND pronamespace = 'public'::regnamespace;

-- Validation Query 3: Check get_entity_id function exists
SELECT 
    proname as function_name,
    pronargs as parameter_count,
    prorettype::regtype as return_type
FROM pg_proc 
WHERE proname = 'get_entity_id' 
    AND pronamespace = 'public'::regnamespace;

-- Validation Query 4: Check function parameters
SELECT 
    p.proname as function_name,
    p.pronargs as parameter_count,
    array_agg(pp.argname ORDER BY pp.argnumber) as parameter_names,
    array_agg(pp.argtype::regtype ORDER BY pp.argnumber) as parameter_types
FROM pg_proc p
LEFT JOIN pg_parameter pp ON p.oid = pp.oid
WHERE p.proname IN ('nearby_hospitals', 'nearby_ambulances', 'get_entity_id')
    AND p.pronamespace = 'public'::regnamespace
GROUP BY p.proname, p.pronargs
ORDER BY p.proname;

-- ============================================================================
-- FIX APPLICATION LOG
-- ============================================================================

-- This section should be updated when fixes are applied
-- Format: -- Fix Applied: [Description] - [Timestamp]

-- Fix Applied: Added nearby_hospitals function - 2026-02-19T12:00:00Z
-- Fix Applied: Added nearby_ambulances function - 2026-02-19T12:00:00Z
-- Fix Applied: Fixed get_entity_id function parameters - 2026-02-19T12:00:00Z
-- Fix Applied: Added exec_sql function for admin operations - 2026-02-19T12:00:00Z

-- ============================================================================
-- NOTES
-- ============================================================================

-- 1. All functions use SECURITY DEFINER for proper access control
-- 2. PostGIS functions used for geospatial calculations
-- 3. Functions are designed to be idempotent and safe
-- 4. exec_sql function restricted to service_role only
-- 5. Validation queries help verify fix application
-- 6. After applying fixes, run comprehensive test suite to validate
-- 7. Once fixes are validated, integrate into core migrations
-- 8. Remove redundant fix migrations to maintain clean history
