export const MAP_AMBULANCE_DECISION_COPY = {
  TITLE: "Dispatch choice",
  SUMMARY: null,
  ETA_LABEL: "ETA",
  DISTANCE_LABEL: "Distance",
  PRICE_LABEL: "Estimated cost",
  PRICE_FALLBACK: "Shown before payment",
  ETA_FALLBACK: "Arriving soon",
  ROUTE_PENDING: "Route updating",
  CONFIDENCE_LIVE: "Live hospital pricing",
  CONFIDENCE_FALLBACK: "Hospital fallback",
  CONFIRM_CTA: "Confirm & continue",
  CONTINUING_CTA: "Continuing...",
  RECOVER_CTA: "Choose another hospital",
  UNAVAILABLE_CTA: "No dispatch available",
  OTHER_HOSPITALS_CTA: "Other hospitals",
  SERVICE_DETAILS_CTA: "Details",
  COMBINED_STEP_SUBTITLE: "Step 1 of 2 · Choose transport",
  CURRENT_PILL: "Current",
  ROUTE_SOURCE_FALLBACK: "Dispatch origin",
  ROUTE_DESTINATION_TITLE: "My location",
  ROUTE_DESTINATION_SUBTITLE: "Current pickup point",
  NO_HOSPITAL_TITLE: "No dispatch candidate yet",
  NO_HOSPITAL_BODY: "Choose another hospital before you continue.",
};

export default MAP_AMBULANCE_DECISION_COPY;
