import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

const TITLE_TEXT = Platform.select({
	ios: { fontSize: 27, lineHeight: 31, fontWeight: "700", letterSpacing: -0.65 },
	android: { fontSize: 27, lineHeight: 31, fontWeight: "700", letterSpacing: -0.65 },
	web: { fontSize: 25, lineHeight: 29, fontWeight: "700", letterSpacing: -0.45 },
	default: { fontSize: 27, lineHeight: 31, fontWeight: "700", letterSpacing: -0.65 },
});

const HERO_TITLE_TEXT = Platform.select({
	ios: { fontSize: 22, lineHeight: 26, fontWeight: "700", letterSpacing: -0.45 },
	android: { fontSize: 22, lineHeight: 26, fontWeight: "700", letterSpacing: -0.45 },
	web: { fontSize: 21, lineHeight: 25, fontWeight: "700", letterSpacing: -0.3 },
	default: { fontSize: 22, lineHeight: 26, fontWeight: "700", letterSpacing: -0.45 },
});

const HOSPITAL_TITLE_TEXT = Platform.select({
	ios: { fontSize: 19, lineHeight: 23, fontWeight: "700", letterSpacing: -0.32 },
	android: { fontSize: 19, lineHeight: 23, fontWeight: "700", letterSpacing: -0.32 },
	web: { fontSize: 18, lineHeight: 22, fontWeight: "700", letterSpacing: -0.2 },
	default: { fontSize: 19, lineHeight: 23, fontWeight: "700", letterSpacing: -0.32 },
});

const styles = StyleSheet.create({
	bodyContent: {
		paddingBottom: 28,
	},
	webWideContentInset: {
		paddingHorizontal: 20,
	},
	topSlot: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 12,
		paddingTop: 4,
		paddingBottom: 10,
	},
	webWideTopSlotInset: {
		paddingHorizontal: 18,
	},
	topSlotCopy: {
		flex: 1,
		paddingHorizontal: 12,
		alignItems: "center",
	},
	topSlotTitle: {
		...TITLE_TEXT,
		textAlign: "center",
	},
	topSlotSubtitle: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		color: COLORS.textSecondary,
		marginTop: 2,
		textAlign: "center",
	},
	closeButton: {
		width: 38,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
	},
	headerActionSpacer: {
		width: 38,
		height: 38,
	},
	midSwitchSpacingTop: {
		height: 0,
	},
	midSwitchSpacingBottom: {
		height: 14,
	},
	sectionGap: {
		height: 14,
	},
	heroCard: {
		borderRadius: 28,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingTop: 13,
		paddingBottom: 13,
		minHeight: 158,
		overflow: "hidden",
	},
	heroPressable: {
		borderRadius: 28,
	},
	heroArtworkLayer: {
		position: "absolute",
		right: -10,
		bottom: -4,
		left: 48,
		top: 6,
		alignItems: "center",
		justifyContent: "center",
	},
	heroHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
		marginBottom: 9,
		zIndex: 2,
	},
	heroDetailChip: {
		width: 30,
		height: 30,
		alignItems: "center",
		justifyContent: "center",
	},
	heroDetailChipText: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "500",
	},
	heroRow: {
		flexDirection: "row",
		alignItems: "flex-end",
		zIndex: 2,
	},
	heroCopy: {
		flex: 1,
		paddingRight: 16,
		maxWidth: "58%",
	},
	heroTitle: {
		...HERO_TITLE_TEXT,
	},
	heroSummary: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "500",
	},
	heroMetaRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginTop: 11,
	},
	metaPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		height: 30,
		paddingHorizontal: 11,
		borderRadius: 15,
		borderCurve: "continuous",
	},
	metaLabel: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "500",
	},
	switchRow: {
		flexDirection: "row",
		alignItems: "stretch",
		gap: 8,
		width: "100%",
	},
	switchPill: {
		minHeight: 42,
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 16,
		borderCurve: "continuous",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: 1,
		position: "relative",
	},
	switchPillLabel: {
		fontSize: 11,
		lineHeight: 12,
		fontWeight: "400",
		textAlign: "center",
		flexShrink: 1,
		maxWidth: "100%",
	},
	routeCard: {
		borderRadius: 26,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingVertical: 10,
	},
	routeRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	routeTrack: {
		alignItems: "center",
		marginRight: 12,
	},
	routeNode: {
		width: 32,
		height: 32,
		borderRadius: 12,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	routeConnector: {
		width: 2,
		height: 26,
		borderRadius: 999,
		marginVertical: 3,
	},
	routeStops: {
		flex: 1,
		minWidth: 0,
	},
	routeStop: {
		minHeight: 28,
		justifyContent: "center",
	},
	routeStopGap: {
		height: 18,
	},
	routeStopTitle: {
		fontSize: Platform.OS === "web" ? 15 : 16,
		lineHeight: Platform.OS === "web" ? 18 : 19,
		fontWeight: Platform.OS === "web" ? "500" : "500",
		letterSpacing: -0.18,
		marginBottom: 1,
	},
	routeStopMetaWrap: {
		position: "relative",
		paddingRight: 18,
		minWidth: 0,
	},
	routeStopMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	routeStopMetaFade: {
		position: "absolute",
		top: "50%",
		right: 0,
		marginTop: -8,
		width: 24,
		height: 16,
		borderRadius: 8,
		borderCurve: "continuous",
	},
	routeMetrics: {
		marginLeft: 10,
		alignItems: "flex-end",
		justifyContent: "center",
		maxWidth: 82,
	},
	routeMetricPrimary: {
		fontSize: Platform.OS === "web" ? 15 : 16,
		lineHeight: Platform.OS === "web" ? 19 : 20,
		fontWeight: Platform.OS === "web" ? "700" : "700",
		textAlign: "right",
	},
	routeMetricSecondary: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		textAlign: "right",
		marginTop: 2,
	},
	expandedChoicesWrap: {
		gap: 10,
	},
	expandedChoiceCard: {
		minHeight: 78,
		borderRadius: 20,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
	},
	expandedChoiceInfo: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		minWidth: 0,
	},
	expandedChoiceIconWrap: {
		width: 36,
		height: 36,
		borderRadius: 18,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	expandedChoiceCopy: {
		flex: 1,
		minWidth: 0,
		paddingRight: 10,
	},
	expandedChoiceTitle: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "700",
		letterSpacing: -0.25,
	},
	expandedChoiceMeta: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		marginTop: 4,
	},
	expandedChoiceArtworkWrap: {
		width: 88,
		height: 60,
		alignItems: "center",
		justifyContent: "center",
		marginHorizontal: 8,
	},
	expandedChoiceActionWrap: {
		width: 24,
		height: 24,
		alignItems: "center",
		justifyContent: "center",
	},
	optionStatePill: {
		height: 28,
		paddingHorizontal: 10,
		borderRadius: 14,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	optionStateText: {
		fontSize: 11,
		lineHeight: 13,
		fontWeight: "700",
		color: COLORS.brandPrimary,
	},
	detailsCard: {
		borderRadius: 24,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	detailsHeader: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 8,
		marginBottom: 10,
	},
	detailsConfidencePill: {
		height: 28,
		paddingHorizontal: 10,
		borderRadius: 14,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	detailsConfidenceText: {
		fontSize: 11,
		lineHeight: 13,
		fontWeight: "500",
		color: COLORS.brandPrimary,
	},
	detailsSummary: {
		fontSize: 14,
		lineHeight: 19,
		fontWeight: "500",
		marginBottom: 10,
	},
	detailsFeatureRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginTop: 8,
	},
	detailsFeatureDot: {
		width: 6,
		height: 6,
		borderRadius: 999,
		backgroundColor: "rgba(134,16,14,0.72)",
		marginTop: 6,
		marginRight: 10,
	},
	detailsFeatureText: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "400",
	},
	emptyCard: {
		borderRadius: 26,
		borderCurve: "continuous",
		paddingHorizontal: 20,
		paddingVertical: 18,
	},
	emptyTitle: {
		fontSize: 20,
		lineHeight: 24,
		fontWeight: "700",
		letterSpacing: -0.35,
		marginBottom: 6,
	},
	emptyBody: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "500",
	},
	footerDock: {
		paddingHorizontal: 12,
		paddingTop: 8,
		paddingBottom: 10,
	},
	primaryButton: {
		width: "100%",
		shadowOffset: { width: 0, height: 10 },
		shadowRadius: 18,
	},
	secondaryAction: {
		height: 46,
		marginTop: 10,
		borderRadius: 23,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: 8,
	},
	secondaryActionText: {
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "700",
		color: COLORS.brandPrimary,
	},
});

export default styles;
