import { Platform, StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export default StyleSheet.create({
	topSlot: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 14,
		paddingBottom: 0,
		paddingTop: 0,
		marginTop: Platform.OS === "android" ? -6 : 0,
	},
	topSlotSpacer: {
		width: 38,
		height: 38,
	},
	topSlotTitle: {
		flex: 1,
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "700",
		textAlign: "center",
		paddingHorizontal: 8,
	},
	topSlotAction: {
		width: 38,
		height: 38,
	},
	topSlotCloseButton: {
		width: 38,
		height: 38,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
	},
	topSlotPressed: {
		opacity: 0.92,
		transform: [{ scale: 0.97 }],
	},
	bodyContent: {
		paddingHorizontal: 14,
		paddingTop: Platform.OS === "android" ? 2 : 0,
		paddingBottom: 28,
	},
	webWideContentInset: {
		paddingHorizontal: 20,
	},
	webWideTopSlotInset: {
		paddingHorizontal: 18,
	},
	sectionSpacer: {
		height: Platform.OS === "android" ? 18 : 16,
	},
	sectionSpacerLarge: {
		height: Platform.OS === "android" ? 20 : 18,
	},
	headerBlock: {
		paddingHorizontal: 18,
		paddingVertical: 16,
		...squircle(28),
	},
	headerMetaRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	headerTypePill: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 10,
		height: 28,
		borderRadius: 999,
	},
	headerTypeLabel: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "700",
	},
	positionLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "500",
		marginLeft: 12,
	},
	summary: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "400",
		marginTop: 10,
	},
	headerAssistiveLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
		marginTop: 8,
	},
	switchRow: {
		flexDirection: "row",
		alignItems: "stretch",
		gap: 8,
		width: "100%",
	},
	switchPill: {
		minHeight: 42,
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 16,
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: 1,
		position: "relative",
		...squircle(16),
	},
	switchPillLabel: {
		fontSize: 11,
		lineHeight: 13,
		fontWeight: "500",
		textAlign: "center",
		flexShrink: 1,
		maxWidth: "100%",
	},
	heroCard: {
		height: 160,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		...squircle(30),
	},
	heroImage: {
		width: "100%",
		height: "100%",
	},
	heroOverlay: {
		position: "absolute",
		left: 14,
		right: 14,
		bottom: 12,
	},
	heroMetaRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	metaPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		height: 30,
		paddingHorizontal: 11,
		borderRadius: 15,
		borderCurve: "continuous",
		maxWidth: "100%",
	},
	metaLabel: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "500",
		flexShrink: 1,
	},
	metricRow: {
		flexDirection: "row",
		flexWrap: "wrap",
	},
	metricPillSpaced: {
		marginRight: 10,
		marginBottom: Platform.OS === "android" ? 8 : 0,
	},
	metricPill: {
		height: 36,
		paddingHorizontal: 12,
		borderRadius: 999,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	metricIconBox: {
		width: 16,
		height: 16,
		alignItems: "center",
		justifyContent: "center",
	},
	metricText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		marginLeft: 6,
		includeFontPadding: false,
		textAlignVertical: "center",
	},
	sectionLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
		marginBottom: 12,
	},
	optionList: {
		gap: 10,
	},
	optionRow: {
		minHeight: 72,
		paddingHorizontal: 14,
		paddingVertical: 12,
		borderRadius: 22,
		flexDirection: "row",
		alignItems: "center",
		...squircle(22),
	},
	optionRowSpaced: {
		marginTop: 10,
	},
	optionLead: {
		flex: 1,
		minWidth: 0,
		paddingRight: 10,
		flexDirection: "row",
		alignItems: "center",
	},
	optionIconWrap: {
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 12,
	},
	optionCopy: {
		flex: 1,
		minWidth: 0,
	},
	optionImage: {
		width: 60,
		height: 42,
		marginRight: 10,
	},
	optionTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "700",
		letterSpacing: -0.2,
	},
	optionMeta: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		marginTop: 2,
	},
	featureList: {
		paddingHorizontal: 16,
		paddingVertical: 14,
		...squircle(24),
	},
	featureRow: {
		flexDirection: "row",
		alignItems: "flex-start",
	},
	featureRowSpaced: {
		marginTop: 12,
	},
	featureDot: {
		width: 7,
		height: 7,
		borderRadius: 3.5,
		marginTop: 6,
		marginRight: 11,
	},
	featureText: {
		flex: 1,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "500",
	},
	footerGap: {
		height: 10,
	},
	footerDock: {
		paddingHorizontal: 0,
		paddingBottom: Platform.OS === "android" ? 6 : 2,
	},
	primaryButton: {
		shadowOffset: { width: 0, height: 12 },
		shadowRadius: 18,
		borderCurve: "continuous",
	},
});
