import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

const styles = StyleSheet.create({
	bodyContent: {
		flexGrow: 1,
		paddingTop: 10,
		paddingBottom: 12,
	},
	webWideContentInset: {
		paddingLeft: 26,
		paddingRight: 26,
	},
	sectionStack: {
		gap: 14,
	},
	overlaySurfaceShell: {
		overflow: "hidden",
	},
	heroCard: {
		minHeight: 276,
		overflow: "hidden",
		shadowColor: "#0F172A",
		shadowOpacity: 0.18,
		shadowRadius: 26,
		shadowOffset: { width: 0, height: 16 },
		elevation: 10,
		...squircle(32),
	},
	heroImageFrame: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
	},
	heroVeil: {
		...StyleSheet.absoluteFillObject,
		zIndex: 1,
	},
	overlaySurfaceGradient: {
		...StyleSheet.absoluteFillObject,
	},
	heroImage: {
		...squircle(32),
	},
	heroBlend: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 176,
		zIndex: 1,
	},
	heroBottomMerge: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 138,
		zIndex: 1,
	},
	heroTopMask: {
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 112,
		zIndex: 1,
	},
	heroContent: {
		flex: 1,
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 18,
		zIndex: 2,
	},
	heroTopRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 12,
	},
	heroTopRowTrailing: {
		justifyContent: "flex-end",
	},
	heroHeaderCopy: {
		flex: 1,
		minWidth: 0,
		overflow: "hidden",
		paddingTop: 4,
		paddingHorizontal: 14,
		paddingBottom: 12,
		...squircle(26),
	},
	heroHeaderTitle: {
		fontSize: 22,
		lineHeight: 27,
		fontWeight: "800",
		letterSpacing: -0.5,
	},
	heroHeaderSubtitle: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	heroPrimaryActionPressable: {
		flexShrink: 0,
	},
	heroPrimaryActionPressed: {
		opacity: 0.96,
		transform: [{ scale: 0.985 }],
	},
	heroPrimaryAction: {
		minWidth: 132,
		paddingHorizontal: 14,
		paddingTop: 11,
		paddingBottom: 12,
		overflow: "hidden",
		shadowColor: "#0F172A",
		shadowOpacity: 0.24,
		shadowRadius: 16,
		shadowOffset: { width: 0, height: 10 },
		...squircle(26),
	},
	heroPrimaryActionDisabled: {
		opacity: 0.72,
	},
	heroPrimaryActionLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "800",
		letterSpacing: 0.35,
		textTransform: "uppercase",
	},
	heroPrimaryActionValueRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginTop: 5,
		minHeight: 28,
	},
	heroPrimaryActionValue: {
		fontSize: 24,
		lineHeight: 28,
		fontWeight: "900",
		letterSpacing: -0.72,
	},
	heroPrimaryActionSkeletonWrap: {
		gap: 6,
	},
	heroPrimaryActionSkeleton: {
		height: 12,
		width: 84,
		backgroundColor: "rgba(255,255,255,0.72)",
		...squircle(999),
	},
	heroPrimaryActionHint: {
		marginTop: 4,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "600",
	},
	heroSummaryList: {
		gap: 12,
		paddingTop: 16,
	},
	heroSummaryRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		overflow: "hidden",
		paddingHorizontal: 12,
		paddingVertical: 10,
		...squircle(24),
	},
	heroSummaryMedia: {
		width: 46,
		height: 46,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		...squircle(17),
	},
	heroSummaryImage: {
		width: "100%",
		height: "100%",
	},
	heroSummaryCopyWrap: {
		flex: 1,
		minWidth: 0,
		position: "relative",
		justifyContent: "center",
	},
	heroSummaryCopy: {
		flex: 1,
		minWidth: 0,
		paddingRight: 20,
	},
	heroSummaryFade: {
		position: "absolute",
		top: 0,
		right: 0,
		bottom: 0,
		width: 34,
	},
	heroSummaryTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.28,
	},
	heroSummarySubtitle: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: -0.08,
	},
	selectorCard: {
		paddingHorizontal: 14,
		paddingVertical: 16,
		overflow: "hidden",
		...squircle(28),
	},
	selectorHeader: {
		paddingHorizontal: 4,
	},
	selectorTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	selectorTitleCopy: {
		flex: 1,
		minWidth: 0,
	},
	selectorTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.28,
	},
	selectorDescription: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "500",
	},
	selectorBody: {
		marginTop: 12,
	},
	paymentSummaryRow: {
		marginTop: 12,
		minHeight: 54,
		paddingLeft: 16,
		paddingRight: 8,
		paddingVertical: 7,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
		...squircle(22),
	},
	paymentSummaryRowPressed: {
		opacity: 0.9,
		transform: [{ scale: 0.995 }],
	},
	paymentSummaryText: {
		flex: 1,
		minWidth: 0,
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.18,
	},
	paymentChangePill: {
		minHeight: 38,
		paddingHorizontal: 15,
		alignItems: "center",
		justifyContent: "center",
		flexShrink: 0,
		...squircle(19),
	},
	paymentChangeText: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "800",
		letterSpacing: -0.08,
	},
	breakdownCard: {
		paddingHorizontal: 18,
		paddingVertical: 16,
		...squircle(24),
	},
	breakdownTitle: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
		letterSpacing: -0.2,
	},
	breakdownList: {
		marginTop: 10,
	},
	breakdownRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 14,
		paddingVertical: 8,
	},
	breakdownRowLabel: {
		flex: 1,
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
	},
	breakdownRowValue: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	breakdownDivider: {
		height: StyleSheet.hairlineWidth,
		marginTop: 4,
		marginBottom: 2,
	},
	breakdownTotalRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 14,
		paddingTop: 10,
	},
	breakdownTotalLabel: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
	},
	breakdownTotalValue: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
		letterSpacing: -0.2,
	},
	breakdownSkeletonTitle: {
		height: 15,
		width: 116,
		...squircle(999),
	},
	breakdownSkeletonLabel: {
		height: 13,
		width: "58%",
		...squircle(999),
	},
	breakdownSkeletonLabelShort: {
		width: "44%",
	},
	breakdownSkeletonValue: {
		height: 13,
		width: 58,
		...squircle(999),
	},
	breakdownSkeletonTotalLabel: {
		height: 14,
		width: 56,
		...squircle(999),
	},
	breakdownSkeletonTotalValue: {
		height: 18,
		width: 86,
		...squircle(999),
	},
	infoGroupCard: {
		paddingHorizontal: 16,
		paddingVertical: 8,
		...squircle(24),
	},
	infoGroupRowWrap: {
		width: "100%",
	},
	infoGroupRow: {
		minHeight: 48,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	infoGroupLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
	},
	infoGroupValue: {
		flexShrink: 1,
		textAlign: "right",
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "700",
		letterSpacing: -0.15,
	},
	infoGroupDivider: {
		height: StyleSheet.hairlineWidth,
	},
	actionGroupCard: {
		overflow: "hidden",
		paddingHorizontal: 12,
		paddingVertical: 6,
		...squircle(24),
	},
	actionGroupRowWrap: {
		width: "100%",
	},
	actionGroupRow: {
		minHeight: 64,
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 8,
		paddingVertical: 10,
	},
	actionGroupRowPressed: {
		opacity: 0.92,
	},
	actionGroupLeading: {
		flexDirection: "row",
		alignItems: "center",
		gap: 14,
		flex: 1,
		minWidth: 0,
	},
	actionGroupMedia: {
		width: 46,
		height: 46,
		borderRadius: 17,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		backgroundColor: "rgba(148,163,184,0.14)",
		flexShrink: 0,
	},
	actionGroupImage: {
		width: 50,
		height: 42,
		flexShrink: 0,
		overflow: "hidden",
		...squircle(16),
	},
	actionGroupLocationImage: {
		width: 56,
		height: 46,
		...squircle(17),
	},
	actionGroupAvatarImage: {
		width: 46,
		height: 46,
		...squircle(18),
	},
	actionGroupCopy: {
		flex: 1,
		minWidth: 0,
		justifyContent: "center",
	},
	actionGroupLabel: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "600",
	},
	actionGroupSubtitle: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	actionGroupDivider: {
		height: StyleSheet.hairlineWidth,
		marginLeft: 68,
	},
	paymentHeroBlade: {
		position: "relative",
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingVertical: 14,
		shadowColor: "#0F172A",
		shadowOpacity: 0.18,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 12 },
		elevation: 8,
		...squircle(26),
	},
	paymentHeroGradient: {
		...StyleSheet.absoluteFillObject,
		opacity: 0.95,
	},
	paymentHeroGlow: {
		position: "absolute",
		right: -36,
		top: -42,
		width: 112,
		height: 112,
		borderRadius: 999,
		opacity: 0.28,
	},
	paymentHeroContent: {
		position: "relative",
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	paymentHeroAvatar: {
		width: 42,
		height: 42,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 8 },
		elevation: 5,
	},
	paymentHeroCopy: {
		flex: 1,
		minWidth: 0,
	},
	paymentHeroTitle: {
		marginTop: 4,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "600",
		letterSpacing: -0.22,
	},
	paymentHeroSubtitle: {
		marginTop: 3,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	paymentHeroRight: {
		minHeight: 34,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 6,
		paddingHorizontal: 11,
		...squircle(17),
	},
	paymentHeroRightText: {
		color: "#FFFFFF",
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
		letterSpacing: -0.1,
	},
	paymentHeroSkeleton: {
		marginTop: 7,
		width: 94,
		height: 12,
		borderRadius: 999,
		backgroundColor: "rgba(148,163,184,0.24)",
	},
	statusCard: {
		paddingHorizontal: 18,
		paddingVertical: 22,
		alignItems: "center",
		...squircle(30),
	},
	statusIconWrap: {
		width: 64,
		height: 64,
		alignItems: "center",
		justifyContent: "center",
		...squircle(24),
	},
	statusTitle: {
		marginTop: 16,
		fontSize: 22,
		lineHeight: 26,
		fontWeight: "800",
		letterSpacing: -0.52,
		textAlign: "center",
	},
	statusDescription: {
		marginTop: 8,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "500",
		textAlign: "center",
	},
	statusMeta: {
		marginTop: 14,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "700",
		textAlign: "center",
	},
	statusActionRow: {
		width: "100%",
		marginTop: 18,
		gap: 10,
	},
	statusPrimaryAction: {
		width: "100%",
	},
	statusSecondaryAction: {
		alignSelf: "center",
		paddingHorizontal: 14,
		paddingVertical: 8,
		...squircle(18),
	},
	statusSecondaryActionPressed: {
		opacity: 0.88,
		transform: [{ scale: 0.99 }],
	},
	statusSecondaryActionText: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	inlineMessage: {
		marginTop: 2,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "600",
	},
	footerDock: {
		paddingHorizontal: 14,
		paddingTop: 10,
		paddingBottom: 14,
	},
	inlineFooterDock: {
		paddingHorizontal: 2,
		paddingTop: 2,
		paddingBottom: 6,
	},
	primaryButton: {
		width: "100%",
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowOffset: { width: 0, height: 10 },
		shadowRadius: 18,
	},
});

export default styles;
