import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
	bodyContent: {
		flexGrow: 1,
		paddingTop: 14,
		paddingBottom: 12,
	},
	webWideContentInset: {
		paddingLeft: 26,
		paddingRight: 26,
	},
	sectionStack: {
		gap: 14,
	},
	heroCard: {
		minHeight: 238,
		borderRadius: 30,
		borderCurve: "continuous",
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 16,
		overflow: "hidden",
		shadowColor: "#0F172A",
		shadowOpacity: 0.2,
		shadowRadius: 28,
		shadowOffset: { width: 0, height: 18 },
		elevation: 12,
	},
	heroCardTopHighlight: {
		position: "absolute",
		top: 1,
		left: 1,
		right: 1,
		height: 84,
		borderTopLeftRadius: 30,
		borderTopRightRadius: 30,
	},
	heroCardBottomShade: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 92,
	},
	passHeader: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 14,
		paddingBottom: 14,
	},
	passHeaderCopy: {
		flex: 1,
		minWidth: 0,
		paddingTop: 2,
	},
	passHeaderTitle: {
		fontSize: 21,
		lineHeight: 25,
		fontWeight: "900",
		letterSpacing: -0.55,
	},
	passHeaderSubtitle: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "600",
	},
	passTotalPill: {
		alignItems: "flex-end",
		flexShrink: 0,
		paddingHorizontal: 2,
	},
	passRowStack: {
		gap: 10,
	},
	passRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 11,
		minHeight: 52,
		paddingHorizontal: 10,
		paddingVertical: 8,
		borderRadius: 22,
		borderCurve: "continuous",
	},
	passRowMedia: {
		width: 46,
		height: 46,
		borderRadius: 17,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
	},
	passRowImage: {
		width: "100%",
		height: "100%",
	},
	passRowCopy: {
		flex: 1,
		minWidth: 0,
	},
	passRowTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.3,
	},
	passRowSubtitle: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "600",
	},
	priceLabel: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "700",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	priceValue: {
		marginTop: 3,
		fontSize: 24,
		lineHeight: 28,
		fontWeight: "900",
		letterSpacing: -0.7,
	},
	selectorCard: {
		borderRadius: 28,
		borderCurve: "continuous",
		paddingHorizontal: 14,
		paddingVertical: 16,
		overflow: "hidden",
	},
	selectorHeader: {
		paddingHorizontal: 4,
	},
	selectorTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.28,
	},
	selectorDescription: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "500",
	},
	selectorBody: {
		marginTop: 12,
	},
	breakdownCard: {
		borderRadius: 24,
		borderCurve: "continuous",
		paddingHorizontal: 18,
		paddingVertical: 16,
	},
	breakdownTitle: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
		letterSpacing: -0.2,
	},
	breakdownRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 14,
		paddingVertical: 8,
	},
	breakdownRowLabel: {
		flex: 1,
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
	},
	breakdownRowValue: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	breakdownDivider: {
		height: StyleSheet.hairlineWidth,
		marginTop: 4,
		marginBottom: 2,
	},
	breakdownTotalRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 14,
		paddingTop: 10,
	},
	breakdownTotalLabel: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
	},
	breakdownTotalValue: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
		letterSpacing: -0.2,
	},
	statusCard: {
		borderRadius: 30,
		borderCurve: "continuous",
		paddingHorizontal: 18,
		paddingVertical: 22,
		alignItems: "center",
	},
	statusIconWrap: {
		width: 64,
		height: 64,
		borderRadius: 24,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
	},
	statusTitle: {
		marginTop: 16,
		fontSize: 22,
		lineHeight: 26,
		fontWeight: "800",
		letterSpacing: -0.52,
		textAlign: "center",
	},
	statusDescription: {
		marginTop: 8,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "500",
		textAlign: "center",
	},
	statusMeta: {
		marginTop: 14,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "700",
		textAlign: "center",
	},
	inlineMessage: {
		marginTop: 6,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "600",
	},
	footerDock: {
		paddingHorizontal: 14,
		paddingTop: 10,
		paddingBottom: 14,
	},
	primaryButton: {
		width: "100%",
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowOffset: { width: 0, height: 10 },
		shadowRadius: 18,
	},
});

export default styles;
