import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export default StyleSheet.create({
	topRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		marginBottom: 20,
		paddingHorizontal: 16,
	},
	topRowCollapsed: {
		marginBottom: 0,
	},
	topRowWebMobile: {
		paddingHorizontal: 14,
		gap: 10,
		marginBottom: 18,
	},
	topRowWebMobileMd: {
		paddingHorizontal: 18,
		gap: 12,
		marginBottom: 20,
	},
	topRowCentered: {
		width: "100%",
		alignSelf: "center",
	},
	topRowModal: {
		marginBottom: 20,
	},
	topRowPanel: {
		marginBottom: 22,
	},
	topRowSidebar: {
		paddingHorizontal: 16,
		marginBottom: 18,
		gap: 10,
	},
	sidebarHeader: {
		width: "100%",
		alignSelf: "center",
		paddingHorizontal: 16,
		marginBottom: 18,
	},
	sidebarHeaderRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	sidebarHeaderSide: {
		width: 42,
		alignItems: "center",
		justifyContent: "center",
	},
	sidebarHeaderCenter: {
		flex: 1,
		minWidth: 0,
	},
	sidebarHeaderTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
		letterSpacing: -0.3,
	},
	sidebarHeaderSubtitle: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
	},
	searchPill: {
		flex: 1,
		minHeight: 50,
		paddingHorizontal: 15,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		borderCurve: "continuous",
	},
	searchPillCollapsed: {
		minHeight: 44,
		paddingHorizontal: 14,
	},
	searchPillWebMobile: {
		minHeight: 48,
	},
	searchText: {
		fontSize: 16,
		lineHeight: 21,
		fontWeight: "600",
	},
	bodyScrollContent: {
		paddingBottom: 6,
	},
	bodyScrollContentWebMobile: {
		paddingBottom: 12,
	},
	bodyScrollContentModal: {
		paddingBottom: 16,
	},
	bodyScrollContentPanel: {
		paddingBottom: 22,
		paddingHorizontal: 0,
	},
	bodyScrollContentSidebar: {
		flexGrow: 1,
		paddingBottom: 0,
	},
	contentSectionInset: {
		paddingHorizontal: 18,
	},
	bodyScrollViewport: {
		flex: 1,
		minHeight: 0,
	},
	contentSectionInsetWebMobile: {
		paddingHorizontal: 14,
	},
	contentSectionInsetWebMobileMd: {
		paddingHorizontal: 18,
	},
	contentSectionCentered: {
		width: "100%",
		alignSelf: "center",
	},
	screenPanelRow: {
		width: "100%",
		alignSelf: "center",
		flexDirection: "row",
		alignItems: "stretch",
		gap: 16,
		marginBottom: 8,
	},
	screenPanelItem: {
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 0,
	},
	sidebarScreenStack: {
		flex: 1,
		minHeight: "100%",
		justifyContent: "space-between",
	},
	sidebarScreenTopCluster: {
		gap: 0,
	},
	sidebarScreenBottomCluster: {
		marginTop: 28,
	},
	sidebarScreenSpacer: {
		flex: 1,
		minHeight: 0,
	},
	avatarPressable: {
		width: 44,
		height: 44,
		position: "relative",
		alignItems: "center",
		justifyContent: "center",
	},
	avatarPressableCollapsed: {
		width: 40,
		height: 40,
	},
	avatarImageShell: {
		width: 42,
		height: 42,
		borderRadius: 999,
		overflow: "hidden",
	},
	avatarImageShellCollapsed: {
		width: 38,
		height: 38,
		borderRadius: 999,
	},
	avatarImage: {
		width: "100%",
		height: "100%",
		borderRadius: 999,
	},
	avatarImageCollapsed: {
		borderRadius: 999,
	},
	avatarDot: {
		position: "absolute",
		bottom: 2,
		right: 1,
		width: 12,
		height: 12,
		borderRadius: 6,
		backgroundColor: "#10B981",
		borderWidth: 2,
		borderColor: "#FFFFFF",
	},
	avatarDotCollapsed: {
		bottom: 1,
		right: 0,
		width: 10,
		height: 10,
		borderRadius: 5,
	},
	hospitalCard: {
		paddingHorizontal: 14,
		paddingVertical: 14,
		flexDirection: "row",
		alignItems: "center",
		gap: 14,
		marginBottom: 22,
	},
	hospitalCardPressed: {
		opacity: 0.96,
		transform: [{ scale: 0.996 }],
	},
	hospitalCardCentered: {
		width: "100%",
		alignSelf: "center",
	},
	intentStatusCard: {
		paddingHorizontal: 14,
		paddingVertical: 14,
		gap: 12,
		marginBottom: 22,
	},
	intentStatusCardWebMobile: {
		alignSelf: "center",
		width: "100%",
		maxWidth: 560,
	},
	intentStatusHeader: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	intentStatusIconWrap: {
		width: 44,
		height: 44,
		alignItems: "center",
		justifyContent: "center",
	},
	intentStatusCopy: {
		flex: 1,
	},
	intentStatusTitle: {
		marginTop: 4,
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "800",
	},
	intentStatusMeta: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	intentStatusChevron: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	intentSignalRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginTop: 8,
	},
	intentSignalPill: {
		alignSelf: "flex-start",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		flexShrink: 0,
		maxWidth: "100%",
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
	},
	intentSignalText: {
		flexShrink: 0,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		includeFontPadding: false,
	},
	summaryHeroCard: {
		marginBottom: 22,
		paddingHorizontal: 18,
		paddingTop: 18,
		paddingBottom: 16,
		overflow: "hidden",
	},
	summaryHeroGlow: {
		...StyleSheet.absoluteFillObject,
	},
	summaryHeroHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
		marginBottom: 16,
	},
	summaryHeroBadge: {
		paddingHorizontal: 12,
		paddingVertical: 7,
		borderRadius: 999,
	},
	summaryHeroBadgeText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "800",
		letterSpacing: 0.4,
		textTransform: "uppercase",
	},
	summaryHeroCopy: {
		gap: 6,
	},
	summaryHeroEyebrow: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		letterSpacing: 0.8,
		textTransform: "uppercase",
	},
	summaryHeroTitle: {
		fontSize: 26,
		lineHeight: 30,
		fontWeight: "900",
		letterSpacing: -0.7,
	},
	summaryHeroMeta: {
		fontSize: 14,
		lineHeight: 19,
		fontWeight: "500",
		maxWidth: "92%",
	},
	summaryHeroMetricGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
		marginTop: 18,
	},
	summaryHeroMetric: {
		flex: 1,
		minWidth: 132,
		paddingHorizontal: 12,
		paddingVertical: 11,
		overflow: "hidden",
		...squircle(18),
	},
	summaryHeroMetricLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.3,
	},
	summaryHeroMetricValue: {
		marginTop: 6,
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
	},
	summaryHeroFooter: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
		marginTop: 18,
	},
	summaryHeroActionPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 11,
		borderRadius: 999,
	},
	summaryHeroActionText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "800",
	},
	summaryHeroHint: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "600",
		flex: 1,
		textAlign: "right",
	},
	summaryLoadingCopy: {
		flex: 1,
		gap: 8,
		paddingVertical: 1,
	},
	summaryLoadingCopyHero: {
		paddingTop: 2,
	},
	summaryLoadingLine: {
		borderRadius: 999,
		backgroundColor: "rgba(148,163,184,0.18)",
	},
	summaryLoadingLineKicker: {
		width: 82,
		height: 10,
	},
	summaryLoadingLineTitle: {
		width: "78%",
		height: 18,
	},
	summaryLoadingLineMeta: {
		width: "58%",
		height: 12,
	},
	summaryLoadingLineHeroKicker: {
		width: 104,
	},
	summaryLoadingLineHeroTitle: {
		width: "72%",
		height: 24,
	},
	summaryLoadingLineHeroMeta: {
		width: "62%",
		height: 13,
	},
	summaryHeroBadgeSkeleton: {
		width: 34,
		height: 10,
		borderRadius: 999,
		backgroundColor: "rgba(148,163,184,0.22)",
	},
	summaryIconShell: {
		width: 42,
		height: 42,
		padding: 1,
		shadowColor: "#0F172A",
		shadowOpacity: 0.05,
		shadowRadius: 6,
		shadowOffset: { width: 0, height: 3 },
		...squircle(16),
	},
	summaryIconShellCompact: {
		width: 30,
		height: 30,
		borderRadius: 15,
	},
	summaryIconFill: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		...squircle(15),
	},
	summaryIconFillCompact: {
		borderRadius: 14,
	},
	summaryIconHighlight: {
		position: "absolute",
		left: 1,
		right: 1,
		top: 1,
		height: "42%",
		backgroundColor: "rgba(255,255,255,0.2)",
		...squircle(14),
	},
	hospitalIconWrap: {
		width: 42,
		height: 42,
		alignItems: "center",
		justifyContent: "center",
	},
	hospitalCardCopy: {
		flex: 1,
	},
	hospitalEyebrow: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		letterSpacing: 0.8,
		textTransform: "uppercase",
	},
	hospitalTitle: {
		marginTop: 4,
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
	},
	hospitalMeta: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	sectionTrigger: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		alignSelf: "flex-start",
		marginBottom: 24,
	},
	sectionTriggerPressed: {
		opacity: 0.78,
	},
	sectionLabel: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
	},
	intentSectionHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
		marginBottom: 16,
	},
	intentSectionHeaderBiased: {
		justifyContent: "flex-start",
		alignSelf: "flex-start",
		gap: 8,
		marginBottom: 18,
	},
	intentSectionHeaderTrigger: {
		alignSelf: "stretch",
	},
	intentSectionMeta: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	intentSectionMetaIconWrap: {
		width: 24,
		height: 24,
		borderRadius: 12,
		alignItems: "center",
		justifyContent: "center",
	},
	careRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 10,
	},
	careRowBiased: {
		width: "100%",
		alignSelf: "flex-start",
		justifyContent: "flex-start",
		gap: 8,
		paddingRight: 10,
	},
	careAction: {
		flex: 1,
		alignItems: "center",
		justifyContent: "flex-start",
		paddingVertical: 2,
		paddingHorizontal: 1,
	},
	careActionPrimaryBias: {
		flex: 1.08,
	},
	careActionLeadingBias: {
		flex: 0.98,
	},
	careActionTrailingBias: {
		flex: 0.9,
		marginLeft: 6,
	},
	careActionPressed: {
		opacity: 0.88,
	},
	careIconShadowWrap: {
		width: 88,
		height: 88,
		borderRadius: 44,
		marginBottom: 10,
	},
	careIconWrap: {
		width: 88,
		height: 88,
		borderRadius: 44,
		overflow: "hidden",
		alignItems: "center",
		justifyContent: "center",
	},
	careLabel: {
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "800",
		textAlign: "center",
	},
	careSubtext: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		textAlign: "center",
	},
	intentActionStack: {
		gap: 10,
	},
	intentActionStackBiased: {
		width: "100%",
		alignSelf: "flex-start",
		gap: 8,
		paddingRight: 8,
	},
	intentActionRow: {
		flexDirection: "row",
		gap: 10,
	},
	intentActionRowBiased: {
		gap: 6,
	},
	intentActionHalf: {
		flex: 1,
	},
	intentActionHalfLeading: {
		flex: 1.04,
	},
	intentActionHalfTrailing: {
		flex: 0.96,
		marginLeft: 6,
	},
	intentPanelGrid: {
		gap: 12,
	},
	intentPanelGridBiased: {
		width: "100%",
		alignSelf: "flex-start",
		paddingRight: 8,
	},
	intentPanelFullSpan: {
		width: "100%",
	},
	intentPanelFullSpanBiased: {
		alignSelf: "flex-start",
	},
	intentPanelBottomRow: {
		flexDirection: "row",
		alignItems: "stretch",
		gap: 12,
	},
	intentPanelBottomRowBiased: {
		gap: 6,
	},
	intentPanelHalf: {
		flex: 1,
	},
	intentPanelHalfLeading: {
		flex: 1.04,
	},
	intentPanelHalfTrailing: {
		flex: 0.96,
		marginLeft: 8,
	},
	intentCardPressable: {
		flex: 1,
	},
	intentCardPulseStage: {
		position: "relative",
		overflow: "visible",
	},
	intentCardPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.988 }],
	},
	intentCardSurface: {
		paddingHorizontal: 16,
		paddingVertical: 15,
		overflow: "hidden",
		...squircle(22),
	},
	intentCardSurfacePrimaryBias: {
		paddingLeft: 20,
		paddingRight: 11,
	},
	intentCardSurfaceLeadingBias: {
		paddingLeft: 17,
		paddingRight: 11,
	},
	intentCardSurfaceTrailingBias: {
		paddingLeft: 14,
		paddingRight: 13,
	},
	intentCardPulseGlow: {
		position: "absolute",
		width: 324,
		height: 324,
		borderRadius: 162,
		alignSelf: "center",
		top: -148,
		backgroundColor: "rgba(255,255,255,0.28)",
	},
	intentCardPulseFloor: {
		position: "absolute",
		left: 28,
		right: 28,
		bottom: -16,
		height: 28,
		borderRadius: 999,
		backgroundColor: "rgba(74, 8, 12, 0.52)",
	},
	intentCardPulseSheen: {
		position: "absolute",
		left: -24,
		right: -24,
		top: 0,
		bottom: 0,
		overflow: "hidden",
	},
	intentCardPulseSheenBand: {
		position: "absolute",
		top: -32,
		bottom: -32,
		width: 186,
		transform: [{ rotate: "16deg" }],
	},
	intentCardPulseSheenBandFill: {
		flex: 1,
	},
	intentCardSurfacePrimary: {
		minHeight: 102,
	},
	intentCardSurfaceSecondary: {
		minHeight: 86,
	},
	intentCardHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	intentCardIconWrap: {
		width: 42,
		height: 42,
		alignItems: "center",
		justifyContent: "center",
		overflow: "visible",
		backgroundColor: "rgba(255,255,255,0.14)",
		...squircle(14),
	},
	intentCardIconAura: {
		position: "absolute",
		width: 72,
		height: 72,
		borderRadius: 36,
		backgroundColor: "rgba(255,255,255,0.22)",
	},
	intentCardCheckBadge: {
		width: 22,
		height: 22,
		borderRadius: 11,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(255,255,255,0.18)",
	},
	intentCardChevronBadge: {
		width: 22,
		height: 22,
		borderRadius: 11,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(255,255,255,0.12)",
	},
	intentCardLabel: {
		marginTop: 16,
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		color: "#FFFFFF",
	},
	intentCardSubtext: {
		marginTop: 4,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		color: "rgba(255,255,255,0.84)",
	},
	expandedSection: {
		marginTop: 24,
	},
	expandedSectionContained: {
		width: "100%",
		alignSelf: "center",
	},
	expandedSectionHeader: {
		paddingHorizontal: 18,
		marginBottom: 10,
	},
	expandedSectionHeaderContained: {
		paddingHorizontal: 0,
		marginBottom: 14,
	},
	expandedSectionTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
		color: "#F8FAFC",
	},
	expandedSectionSubtext: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "500",
		color: "rgba(248,250,252,0.72)",
	},
	featuredRailViewport: {
		marginTop: 10,
		marginHorizontal: 0,
		overflow: "hidden",
	},
	featuredScrollContent: {
		paddingLeft: 14,
		paddingRight: 14,
		gap: 10,
	},
	featuredCard: {
		width: 212,
		height: 288,
		overflow: "hidden",
		...squircle(30),
	},
	featuredCardPressed: {
		opacity: 0.96,
		transform: [{ scale: 0.992 }],
	},
	featuredCardImage: {
		flex: 1,
		justifyContent: "flex-end",
	},
	featuredCardImageStyle: {
		...squircle(30),
	},
	featuredCardHeader: {
		paddingHorizontal: 10,
		paddingTop: 10,
		alignItems: "flex-start",
	},
	featuredTopPill: {
		borderRadius: 999,
		paddingHorizontal: 9,
		paddingVertical: 5,
		backgroundColor: "rgba(8,15,27,0.42)",
	},
	featuredTopPillText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	featuredCardContent: {
		paddingHorizontal: 12,
		paddingVertical: 12,
	},
	featuredTitle: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "800",
	},
	featuredMeta: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	placeholderCard: {
		backgroundColor: "rgba(255,255,255,0.03)",
	},
	placeholderCardInner: {
		flex: 1,
		justifyContent: "space-between",
		...squircle(28),
	},
	placeholderCardHeader: {
		paddingHorizontal: 12,
		paddingTop: 12,
		alignItems: "flex-start",
	},
	placeholderTopPillSkeleton: {
		width: 74,
		height: 22,
		borderRadius: 999,
		backgroundColor: "rgba(248,250,252,0.16)",
	},
	placeholderCopy: {
		flex: 1,
		justifyContent: "flex-end",
		paddingHorizontal: 12,
		paddingVertical: 12,
	},
	placeholderTitleBlock: {
		gap: 6,
	},
	placeholderTitleSkeleton: {
		height: 18,
		borderRadius: 999,
		backgroundColor: "rgba(248,250,252,0.22)",
		width: "86%",
	},
	placeholderTitleSkeletonShort: {
		width: "64%",
	},
	placeholderMetaSkeleton: {
		height: 12,
		borderRadius: 999,
		backgroundColor: "rgba(248,250,252,0.14)",
		width: "58%",
		marginTop: 10,
	},
	footerSlot: {
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		paddingTop: 6,
		paddingBottom: 2,
		paddingHorizontal: 18,
	},
	termsLink: {
		marginTop: 2,
		alignSelf: "center",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 2,
	},
	termsText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
		textAlign: "center",
	},
});
