import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
	bodyContent: {
		flexGrow: 1,
		paddingTop: Platform.OS === "android" ? 2 : 0,
		paddingBottom: 18,
	},
	webWideContentInset: {
		paddingHorizontal: 20,
	},
	stage: {
		width: "100%",
		maxWidth: 420,
		alignSelf: "center",
		paddingHorizontal: 8,
		paddingTop: 10,
		paddingBottom: 16,
	},
	heroBlock: {
		alignItems: "center",
	},
	progressRow: {
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	progressText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: 0.2,
		textTransform: "uppercase",
	},
	// PULLBACK NOTE: Pass 4 HIG sweep — OLD: paddingVertical 8 (tap target ~31pt) NEW: 14 (≥44pt)
	skipAllButton: {
		paddingHorizontal: 12,
		paddingVertical: 14,
		borderRadius: 999,
		borderCurve: "continuous",
	},
	skipAllText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "700",
		letterSpacing: 0.14,
	},
	avatarOrb: {
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 16,
		overflow: "hidden",
		shadowColor: "#000000",
		shadowOpacity: 0.24,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 12 },
		elevation: 10,
	},
	avatarOrbSheen: {
		position: "absolute",
		top: 8,
		left: 12,
		width: "58%",
		height: "32%",
		borderRadius: 999,
		backgroundColor: "rgba(255,255,255,0.28)",
		transform: [{ rotate: "-14deg" }],
	},
	avatarOrbDepth: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: "46%",
		backgroundColor: "rgba(0,0,0,0.16)",
	},
	promptText: {
		marginTop: 12,
		fontSize: 28,
		lineHeight: 32,
		fontWeight: "700",
		letterSpacing: -0.6,
		textAlign: "center",
		maxWidth: 340,
	},
	priorityPill: {
		marginTop: 12,
		paddingHorizontal: 12,
		paddingVertical: 7,
		borderRadius: 999,
		borderCurve: "continuous",
	},
	priorityText: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "700",
	},
	optionsGrid: {
		marginTop: 24,
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
		gap: 10,
	},
	optionCard: {
		paddingHorizontal: 14,
		paddingVertical: 14,
		borderRadius: 20,
		borderCurve: "continuous",
		borderWidth: 1,
		minHeight: 62,
		justifyContent: "center",
	},
	optionSpanHalf: {
		width: "48%",
	},
	optionSpanFull: {
		width: "100%",
	},
	optionSpanThird: {
		width: "31%",
		paddingHorizontal: 8,
		paddingVertical: 12,
		minHeight: 54,
	},
	optionContent: {
		flexDirection: "row",
		alignItems: "center",
	},
	optionContentCompact: {
		justifyContent: "center",
	},
	optionIconBubble: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	optionIconBubbleCompact: {
		marginRight: 0,
		marginBottom: 4,
		alignSelf: "center",
	},
	optionLabel: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "700",
		flex: 1,
	},
	optionLabelCompact: {
		fontSize: 16,
		lineHeight: 18,
		fontWeight: "700",
		textAlign: "center",
		flex: 0,
	},
	// PULLBACK NOTE: Pass 4 HIG sweep — OLD: paddingVertical 8 (tap target ~29pt) NEW: 14 (≥44pt)
	showMoreButton: {
		marginTop: 14,
		alignSelf: "center",
		paddingVertical: 14,
		paddingHorizontal: 12,
		borderRadius: 999,
		borderCurve: "continuous",
		borderWidth: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	showMoreText: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
		marginLeft: 6,
	},
	textSurface: {
		marginTop: 24,
		borderRadius: 28,
		borderCurve: "continuous",
		borderWidth: 1,
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	textInput: {
		minHeight: 110,
		fontSize: 16,
		lineHeight: 22,
		textAlignVertical: "top",
		padding: 0,
	},
	actionsRow: {
		marginTop: 20,
		flexDirection: "row",
		gap: 10,
	},
	secondaryButton: {
		flex: 1,
		minHeight: 50,
		borderRadius: 18,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 14,
	},
	secondaryButtonText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	primaryButton: {
		flex: 1.16,
		minHeight: 50,
		borderRadius: 18,
		borderCurve: "continuous",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 14,
	},
	primaryButtonText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
		color: "#FFFFFF",
	},
});

export default styles;
