import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../../../../constants/colors";

const STACK_PROFILE = {
	layout: "stack",
	copyAlign: "center",
	mapShape: "square",
	stageMaxWidth: 460,
	heroRailWidth: "100%",
	heroWidth: 214,
	heroHeight: 152,
	headlineSize: 34,
	headlineLineHeight: 38,
	helperSize: 17,
	helperLineHeight: 25,
	mapHeight: 232,
	mapMaxWidth: 460,
	actionMaxWidth: 420,
	railWidth: 208,
	railTravel: 92,
	rowGap: 18,
	storyGap: 22,
	sectionGap: 18,
	heroTopPadding: 10,
	actionTopSpacing: 18,
	actionBottomSpacing: 6,
	primaryHeight: 60,
};

const ANDROID_MOBILE_PROFILE = {
	...STACK_PROFILE,
	actionLayout: "inline-icon",
	stageMaxWidth: 480,
	heroWidth: 206,
	heroHeight: 146,
	headlineSize: 32,
	headlineLineHeight: 36,
	helperSize: 16,
	helperLineHeight: 24,
	mapHeight: 224,
	mapMaxWidth: 440,
	actionMaxWidth: 430,
	rowGap: 18,
	storyGap: 20,
	sectionGap: 16,
	actionTopSpacing: 18,
	actionBottomSpacing: 6,
	primaryHeight: 60,
};

const ANDROID_FOLD_PROFILE = {
	layout: "stack",
	copyAlign: "center",
	mapShape: "square",
	stageMaxWidth: 760,
	heroRailWidth: "100%",
	heroWidth: 246,
	heroHeight: 174,
	headlineSize: 40,
	headlineLineHeight: 44,
	helperSize: 17,
	helperLineHeight: 26,
	mapHeight: 0,
	mapMaxWidth: 540,
	actionMaxWidth: 560,
	railWidth: 224,
	railTravel: 104,
	rowGap: 22,
	storyGap: 26,
	sectionGap: 20,
	heroTopPadding: 6,
	actionTopSpacing: 22,
	actionBottomSpacing: 8,
	primaryHeight: 62,
	actionLayout: "inline-icon",
};

const STORY_PROFILE = {
	layout: "story",
	copyAlign: "left",
	stageMaxWidth: 920,
	heroRailWidth: 280,
	heroWidth: 236,
	heroHeight: 168,
	headlineSize: 42,
	headlineLineHeight: 46,
	helperSize: 18,
	helperLineHeight: 27,
	mapHeight: 278,
	mapMaxWidth: 920,
	actionMaxWidth: 420,
	railWidth: 244,
	railTravel: 112,
	rowGap: 28,
	storyGap: 24,
	sectionGap: 22,
	heroTopPadding: 0,
	actionTopSpacing: 20,
	actionBottomSpacing: 6,
	primaryHeight: 62,
};

const IOS_PAD_PROFILE = {
	layout: "stack",
	copyAlign: "center",
	mapShape: "square",
	actionPlacement: "before-map",
	surfaceBorderless: true,
	postActionSpacing: 18,
	stageMaxWidth: 820,
	heroRailWidth: "100%",
	heroWidth: 276,
	heroHeight: 196,
	headlineSize: 46,
	headlineLineHeight: 50,
	helperSize: 18,
	helperLineHeight: 28,
	mapHeight: 0,
	mapMaxWidth: 640,
	actionMaxWidth: 680,
	actionAlign: "center",
	actionLayout: "paired",
	secondaryActionWidth: 244,
	railWidth: 272,
	railTravel: 122,
	rowGap: 28,
	storyGap: 28,
	sectionGap: 22,
	heroTopPadding: 18,
	actionTopSpacing: 20,
	actionBottomSpacing: 0,
	primaryHeight: 64,
};

const STUDIO_PROFILE = {
	layout: "studio",
	copyAlign: "left",
	stageMaxWidth: 1260,
	heroRailWidth: 320,
	heroWidth: 254,
	heroHeight: 182,
	headlineSize: 48,
	headlineLineHeight: 52,
	helperSize: 18,
	helperLineHeight: 28,
	mapHeight: 316,
	mapMaxWidth: 1260,
	actionMaxWidth: 430,
	railWidth: 264,
	railTravel: 122,
	rowGap: 34,
	storyGap: 28,
	sectionGap: 24,
	heroTopPadding: 0,
	actionTopSpacing: 22,
	actionBottomSpacing: 4,
	primaryHeight: 64,
};

const CINEMA_PROFILE = {
	layout: "cinema",
	copyAlign: "left",
	stageMaxWidth: 1640,
	heroRailWidth: 360,
	heroWidth: 282,
	heroHeight: 198,
	headlineSize: 56,
	headlineLineHeight: 60,
	helperSize: 19,
	helperLineHeight: 30,
	mapHeight: 360,
	mapMaxWidth: 1640,
	actionMaxWidth: 450,
	railWidth: 284,
	railTravel: 132,
	rowGap: 40,
	storyGap: 30,
	sectionGap: 26,
	heroTopPadding: 0,
	actionTopSpacing: 24,
	actionBottomSpacing: 0,
	primaryHeight: 64,
};

const VARIANT_PROFILES = {
	"ios-mobile": {
		...STACK_PROFILE,
		actionLayout: "inline-icon",
	},
	"android-mobile": ANDROID_MOBILE_PROFILE,
	"web-mobile": {
		...STACK_PROFILE,
		actionLayout: "inline-icon",
		stageMaxWidth: 392,
		heroWidth: 208,
		heroHeight: 148,
		headlineSize: 28,
		headlineLineHeight: 32,
		helperSize: 15,
		helperLineHeight: 22,
		mapMaxWidth: 360,
		actionMaxWidth: 392,
		rowGap: 16,
		storyGap: 18,
		sectionGap: 16,
		heroTopPadding: 18,
		actionTopSpacing: 12,
		actionBottomSpacing: 8,
		primaryHeight: 56,
	},
	"web-sm-wide": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		surfaceBorderless: true,
		postActionSpacing: 12,
		stageMaxWidth: 540,
		heroWidth: 228,
		heroHeight: 162,
		headlineSize: 38,
		headlineLineHeight: 42,
		helperSize: 17,
		helperLineHeight: 24,
		mapMaxWidth: 448,
		actionMaxWidth: 500,
		secondaryActionWidth: 204,
		rowGap: 18,
		storyGap: 24,
		sectionGap: 16,
		heroTopPadding: 20,
		actionTopSpacing: 16,
		actionBottomSpacing: 0,
		primaryHeight: 58,
	},
	"web-md": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		surfaceBorderless: true,
		postActionSpacing: 14,
		stageMaxWidth: 720,
		heroWidth: 248,
		heroHeight: 176,
		headlineSize: 42,
		headlineLineHeight: 46,
		helperSize: 17,
		helperLineHeight: 25,
		mapMaxWidth: 560,
		actionMaxWidth: 560,
		secondaryActionWidth: 228,
		rowGap: 20,
		storyGap: 26,
		sectionGap: 18,
		heroTopPadding: 22,
		actionTopSpacing: 18,
		actionBottomSpacing: 0,
		primaryHeight: 60,
	},
	"android-fold": ANDROID_FOLD_PROFILE,
	"ios-pad": IOS_PAD_PROFILE,
	"android-tablet": {
		...STORY_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		mapShape: "square",
		stageMaxWidth: 980,
		mapMaxWidth: 620,
		heroRailWidth: 292,
		heroWidth: 238,
		heroHeight: 170,
		headlineSize: 42,
		headlineLineHeight: 46,
		helperSize: 18,
		helperLineHeight: 28,
		mapHeight: 0,
		actionMaxWidth: 720,
		secondaryActionWidth: 248,
		rowGap: 28,
		storyGap: 28,
		sectionGap: 24,
		actionTopSpacing: 24,
		actionBottomSpacing: 0,
		primaryHeight: 64,
	},
	"android-chromebook": {
		...STUDIO_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		mapShape: "square",
		stageMaxWidth: 1320,
		mapMaxWidth: 720,
		heroRailWidth: 340,
		heroWidth: 272,
		heroHeight: 194,
		headlineSize: 50,
		headlineLineHeight: 54,
		helperSize: 19,
		helperLineHeight: 29,
		mapHeight: 0,
		actionMaxWidth: 780,
		secondaryActionWidth: 266,
		rowGap: 32,
		storyGap: 30,
		sectionGap: 24,
		actionTopSpacing: 26,
		actionBottomSpacing: 0,
		primaryHeight: 64,
	},
	macbook: STUDIO_PROFILE,
	"web-lg": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		sideMapPlacement: true,
		pairedActionDirection: "column",
		actionSurfaceless: true,
		surfaceBorderless: true,
		stageMaxWidth: 1200,
		leftColumnWidth: 420,
		columnGap: 42,
		heroWidth: 292,
		heroHeight: 208,
		headlineSize: 44,
		headlineLineHeight: 48,
		helperSize: 17,
		helperLineHeight: 25,
		mapShape: "square",
		mapHeight: 0,
		mapMaxWidth: 540,
		actionMaxWidth: 392,
		secondaryActionWidth: 392,
		rowGap: 22,
		storyGap: 28,
		sectionGap: 22,
		heroTopPadding: 24,
		actionTopSpacing: 22,
		actionBottomSpacing: 0,
		primaryHeight: 62,
	},
	"web-xl": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		sideMapPlacement: true,
		pairedActionDirection: "column",
		actionSurfaceless: true,
		surfaceBorderless: true,
		stageMaxWidth: 1360,
		leftColumnWidth: 460,
		columnGap: 56,
		heroWidth: 316,
		heroHeight: 224,
		headlineSize: 48,
		headlineLineHeight: 52,
		helperSize: 18,
		helperLineHeight: 27,
		mapShape: "square",
		mapHeight: 0,
		mapMaxWidth: 620,
		actionMaxWidth: 420,
		secondaryActionWidth: 420,
		rowGap: 24,
		storyGap: 32,
		sectionGap: 24,
		heroTopPadding: 28,
		actionTopSpacing: 24,
		actionBottomSpacing: 0,
		primaryHeight: 64,
	},
	"web-2xl-3xl": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		sideMapPlacement: true,
		pairedActionDirection: "column",
		actionSurfaceless: true,
		surfaceBorderless: true,
		stageMaxWidth: 1640,
		leftColumnWidth: 520,
		columnGap: 68,
		heroWidth: 344,
		heroHeight: 242,
		headlineSize: 54,
		headlineLineHeight: 58,
		helperSize: 19,
		helperLineHeight: 29,
		mapShape: "square",
		mapHeight: 0,
		mapMaxWidth: 760,
		actionMaxWidth: 448,
		secondaryActionWidth: 448,
		rowGap: 26,
		storyGap: 34,
		sectionGap: 26,
		heroTopPadding: 32,
		actionTopSpacing: 26,
		actionBottomSpacing: 0,
		primaryHeight: 66,
	},
	"web-ultra-wide": {
		...STACK_PROFILE,
		actionLayout: "paired",
		actionAlign: "center",
		actionPlacement: "before-map",
		sideMapPlacement: true,
		pairedActionDirection: "column",
		actionSurfaceless: true,
		surfaceBorderless: true,
		stageMaxWidth: 1840,
		leftColumnWidth: 560,
		columnGap: 76,
		heroWidth: 366,
		heroHeight: 258,
		headlineSize: 58,
		headlineLineHeight: 62,
		helperSize: 20,
		helperLineHeight: 30,
		mapShape: "square",
		mapHeight: 0,
		mapMaxWidth: 860,
		actionMaxWidth: 468,
		secondaryActionWidth: 468,
		rowGap: 28,
		storyGap: 36,
		sectionGap: 28,
		heroTopPadding: 36,
		actionTopSpacing: 28,
		actionBottomSpacing: 0,
		primaryHeight: 66,
	},
};

export default function createEmergencyChooseLocationTheme({
	variant,
	isDarkMode,
	viewportHeight = 0,
	fontScale = 1,
}) {
	const profile = VARIANT_PROFILES[variant] || VARIANT_PROFILES["ios-mobile"];
	const isSquareMap = profile.mapShape === "square";
	const cappedFontScale = Math.min(Math.max(fontScale || 1, 1), 1.24);
	const compressedSpacingFactor =
		cappedFontScale >= 1.18 ? 0.76 : cappedFontScale >= 1.08 ? 0.88 : 1;
	const squareMapScale =
		isSquareMap && cappedFontScale >= 1.18
			? 0.86
			: isSquareMap && cappedFontScale >= 1.08
				? 0.93
				: 1;
	const reducedMapHeight = viewportHeight > 0 && viewportHeight < 780 ? 18 : 0;
	const mapHeight = Math.max(208, profile.mapHeight - reducedMapHeight);
	const squareMapMaxWidth = Math.round(profile.mapMaxWidth * squareMapScale);

	const colors = isDarkMode
		? {
			headline: "#F8FAFC",
			helper: "#A8B4C6",
			quiet: "#7F8CA1",
			surface: "rgba(255,255,255,0.04)",
			surfaceBorder: "rgba(255,255,255,0.08)",
			skeleton: "rgba(255,255,255,0.07)",
			skeletonHighlight: "rgba(255,255,255,0.12)",
			rail: "rgba(255,255,255,0.08)",
			railIndicator: "#C62828",
			findingHaloOuter: "#9B1C1C",
			findingHaloMiddle: "#B91C1C",
			findingHaloInner: "#DC2626",
		}
		: {
			headline: "#111827",
			helper: "#667287",
			quiet: "#8B97AA",
			surface: "rgba(255,255,255,0.86)",
			surfaceBorder: "rgba(17,24,39,0.08)",
			skeleton: "rgba(15,23,42,0.05)",
			skeletonHighlight: "rgba(15,23,42,0.08)",
			rail: "rgba(17,24,39,0.08)",
			railIndicator: "#B91C1C",
			findingHaloOuter: "#FCA5A5",
			findingHaloMiddle: "#F87171",
			findingHaloInner: "#EF4444",
		};

	const leftAligned = profile.copyAlign === "left";
	const actionPlacement = profile.actionPlacement || "after-map";
	const useSideMapPlacement = profile.sideMapPlacement === true;
	const pairedActionDirection = profile.pairedActionDirection || "row";
	const usePairedActionColumn = pairedActionDirection === "column";
	const actionAlign =
		profile.actionAlign || (leftAligned ? "flex-start" : "center");
	const mapRadius = profile.mapRadius || 28;
	const stageBottomPadding = profile.actionBottomSpacing;

	const styles = StyleSheet.create({
		stageRoot: {
			flex: 1,
			width: "100%",
			maxWidth: profile.stageMaxWidth,
			alignSelf: "center",
			flexDirection: useSideMapPlacement ? "row" : "column",
			alignItems: useSideMapPlacement ? "center" : "stretch",
			justifyContent: useSideMapPlacement ? "center" : "space-between",
			columnGap: useSideMapPlacement
				? Math.round((profile.columnGap || 40) * compressedSpacingFactor)
				: 0,
			paddingBottom: stageBottomPadding,
		},
		storyBlock: {
			width: useSideMapPlacement ? profile.leftColumnWidth || 460 : "100%",
			gap: Math.round(profile.storyGap * compressedSpacingFactor),
			flexShrink: useSideMapPlacement ? 0 : 1,
		},
		heroCopyRow: {
			width: "100%",
			flexDirection: profile.layout === "stack" ? "column" : "row",
			alignItems: profile.layout === "stack" ? "center" : "center",
			columnGap: Math.round(profile.rowGap * compressedSpacingFactor),
			rowGap: Math.round(profile.rowGap * compressedSpacingFactor),
		},
		heroRail: {
			width: profile.layout === "stack" ? "100%" : profile.heroRailWidth,
			alignItems: "center",
			justifyContent: "center",
			paddingTop: profile.heroTopPadding,
		},
		copyRail: {
			flex: profile.layout === "stack" ? 0 : 1,
			width: profile.layout === "stack" ? "100%" : undefined,
			alignItems: leftAligned ? "flex-start" : "center",
			justifyContent: "center",
		},
		heroBlock: {
			alignItems: "center",
			justifyContent: "center",
			minHeight: profile.heroHeight + Math.round(24 * compressedSpacingFactor),
		},
		heroImage: {
			width: profile.heroWidth,
			height: profile.heroHeight,
		},
		findingAmbientWrap: {
			position: "absolute",
			alignItems: "center",
			justifyContent: "center",
		},
		findingHaloOuter: {
			position: "absolute",
			width: profile.heroWidth + 176,
			height: profile.heroWidth + 176,
		},
		findingHaloMiddle: {
			position: "absolute",
			width: profile.heroWidth + 124,
			height: profile.heroWidth + 124,
		},
		findingHaloInner: {
			position: "absolute",
			width: profile.heroWidth + 82,
			height: profile.heroWidth + 82,
		},
		copyBlock: {
			width: "100%",
			alignItems: leftAligned ? "flex-start" : "center",
			gap: 8,
			minHeight: profile.headlineLineHeight + profile.helperLineHeight + 12,
		},
		headline: {
			width: "100%",
			maxWidth: leftAligned ? 760 : 680,
			fontSize: profile.headlineSize,
			lineHeight: profile.headlineLineHeight,
			fontWeight: "900",
			letterSpacing: -1.2,
			color: colors.headline,
			textAlign: leftAligned ? "left" : "center",
		},
		helper: {
			width: "100%",
			maxWidth: leftAligned ? 560 : 520,
			fontSize: profile.helperSize,
			lineHeight: profile.helperLineHeight,
			fontWeight: "500",
			color: colors.helper,
			textAlign: leftAligned ? "left" : "center",
		},
		copySkeleton: {
			width: "100%",
			alignItems: leftAligned ? "flex-start" : "center",
			gap: 12,
		},
		headlineSkeleton: {
			width: leftAligned ? 320 : 248,
			height: Math.max(28, profile.headlineLineHeight - 6),
			borderRadius: 16,
			backgroundColor: colors.skeleton,
		},
		helperSkeleton: {
			width: leftAligned ? 240 : 188,
			height: Math.max(16, profile.helperLineHeight - 8),
			borderRadius: 12,
			backgroundColor: colors.skeletonHighlight,
		},
		mapWrap: {
			width: "100%",
			maxWidth: isSquareMap ? squareMapMaxWidth : profile.mapMaxWidth,
			height: isSquareMap ? undefined : mapHeight,
			aspectRatio: isSquareMap ? 1 : undefined,
			alignSelf: "center",
			borderRadius: mapRadius,
			overflow: "hidden",
		},
		mapSkeleton: {
			width: "100%",
			maxWidth: isSquareMap ? squareMapMaxWidth : profile.mapMaxWidth,
			height: isSquareMap ? undefined : mapHeight,
			aspectRatio: isSquareMap ? 1 : undefined,
			alignSelf: "center",
			borderRadius: mapRadius,
			backgroundColor: colors.skeleton,
			borderWidth: 1,
			borderColor: colors.surfaceBorder,
			overflow: "hidden",
			alignItems: "center",
			justifyContent: "center",
		},
		mapSkeletonPill: {
			position: "absolute",
			top: 14,
			left: 14,
			width: 118,
			height: 38,
			borderRadius: 999,
			backgroundColor: colors.surface,
			borderWidth: 1,
			borderColor: colors.surfaceBorder,
		},
		mapSkeletonPinWrap: {
			position: "absolute",
			top: "55%",
			left: "50%",
			width: 24,
			height: 24,
			marginLeft: -12,
			marginTop: -12,
			borderRadius: 12,
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: colors.surface,
			borderWidth: 1,
			borderColor: colors.surfaceBorder,
		},
		mapSkeletonPin: {
			width: 12,
			height: 12,
			borderRadius: 6,
			backgroundColor: colors.railIndicator,
		},
		mapSkeletonGridA: {
			position: "absolute",
			top: "28%",
			left: 24,
			right: 24,
			height: 1,
			backgroundColor: colors.surfaceBorder,
		},
		mapSkeletonGridB: {
			position: "absolute",
			bottom: "24%",
			left: 28,
			right: 28,
			height: 1,
			backgroundColor: colors.surfaceBorder,
		},
		mapSkeletonGridC: {
			position: "absolute",
			top: 22,
			bottom: 22,
			left: "32%",
			width: 1,
			backgroundColor: colors.surfaceBorder,
		},
		actionWell: {
			width: "100%",
			maxWidth: profile.actionMaxWidth,
			alignSelf: actionAlign,
			marginTop: Math.round(profile.actionTopSpacing * compressedSpacingFactor),
			marginBottom:
				actionPlacement === "before-map"
					? Math.round((profile.postActionSpacing || 0) * compressedSpacingFactor)
					: 0,
			gap: 12,
			flexShrink: 0,
		},
		floatingActionDock: {
			paddingTop: 10,
			paddingHorizontal: 10,
			paddingBottom: 8,
			borderRadius: 26,
			backgroundColor: isDarkMode ? "rgba(11,15,26,0.72)" : "rgba(255,255,255,0.88)",
			shadowColor: isDarkMode ? "#000000" : "#0F172A",
			shadowOpacity: isDarkMode ? 0.24 : 0.12,
			shadowRadius: 18,
			shadowOffset: { width: 0, height: 10 },
			elevation: 0,
			backdropFilter: Platform.OS === "web" ? "blur(14px)" : undefined,
		},
		sideMapWrap: {
			width: "100%",
			maxWidth: isSquareMap ? squareMapMaxWidth : profile.mapMaxWidth,
			alignSelf: "center",
			flexShrink: 0,
		},
		pairedActionSurface: {
			width: "100%",
			padding: 14,
			borderRadius: 28,
			backgroundColor: colors.surface,
			borderWidth: profile.surfaceBorderless ? 0 : 1,
			borderColor: profile.surfaceBorderless
				? "transparent"
				: colors.surfaceBorder,
		},
		pairedActionRow: {
			width: "100%",
			flexDirection: pairedActionDirection,
			alignItems: "center",
			gap: usePairedActionColumn ? 12 : 14,
		},
		pairedSecondaryAction: {
			width: usePairedActionColumn ? "100%" : profile.secondaryActionWidth || 220,
		},
		pairedPrimaryAction: {
			flex: usePairedActionColumn ? 0 : 1,
			width: usePairedActionColumn ? "100%" : undefined,
		},
		inlineActionRow: {
			width: "100%",
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		inlinePrimaryAction: {
			flex: 1,
		},
		inlineLocationButton: {
			width: profile.primaryHeight,
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "rgba(15,23,42,0.05)",
		},
		inlineLocationButtonSkeleton: {
			width: profile.primaryHeight,
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeleton,
		},
		pairedSecondarySkeleton: {
			width: profile.secondaryActionWidth || 220,
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeletonHighlight,
		},
		stackedSecondaryAction: {
			width: "100%",
		},
		stackedSecondarySkeleton: {
			width: "100%",
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeletonHighlight,
		},
		inlineLocationButtonPressed: {
			opacity: 0.82,
			transform: [{ scale: 0.97 }],
		},
		loadingWell: {
			width: "100%",
			gap: 12,
			paddingTop: 4,
		},
		primarySkeleton: {
			width: "100%",
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeleton,
		},
		quietLinkSkeleton: {
			alignSelf: leftAligned ? "flex-start" : "center",
			width: 132,
			height: 16,
			borderRadius: 8,
			backgroundColor: colors.skeletonHighlight,
		},
		findingWell: {
			width: "100%",
			gap: 12,
		},
		findingRail: {
			width: profile.railWidth,
			height: 8,
			borderRadius: 999,
			backgroundColor: colors.rail,
			overflow: "hidden",
			alignSelf: leftAligned ? "flex-start" : "center",
		},
		findingRailIndicator: {
			width: Math.max(88, Math.round(profile.railWidth * 0.42)),
			height: 8,
			borderRadius: 999,
			backgroundColor: colors.railIndicator,
		},
		findingStatusText: {
			fontSize: 13,
			lineHeight: 18,
			fontWeight: "600",
			color: colors.quiet,
			textAlign: leftAligned ? "left" : "center",
		},
		quietLink: {
			alignSelf: leftAligned ? "flex-start" : "center",
			paddingVertical: 12,
			paddingHorizontal: 10,
			marginHorizontal: -10,
		},
		quietLinkText: {
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "600",
			color: colors.quiet,
			textAlign: leftAligned ? "left" : "center",
		},
	});

	return {
		profile: {
			...profile,
			mapShape: profile.mapShape || "landscape",
			mapHeight,
		},
		colors,
		styles,
	};
}
