import { StyleSheet } from "react-native";
import { COLORS } from "../../../../../constants/colors";

const STACK_PROFILE = {
	layout: "stack",
	copyAlign: "center",
	mapShape: "square",
	stageMaxWidth: 460,
	heroRailWidth: "100%",
	heroWidth: 214,
	heroHeight: 152,
	headlineSize: 34,
	headlineLineHeight: 38,
	helperSize: 17,
	helperLineHeight: 25,
	mapHeight: 232,
	mapMaxWidth: 460,
	actionMaxWidth: 420,
	railWidth: 208,
	railTravel: 92,
	rowGap: 18,
	storyGap: 22,
	sectionGap: 18,
	heroTopPadding: 10,
	actionTopSpacing: 18,
	actionBottomSpacing: 6,
	primaryHeight: 60,
};

const STORY_PROFILE = {
	layout: "story",
	copyAlign: "left",
	stageMaxWidth: 920,
	heroRailWidth: 280,
	heroWidth: 236,
	heroHeight: 168,
	headlineSize: 42,
	headlineLineHeight: 46,
	helperSize: 18,
	helperLineHeight: 27,
	mapHeight: 278,
	mapMaxWidth: 920,
	actionMaxWidth: 420,
	railWidth: 244,
	railTravel: 112,
	rowGap: 28,
	storyGap: 24,
	sectionGap: 22,
	heroTopPadding: 0,
	actionTopSpacing: 20,
	actionBottomSpacing: 6,
	primaryHeight: 62,
};

const STUDIO_PROFILE = {
	layout: "studio",
	copyAlign: "left",
	stageMaxWidth: 1260,
	heroRailWidth: 320,
	heroWidth: 254,
	heroHeight: 182,
	headlineSize: 48,
	headlineLineHeight: 52,
	helperSize: 18,
	helperLineHeight: 28,
	mapHeight: 316,
	mapMaxWidth: 1260,
	actionMaxWidth: 430,
	railWidth: 264,
	railTravel: 122,
	rowGap: 34,
	storyGap: 28,
	sectionGap: 24,
	heroTopPadding: 0,
	actionTopSpacing: 22,
	actionBottomSpacing: 4,
	primaryHeight: 64,
};

const CINEMA_PROFILE = {
	layout: "cinema",
	copyAlign: "left",
	stageMaxWidth: 1640,
	heroRailWidth: 360,
	heroWidth: 282,
	heroHeight: 198,
	headlineSize: 56,
	headlineLineHeight: 60,
	helperSize: 19,
	helperLineHeight: 30,
	mapHeight: 360,
	mapMaxWidth: 1640,
	actionMaxWidth: 450,
	railWidth: 284,
	railTravel: 132,
	rowGap: 40,
	storyGap: 30,
	sectionGap: 26,
	heroTopPadding: 0,
	actionTopSpacing: 24,
	actionBottomSpacing: 0,
	primaryHeight: 64,
};

const VARIANT_PROFILES = {
	"ios-mobile": STACK_PROFILE,
	"android-mobile": {
		...STACK_PROFILE,
		heroWidth: 206,
		heroHeight: 146,
		mapHeight: 224,
	},
	"web-mobile": {
		...STACK_PROFILE,
		stageMaxWidth: 500,
		mapMaxWidth: 500,
	},
	"android-fold": {
		...STORY_PROFILE,
		stageMaxWidth: 760,
		mapMaxWidth: 760,
		heroRailWidth: 248,
		heroWidth: 216,
		heroHeight: 154,
		headlineSize: 36,
		headlineLineHeight: 40,
		mapHeight: 246,
		actionMaxWidth: 380,
		rowGap: 22,
	},
	"ios-pad": STORY_PROFILE,
	"android-tablet": {
		...STORY_PROFILE,
		stageMaxWidth: 980,
		mapMaxWidth: 980,
		heroRailWidth: 292,
		mapHeight: 286,
	},
	"web-sm-wide": {
		...STORY_PROFILE,
		stageMaxWidth: 980,
		mapMaxWidth: 980,
		mapHeight: 284,
	},
	"web-md": {
		...STORY_PROFILE,
		stageMaxWidth: 1040,
		mapMaxWidth: 1040,
		mapHeight: 292,
	},
	"android-chromebook": {
		...STUDIO_PROFILE,
		stageMaxWidth: 1320,
		mapMaxWidth: 1320,
	},
	macbook: STUDIO_PROFILE,
	"web-lg": {
		...STUDIO_PROFILE,
		stageMaxWidth: 1360,
		mapMaxWidth: 1360,
	},
	"web-xl": {
		...STUDIO_PROFILE,
		stageMaxWidth: 1480,
		mapMaxWidth: 1480,
		heroRailWidth: 340,
		heroWidth: 268,
		heroHeight: 192,
		headlineSize: 52,
		headlineLineHeight: 56,
		mapHeight: 332,
	},
	"web-2xl-3xl": {
		...CINEMA_PROFILE,
		stageMaxWidth: 1720,
		mapMaxWidth: 1720,
	},
	"web-ultra-wide": {
		...CINEMA_PROFILE,
		stageMaxWidth: 1880,
		mapMaxWidth: 1880,
		heroRailWidth: 396,
		heroWidth: 298,
		heroHeight: 208,
		mapHeight: 388,
	},
};

export default function createEmergencyChooseLocationTheme({
	variant,
	isDarkMode,
	viewportHeight = 0,
	fontScale = 1,
}) {
	const profile = VARIANT_PROFILES[variant] || VARIANT_PROFILES["ios-mobile"];
	const isSquareMap = profile.mapShape === "square";
	const cappedFontScale = Math.min(Math.max(fontScale || 1, 1), 1.24);
	const compressedSpacingFactor =
		cappedFontScale >= 1.18 ? 0.76 : cappedFontScale >= 1.08 ? 0.88 : 1;
	const squareMapScale =
		isSquareMap && cappedFontScale >= 1.18
			? 0.86
			: isSquareMap && cappedFontScale >= 1.08
				? 0.93
				: 1;
	const reducedMapHeight = viewportHeight > 0 && viewportHeight < 780 ? 18 : 0;
	const mapHeight = Math.max(208, profile.mapHeight - reducedMapHeight);
	const squareMapMaxWidth = Math.round(profile.mapMaxWidth * squareMapScale);

	const colors = isDarkMode
		? {
			headline: "#F8FAFC",
			helper: "#A8B4C6",
			quiet: "#7F8CA1",
			surface: "rgba(255,255,255,0.04)",
			surfaceBorder: "rgba(255,255,255,0.08)",
			skeleton: "rgba(255,255,255,0.07)",
			skeletonHighlight: "rgba(255,255,255,0.12)",
			rail: "rgba(255,255,255,0.08)",
			railIndicator: "#C62828",
			findingHaloOuter: "#9B1C1C",
			findingHaloMiddle: "#B91C1C",
			findingHaloInner: "#DC2626",
		}
		: {
			headline: "#111827",
			helper: "#667287",
			quiet: "#8B97AA",
			surface: "rgba(255,255,255,0.86)",
			surfaceBorder: "rgba(17,24,39,0.08)",
			skeleton: "rgba(15,23,42,0.05)",
			skeletonHighlight: "rgba(15,23,42,0.08)",
			rail: "rgba(17,24,39,0.08)",
			railIndicator: "#B91C1C",
			findingHaloOuter: "#FCA5A5",
			findingHaloMiddle: "#F87171",
			findingHaloInner: "#EF4444",
		};

	const leftAligned = profile.copyAlign === "left";
	const stageBottomPadding = profile.actionBottomSpacing;

	const styles = StyleSheet.create({
		stageRoot: {
			flex: 1,
			width: "100%",
			maxWidth: profile.stageMaxWidth,
			alignSelf: "center",
			justifyContent: "space-between",
			paddingBottom: stageBottomPadding,
		},
		storyBlock: {
			width: "100%",
			gap: Math.round(profile.storyGap * compressedSpacingFactor),
			flexShrink: 1,
		},
		heroCopyRow: {
			width: "100%",
			flexDirection: profile.layout === "stack" ? "column" : "row",
			alignItems: profile.layout === "stack" ? "center" : "center",
			columnGap: Math.round(profile.rowGap * compressedSpacingFactor),
			rowGap: Math.round(profile.rowGap * compressedSpacingFactor),
		},
		heroRail: {
			width: profile.layout === "stack" ? "100%" : profile.heroRailWidth,
			alignItems: "center",
			justifyContent: "center",
			paddingTop: profile.heroTopPadding,
		},
		copyRail: {
			flex: profile.layout === "stack" ? 0 : 1,
			width: profile.layout === "stack" ? "100%" : undefined,
			alignItems: leftAligned ? "flex-start" : "center",
			justifyContent: "center",
		},
		heroBlock: {
			alignItems: "center",
			justifyContent: "center",
			minHeight: profile.heroHeight + Math.round(24 * compressedSpacingFactor),
		},
		heroImage: {
			width: profile.heroWidth,
			height: profile.heroHeight,
		},
		findingAmbientWrap: {
			position: "absolute",
			alignItems: "center",
			justifyContent: "center",
		},
		findingHaloOuter: {
			position: "absolute",
			width: profile.heroWidth + 176,
			height: profile.heroWidth + 176,
		},
		findingHaloMiddle: {
			position: "absolute",
			width: profile.heroWidth + 124,
			height: profile.heroWidth + 124,
		},
		findingHaloInner: {
			position: "absolute",
			width: profile.heroWidth + 82,
			height: profile.heroWidth + 82,
		},
		copyBlock: {
			width: "100%",
			alignItems: leftAligned ? "flex-start" : "center",
			gap: 8,
			minHeight: profile.headlineLineHeight + profile.helperLineHeight + 12,
		},
		headline: {
			width: "100%",
			maxWidth: leftAligned ? 760 : 680,
			fontSize: profile.headlineSize,
			lineHeight: profile.headlineLineHeight,
			fontWeight: "900",
			letterSpacing: -1.2,
			color: colors.headline,
			textAlign: leftAligned ? "left" : "center",
		},
		helper: {
			width: "100%",
			maxWidth: leftAligned ? 560 : 520,
			fontSize: profile.helperSize,
			lineHeight: profile.helperLineHeight,
			fontWeight: "500",
			color: colors.helper,
			textAlign: leftAligned ? "left" : "center",
		},
		copySkeleton: {
			width: "100%",
			alignItems: leftAligned ? "flex-start" : "center",
			gap: 12,
		},
		headlineSkeleton: {
			width: leftAligned ? 320 : 248,
			height: Math.max(28, profile.headlineLineHeight - 6),
			borderRadius: 16,
			backgroundColor: colors.skeleton,
		},
		helperSkeleton: {
			width: leftAligned ? 240 : 188,
			height: Math.max(16, profile.helperLineHeight - 8),
			borderRadius: 12,
			backgroundColor: colors.skeletonHighlight,
		},
		mapWrap: {
			width: "100%",
			maxWidth: isSquareMap ? squareMapMaxWidth : profile.mapMaxWidth,
			height: isSquareMap ? undefined : mapHeight,
			aspectRatio: isSquareMap ? 1 : undefined,
			alignSelf: "center",
			borderRadius: 28,
			overflow: "hidden",
		},
		mapSkeleton: {
			width: "100%",
			maxWidth: isSquareMap ? squareMapMaxWidth : profile.mapMaxWidth,
			height: isSquareMap ? undefined : mapHeight,
			aspectRatio: isSquareMap ? 1 : undefined,
			borderRadius: 28,
			backgroundColor: colors.skeleton,
			borderWidth: 1,
			borderColor: colors.surfaceBorder,
			overflow: "hidden",
			alignItems: "center",
			justifyContent: "center",
		},
		mapSkeletonRing: {
			width: 46,
			height: 46,
			borderRadius: 23,
			borderWidth: 2,
			borderColor: colors.quiet,
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: colors.surface,
		},
		mapSkeletonPin: {
			width: 12,
			height: 12,
			borderRadius: 6,
			backgroundColor: colors.railIndicator,
		},
		mapSkeletonGridA: {
			position: "absolute",
			top: "28%",
			left: 24,
			right: 24,
			height: 1,
			backgroundColor: colors.surfaceBorder,
		},
		mapSkeletonGridB: {
			position: "absolute",
			bottom: "24%",
			left: 28,
			right: 28,
			height: 1,
			backgroundColor: colors.surfaceBorder,
		},
		mapSkeletonGridC: {
			position: "absolute",
			top: 22,
			bottom: 22,
			left: "32%",
			width: 1,
			backgroundColor: colors.surfaceBorder,
		},
		actionWell: {
			width: "100%",
			maxWidth: profile.actionMaxWidth,
			alignSelf: leftAligned ? "flex-start" : "center",
			marginTop: Math.round(profile.actionTopSpacing * compressedSpacingFactor),
			gap: 12,
			flexShrink: 0,
		},
		inlineActionRow: {
			width: "100%",
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		inlinePrimaryAction: {
			flex: 1,
		},
		inlineLocationButton: {
			width: profile.primaryHeight,
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "rgba(15,23,42,0.05)",
		},
		inlineLocationButtonSkeleton: {
			width: profile.primaryHeight,
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeleton,
		},
		inlineLocationButtonPressed: {
			opacity: 0.82,
			transform: [{ scale: 0.97 }],
		},
		loadingWell: {
			width: "100%",
			gap: 12,
			paddingTop: 4,
		},
		primarySkeleton: {
			width: "100%",
			height: profile.primaryHeight,
			borderRadius: profile.primaryHeight / 2,
			backgroundColor: colors.skeleton,
		},
		quietLinkSkeleton: {
			alignSelf: leftAligned ? "flex-start" : "center",
			width: 132,
			height: 16,
			borderRadius: 8,
			backgroundColor: colors.skeletonHighlight,
		},
		findingWell: {
			width: "100%",
			gap: 12,
		},
		findingRail: {
			width: profile.railWidth,
			height: 8,
			borderRadius: 999,
			backgroundColor: colors.rail,
			overflow: "hidden",
			alignSelf: leftAligned ? "flex-start" : "center",
		},
		findingRailIndicator: {
			width: Math.max(88, Math.round(profile.railWidth * 0.42)),
			height: 8,
			borderRadius: 999,
			backgroundColor: colors.railIndicator,
		},
		findingStatusText: {
			fontSize: 13,
			lineHeight: 18,
			fontWeight: "600",
			color: colors.quiet,
			textAlign: leftAligned ? "left" : "center",
		},
		quietLink: {
			alignSelf: leftAligned ? "flex-start" : "center",
			paddingVertical: 12,
			paddingHorizontal: 10,
			marginHorizontal: -10,
		},
		quietLinkText: {
			fontSize: 14,
			lineHeight: 20,
			fontWeight: "600",
			color: colors.quiet,
			textAlign: leftAligned ? "left" : "center",
		},
	});

	return {
		profile: {
			...profile,
			mapShape: profile.mapShape || "landscape",
			mapHeight,
		},
		colors,
		styles,
	};
}
