import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

const styles = StyleSheet.create({
	bodyContent: {
		flexGrow: 1,
		paddingTop: 10,
		paddingBottom: 20,
	},
	sectionStack: {
		gap: 14,
	},
	metricsCapsule: {
		flexDirection: "row",
		alignItems: "stretch",
		overflow: "hidden",
		shadowColor: "#020617",
		shadowOpacity: 0.14,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 12 },
		elevation: 8,
		...squircle(28),
	},
	metricCell: {
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 14,
		paddingVertical: 14,
		alignItems: "center",
		justifyContent: "center",
	},
	metricLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.34,
	},
	metricValue: {
		marginTop: 5,
		fontSize: 24,
		lineHeight: 28,
		fontWeight: "800",
		letterSpacing: -0.64,
	},
	metricDivider: {
		width: StyleSheet.hairlineWidth,
		marginVertical: 14,
	},
	routeCard: {
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 16,
		shadowColor: "#020617",
		shadowOpacity: 0.16,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 14 },
		elevation: 10,
		...squircle(30),
	},
	routeCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	routeHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
	},
	servicePill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	servicePillText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "800",
		letterSpacing: -0.14,
	},
	requestPill: {
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	requestPillText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "800",
		letterSpacing: 0.08,
	},
	stopList: {
		marginTop: 16,
		position: "relative",
		gap: 16,
	},
	stopConnector: {
		position: "absolute",
		left: 21,
		top: 34,
		bottom: 30,
		width: 2,
		borderRadius: 999,
	},
	stopRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	stopIconWrap: {
		width: 42,
		height: 42,
		alignItems: "center",
		justifyContent: "center",
		...squircle(16),
	},
	stopCopyWrap: {
		flex: 1,
		minWidth: 0,
		position: "relative",
	},
	stopCopy: {
		paddingRight: 18,
	},
	stopLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.28,
	},
	stopTitle: {
		marginTop: 3,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "800",
		letterSpacing: -0.28,
	},
	stopSubtitle: {
		marginTop: 2,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "600",
	},
	stopFade: {
		position: "absolute",
		top: 0,
		right: 0,
		bottom: 0,
		width: 32,
	},
	statusRow: {
		marginTop: 16,
		flexDirection: "row",
		flexWrap: "wrap",
		alignItems: "center",
		gap: 10,
	},
	statusPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	statusPillText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "800",
		letterSpacing: -0.08,
	},
	utilityRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	utilityButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		...squircle(20),
	},
	utilityButtonPressed: {
		opacity: 0.9,
		transform: [{ scale: 0.988 }],
	},
	utilityLabel: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "800",
		letterSpacing: -0.12,
	},
	detailCard: {
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingVertical: 14,
		...squircle(26),
	},
	detailCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	detailHeader: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "800",
		textTransform: "uppercase",
		letterSpacing: 0.34,
	},
	detailList: {
		marginTop: 10,
	},
	detailRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 14,
		paddingVertical: 9,
	},
	detailDivider: {
		height: StyleSheet.hairlineWidth,
	},
	detailLabel: {
		flexShrink: 0,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	detailValue: {
		flex: 1,
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
		textAlign: "right",
	},
	emptyCard: {
		paddingHorizontal: 18,
		paddingVertical: 18,
		alignItems: "center",
		justifyContent: "center",
		...squircle(28),
	},
	emptyTitle: {
		fontSize: 19,
		lineHeight: 23,
		fontWeight: "800",
		letterSpacing: -0.32,
		textAlign: "center",
	},
	emptyMeta: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "600",
		textAlign: "center",
	},
});

export default styles;
