import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

const styles = StyleSheet.create({
	bodyContent: {
		flexGrow: 1,
		paddingTop: 8,
		paddingBottom: 28,
	},
	topSlot: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		paddingHorizontal: 14,
		paddingTop: 6,
		paddingBottom: 2,
	},
	topSlotSide: {
		width: 38,
		height: 38,
	},
	topSlotSideLeft: {
		alignItems: "flex-start",
		justifyContent: "center",
	},
	topSlotSideRight: {
		alignItems: "flex-end",
		justifyContent: "center",
	},
	topSlotAction: {
		alignItems: "center",
		justifyContent: "center",
	},
	topSlotActionButton: {
		width: 38,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
	},
	triageProgressWrap: {
		width: 38,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
	},
	triageProgressSvg: {
		position: "absolute",
	},
	topSlotSpacer: {
		width: 38,
		height: 38,
	},
	topSlotCopy: {
		flex: 1,
		minWidth: 0,
		alignItems: "center",
	},
	topSlotTitle: {
		fontSize: 22,
		lineHeight: 26,
		fontWeight: "700",
		letterSpacing: -0.44,
	},
	topSlotSubtitle: {
		marginTop: 2,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	infoRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	infoCard: {
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 16,
		paddingVertical: 14,
		...squircle(24),
	},
	infoLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.28,
	},
	infoTitle: {
		marginTop: 4,
		fontSize: 16,
		lineHeight: 19,
		fontWeight: "700",
		letterSpacing: -0.22,
	},
	infoSubtitle: {
		marginTop: 3,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	teamHeroCard: {
		position: "relative",
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingVertical: 14,
		...squircle(26),
	},
	teamHeroProgressFill: {
		position: "absolute",
		left: 0,
		top: 0,
		bottom: 0,
		borderRadius: 26,
		borderCurve: "continuous",
	},
	teamHeroContent: {
		position: "relative",
	},
	teamHeroRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	teamHeroAvatar: {
		width: 42,
		height: 42,
		borderRadius: 999,
		backgroundColor: "#B42318",
		alignItems: "center",
		justifyContent: "center",
	},
	teamHeroCopy: {
		flex: 1,
		minWidth: 0,
	},
	teamHeroRight: {
		alignItems: "flex-end",
		justifyContent: "center",
		paddingLeft: 8,
	},
	teamHeroRightText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
		letterSpacing: -0.1,
	},
	teamHeroLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "500",
		textTransform: "uppercase",
		letterSpacing: 0.28,
	},
	teamHeroTitle: {
		marginTop: 4,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "600",
		letterSpacing: -0.22,
	},
	teamHeroSubtitle: {
		marginTop: 3,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	sectionStack: {
		gap: 12,
	},
	metricsCapsule: {
		flexDirection: "row",
		alignItems: "stretch",
		overflow: "hidden",
		shadowColor: "#020617",
		shadowOpacity: 0.14,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 12 },
		elevation: 8,
		...squircle(28),
	},
	metricCell: {
		flex: 1,
		minWidth: 0,
		paddingHorizontal: 14,
		paddingVertical: 14,
		alignItems: "center",
		justifyContent: "center",
	},
	metricLabel: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "600",
		letterSpacing: -0.08,
	},
	metricValue: {
		marginTop: 4,
		fontSize: 20,
		lineHeight: 24,
		fontWeight: "700",
		letterSpacing: -0.4,
	},
	metricDivider: {
		width: StyleSheet.hairlineWidth,
		marginVertical: 14,
	},
	routeCard: {
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 16,
		shadowColor: "#020617",
		shadowOpacity: 0.16,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 14 },
		elevation: 10,
		...squircle(30),
	},
	routeCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	routeHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
	},
	servicePill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	servicePillText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: -0.14,
	},
	requestPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	requestPillText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "700",
		letterSpacing: 0.08,
	},
	stopList: {
		marginTop: 16,
		position: "relative",
		gap: 16,
	},
	stopConnector: {
		position: "absolute",
		left: 21,
		top: 34,
		bottom: 30,
		width: 2,
		borderRadius: 999,
	},
	stopConnectorProgress: {
		position: "absolute",
		left: 21,
		bottom: 30,
		width: 2,
		borderRadius: 999,
	},
	stopRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	stopIconWrap: {
		width: 42,
		height: 42,
		alignItems: "center",
		justifyContent: "center",
		...squircle(16),
	},
	stopCopyWrap: {
		flex: 1,
		minWidth: 0,
		position: "relative",
	},
	stopCopy: {
		paddingRight: 18,
	},
	stopLabel: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
		letterSpacing: -0.08,
	},
	stopTitle: {
		marginTop: 3,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "700",
		letterSpacing: -0.28,
	},
	stopSubtitle: {
		marginTop: 2,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	stopFade: {
		position: "absolute",
		top: 2,
		right: 0,
		bottom: 2,
		width: 32,
		borderTopLeftRadius: 12,
		borderBottomLeftRadius: 12,
		borderTopRightRadius: 10,
		borderBottomRightRadius: 10,
		borderCurve: "continuous",
	},
	statusRow: {
		marginTop: 16,
		flexDirection: "row",
		flexWrap: "wrap",
		alignItems: "center",
		gap: 10,
	},
	statusPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		...squircle(18),
	},
	statusPillText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "700",
		letterSpacing: -0.08,
	},
	utilityRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	ctaRow: {
		flexDirection: "column",
		gap: 10,
	},
	ctaList: {
		flexDirection: "column",
		gap: 8,
	},
	ctaGroupCard: {
		overflow: "hidden",
		paddingHorizontal: 12,
		paddingVertical: 6,
		...squircle(24),
	},
	ctaButton: {
		minHeight: 48,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		gap: 18,
		paddingHorizontal: 16,
		paddingVertical: 12,
		width: "100%",
		...squircle(20),
	},
	ctaButtonGrouped: {
		backgroundColor: "transparent",
		borderRadius: 0,
		paddingHorizontal: 8,
	},
	ctaDivider: {
		height: 1,
		marginLeft: 58,
		backgroundColor: "rgba(148,163,184,0.18)",
	},
	ctaButtonPressed: {
		opacity: 0.9,
		transform: [{ scale: 0.988 }],
	},
	ctaButtonText: {
		fontSize: 18,
		lineHeight: 24,
		fontWeight: "500",
		marginLeft: 0,
		letterSpacing: -0.1,
	},
	cancelCtaWrap: {
		alignItems: "stretch",
		paddingTop: 2,
	},
	cancelCtaButton: {
		minHeight: 52,
		width: "100%",
		paddingHorizontal: 26,
		paddingVertical: 14,
		alignItems: "center",
		justifyContent: "center",
		...squircle(28),
	},
	cancelCtaText: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "700",
		letterSpacing: -0.24,
	},
	utilityButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		...squircle(20),
	},
	utilityButtonPressed: {
		opacity: 0.9,
		transform: [{ scale: 0.988 }],
	},
	utilityLabel: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: -0.12,
	},
	responderCard: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		paddingHorizontal: 16,
		paddingVertical: 14,
		...squircle(24),
	},
	responderAvatar: {
		width: 46,
		height: 46,
		alignItems: "center",
		justifyContent: "center",
		...squircle(17),
	},
	responderCopy: {
		flex: 1,
		minWidth: 0,
	},
	responderLabel: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.34,
	},
	responderName: {
		marginTop: 3,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "700",
		letterSpacing: -0.24,
	},
	responderMeta: {
		marginTop: 2,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	responderPlate: {
		paddingHorizontal: 10,
		paddingVertical: 8,
		...squircle(16),
	},
	responderPlateText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		letterSpacing: 0.22,
	},
	primaryActionCardShell: {
		...squircle(28),
	},
	primaryActionCard: {
		minHeight: 76,
		paddingHorizontal: 16,
		paddingVertical: 14,
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		...squircle(28),
	},
	primaryActionCardPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.992 }],
	},
	primaryActionIconWrap: {
		width: 46,
		height: 46,
		alignItems: "center",
		justifyContent: "center",
		...squircle(17),
	},
	primaryActionCopy: {
		flex: 1,
		minWidth: 0,
	},
	primaryActionEyebrow: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.34,
	},
	primaryActionTitle: {
		marginTop: 4,
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "700",
		letterSpacing: -0.24,
	},
	primaryActionButton: {
		minWidth: 86,
		paddingHorizontal: 14,
		paddingVertical: 12,
		alignItems: "center",
		justifyContent: "center",
		...squircle(18),
	},
	primaryActionButtonText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		letterSpacing: -0.12,
	},
	detailCard: {
		overflow: "hidden",
		paddingHorizontal: 16,
		paddingVertical: 16,
		...squircle(28),
	},
	detailCardGradient: {
		...StyleSheet.absoluteFillObject,
	},
	detailHeader: {
		fontSize: 15,
		lineHeight: 20,
		fontWeight: "600",
		letterSpacing: -0.16,
	},
	detailList: {
		marginTop: 12,
		gap: 10,
	},
	detailRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 14,
		paddingHorizontal: 12,
		paddingVertical: 12,
		...squircle(18),
	},
	detailLeading: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		flexShrink: 0,
	},
	detailIconWrap: {
		width: 24,
		height: 24,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
	},
	detailDivider: {
		height: StyleSheet.hairlineWidth,
	},
	detailLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "500",
	},
	detailValue: {
		flex: 1,
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "600",
		textAlign: "right",
	},
	emptyCard: {
		paddingHorizontal: 18,
		paddingVertical: 18,
		alignItems: "center",
		justifyContent: "center",
		...squircle(28),
	},
	emptyTitle: {
		fontSize: 19,
		lineHeight: 23,
		fontWeight: "700",
		letterSpacing: -0.32,
		textAlign: "center",
	},
	emptyMeta: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
		textAlign: "center",
	},
});

export default styles;
