import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
	content: {
		paddingTop: 0,
		paddingBottom: 10,
		gap: 18,
	},
	searchBar: {
		marginTop: 0,
		marginBottom: 0,
	},
	modeSwitchRow: {
		flexDirection: "row",
		gap: 10,
	},
	modeChip: {
		flex: 1,
		minHeight: 44,
		borderRadius: 16,
		paddingHorizontal: 14,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
	},
	modeChipLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "800",
	},
	section: {
		gap: 12,
	},
	sectionTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
	},
	chipWrap: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	queryChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		borderRadius: 999,
		maxWidth: "100%",
	},
	queryChipLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
		maxWidth: 220,
	},
	resultGroup: {
		borderRadius: 28,
		overflow: "hidden",
	},
	resultRow: {
		paddingHorizontal: 14,
		paddingVertical: 14,
		minHeight: 74,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	resultLeading: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
		gap: 12,
	},
	sheetIconShell: {
		width: 40,
		height: 40,
		borderRadius: 20,
		padding: 1,
		shadowColor: "#0F172A",
		shadowOpacity: 0.05,
		shadowRadius: 6,
		shadowOffset: { width: 0, height: 3 },
	},
	sheetIconFill: {
		flex: 1,
		borderRadius: 19,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
	},
	sheetIconHighlight: {
		position: "absolute",
		left: 1,
		right: 1,
		top: 1,
		height: "42%",
		borderRadius: 18,
		backgroundColor: "rgba(255,255,255,0.2)",
	},
	resultCopy: {
		flex: 1,
	},
	resultTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 8,
	},
	resultTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		flexShrink: 1,
	},
	resultBadge: {
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 999,
		backgroundColor: `${COLORS.brandPrimary}18`,
	},
	resultBadgeText: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "800",
		color: COLORS.brandPrimary,
		textTransform: "uppercase",
		letterSpacing: 0.4,
	},
	resultSubtitle: {
		marginTop: 3,
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "400",
	},
	resultMeta: {
		marginTop: 4,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
	},
	rowDivider: {
		height: StyleSheet.hairlineWidth,
		marginLeft: 66,
	},
	emptyState: {
		borderRadius: 28,
		paddingHorizontal: 18,
		paddingVertical: 22,
		alignItems: "center",
		gap: 10,
	},
	emptyIconWrap: {
		width: 42,
		height: 42,
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: `${COLORS.brandPrimary}14`,
	},
	emptyTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "800",
		textAlign: "center",
	},
	emptyBody: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "400",
		textAlign: "center",
		maxWidth: 320,
	},
	actionChipRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "center",
		gap: 10,
		marginTop: 2,
	},
	actionChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		borderRadius: 999,
	},
	actionChipLabel: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "700",
	},
	loadingRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingHorizontal: 14,
		paddingVertical: 18,
	},
	loadingText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "400",
	},
});
