import { COLORS } from "../../constants/colors";

const MAP_THEME = {
	light: {
		base: "#F3EFE7",
		land: "#ECE7DC",
		landcover: "#DEE6D2",
		building: "#F5F1E8",
		buildingStroke: "#D7D0C4",
		poi: "#ECEEE6",
		poiLabel: "#7C8377",
		roadLocal: "#FAF8F3",
		roadArterial: "#F1EDE4",
		roadHighway: "#E8E2D7",
		roadStroke: "#D2CABD",
		roadLabel: "#6D6B61",
		label: "#6B695F",
		labelStroke: "#F8F4EC",
		water: "#D8E4E5",
		waterLabel: "#697E8D",
		park: "#DCE5D0",
		medicalFill: "#F5E7E9",
		medicalLabel: "#86100E",
	},
	dark: {
		base: "#0F131A",
		land: "#151B24",
		landcover: "#1A2420",
		building: "#101722",
		buildingStroke: "#2A3444",
		poi: "#1A212D",
		poiLabel: "#6F7E94",
		roadLocal: "#202734",
		roadArterial: "#2A3444",
		roadHighway: "#3A4458",
		roadStroke: "#4B5870",
		roadLabel: "#A5B0C2",
		label: "#98A3B6",
		labelStroke: "#0F131A",
		water: "#1A2535",
		waterLabel: "#8BA1C2",
		park: "#1A2420",
		medicalFill: "#2A1A1F",
		medicalLabel: "#E48A93",
	},
	webLight: {
		base: "#F4F0E8",
		land: "#ECE8DE",
		landcover: "#DDE5D1",
		building: "#F6F2EA",
		buildingStroke: "#D8D1C4",
		poi: "#ECEEE6",
		poiLabel: "#7D8477",
		roadLocal: "#FBF9F4",
		roadArterial: "#F1EDE4",
		roadHighway: "#E8E2D7",
		roadStroke: "#D3CBBD",
		roadLabel: "#6D6B61",
		label: "#6C695F",
		labelStroke: "#F8F4EC",
		water: "#D8E4E5",
		waterLabel: "#6A7F8F",
		park: "#DCE5D0",
		medicalFill: "#F5E7E9",
		medicalLabel: "#86100E",
	},
	webDark: {
		base: COLORS.bgDark,
		land: "#111925",
		landcover: "#16231B",
		building: "#131D2A",
		buildingStroke: "#334154",
		poi: "#192332",
		poiLabel: "#7A8A9F",
		roadLocal: "#263345",
		roadArterial: "#324255",
		roadHighway: "#42546A",
		roadStroke: "#5A6B82",
		roadLabel: "#B0BDD0",
		label: "#A2AEC0",
		labelStroke: COLORS.bgDark,
		water: "#192738",
		waterLabel: "#95A9C8",
		park: "#173021",
		medicalFill: "#2E1B20",
		medicalLabel: "#EF9CA4",
	},
	androidLight: {
		base: "#F3EFE7",
		land: "#EBE6DC",
		landcover: "#DCE4D0",
		building: "#F4F0E7",
		buildingStroke: "#D6CEC0",
		poi: "#EBEDE4",
		poiLabel: "#7A8276",
		roadLocal: "#FAF8F3",
		roadArterial: "#F0ECE3",
		roadHighway: "#E7E1D6",
		roadStroke: "#D1C8BA",
		roadLabel: "#6A685F",
		label: "#68665D",
		labelStroke: "#F8F4EC",
		water: "#D7E3E4",
		waterLabel: "#6B8091",
		park: "#DBE4CF",
		medicalFill: "#F5E7E9",
		medicalLabel: "#86100E",
	},
	androidDark: {
		base: COLORS.bgDark,
		land: "#101823",
		landcover: "#15221A",
		building: "#121B28",
		buildingStroke: "#334153",
		poi: "#192330",
		poiLabel: "#8190A3",
		roadLocal: "#263244",
		roadArterial: "#324153",
		roadHighway: "#415167",
		roadStroke: "#59687E",
		roadLabel: "#AEBBCD",
		label: "#A0ADBF",
		labelStroke: COLORS.bgDark,
		water: "#192638",
		waterLabel: "#95A8C6",
		park: "#173021",
		medicalFill: "#2E1B20",
		medicalLabel: "#EF9CA4",
	},
};

const buildMapStyle = (theme) => [
	{ elementType: "geometry", stylers: [{ color: theme.base }] },
	{ elementType: "labels.text.fill", stylers: [{ color: theme.label }] },
	{
		elementType: "labels.text.stroke",
		stylers: [{ color: theme.labelStroke }, { weight: 1.5 }],
	},
	{ elementType: "labels.icon", stylers: [{ visibility: "off" }] },

	{
		featureType: "administrative",
		elementType: "geometry.stroke",
		stylers: [{ color: theme.roadStroke }],
	},
	{
		featureType: "landscape.natural",
		elementType: "geometry",
		stylers: [{ color: theme.land }],
	},
	{
		featureType: "landscape.natural.landcover",
		elementType: "geometry",
		stylers: [{ color: theme.landcover || theme.land }],
	},
	{
		featureType: "landscape.man_made",
		elementType: "geometry",
		stylers: [{ color: theme.building }],
	},
	{
		featureType: "landscape.man_made",
		elementType: "geometry.fill",
		stylers: [{ color: theme.building }],
	},
	{
		featureType: "landscape.man_made",
		elementType: "geometry.stroke",
		stylers: [{ color: theme.buildingStroke }],
	},
	{
		featureType: "poi",
		elementType: "geometry",
		stylers: [{ color: theme.poi }],
	},
	{
		featureType: "poi",
		elementType: "labels.text",
		stylers: [{ visibility: "on" }],
	},
	{
		featureType: "poi",
		elementType: "labels.text.fill",
		stylers: [{ color: theme.poiLabel }],
	},
	{
		featureType: "poi",
		elementType: "labels.text.stroke",
		stylers: [{ color: theme.labelStroke }, { weight: 1 }],
	},
	{
		featureType: "poi",
		elementType: "labels.icon",
		stylers: [{ visibility: "off" }],
	},
	{
		featureType: "poi.business",
		elementType: "labels",
		stylers: [{ visibility: "off" }],
	},
	{
		featureType: "poi.attraction",
		elementType: "labels",
		stylers: [{ visibility: "off" }],
	},
	{
		featureType: "poi.government",
		elementType: "labels",
		stylers: [{ visibility: "off" }],
	},
	{
		featureType: "poi.place_of_worship",
		elementType: "labels",
		stylers: [{ visibility: "off" }],
	},
	{
		featureType: "poi.park",
		elementType: "geometry",
		stylers: [{ color: theme.park }],
	},
	{
		featureType: "poi.medical",
		elementType: "geometry",
		stylers: [{ color: theme.medicalFill }],
	},
	{
		featureType: "poi.medical",
		elementType: "labels.text.fill",
		stylers: [{ color: theme.medicalLabel }],
	},
	{
		featureType: "road",
		elementType: "labels.text.fill",
		stylers: [{ color: theme.roadLabel }],
	},
	{
		featureType: "road.local",
		elementType: "geometry.fill",
		stylers: [{ color: theme.roadLocal }],
	},
	{
		featureType: "road.local",
		elementType: "geometry.stroke",
		stylers: [{ color: theme.roadStroke }],
	},
	{
		featureType: "road.arterial",
		elementType: "geometry.fill",
		stylers: [{ color: theme.roadArterial }],
	},
	{
		featureType: "road.arterial",
		elementType: "geometry.stroke",
		stylers: [{ color: theme.roadStroke }],
	},
	{
		featureType: "road.highway",
		elementType: "geometry.fill",
		stylers: [{ color: theme.roadHighway }],
	},
	{
		featureType: "road.highway",
		elementType: "geometry.stroke",
		stylers: [{ color: theme.roadStroke }],
	},
	{
		featureType: "road.highway",
		elementType: "labels.text.fill",
		stylers: [{ color: theme.roadLabel }],
	},

	{
		featureType: "transit",
		elementType: "geometry",
		stylers: [{ color: theme.poi }],
	},
	{
		featureType: "transit.line",
		elementType: "geometry",
		stylers: [{ color: theme.roadStroke }],
	},
	{
		featureType: "transit.station",
		elementType: "labels",
		stylers: [{ visibility: "off" }],
	},

	{
		featureType: "water",
		elementType: "geometry",
		stylers: [{ color: theme.water }],
	},
	{
		featureType: "water",
		elementType: "labels.text.fill",
		stylers: [{ color: theme.waterLabel }],
	},
];

export const lightMapStyle = buildMapStyle(MAP_THEME.light);
export const darkMapStyle = buildMapStyle(MAP_THEME.dark);
export const lightWebMapStyle = buildMapStyle(MAP_THEME.webLight);
export const darkWebMapStyle = buildMapStyle(MAP_THEME.webDark);
export const lightAndroidMapStyle = buildMapStyle(MAP_THEME.androidLight);
export const darkAndroidMapStyle = buildMapStyle(MAP_THEME.androidDark);
