// components/register/countries.js
export default [
  { name: "Afghanistan", code: "AF", dial_code: "+93", min: 9, max: 9, flagEmoji: "🇦🇫" },
  { name: "Albania", code: "AL", dial_code: "+355", min: 8, max: 9, flagEmoji: "🇦🇱" },
  { name: "Algeria", code: "DZ", dial_code: "+213", min: 8, max: 9, flagEmoji: "🇩🇿" },
  { name: "American Samoa", code: "AS", dial_code: "+1‑684", min: 7, max: 7, flagEmoji: "🇦🇸" },
  { name: "Andorra", code: "AD", dial_code: "+376", min: 6, max: 6, flagEmoji: "🇦🇩" },
  { name: "Angola", code: "AO", dial_code: "+244", min: 9, max: 9, flagEmoji: "🇦🇴" },
  { name: "Anguilla", code: "AI", dial_code: "+1‑264", min: 7, max: 7, flagEmoji: "🇦🇮" },
  { name: "Antigua and Barbuda", code: "AG", dial_code: "+1‑268", min: 7, max: 7, flagEmoji: "🇦🇬" },
  { name: "Argentina", code: "AR", dial_code: "+54", min: 10, max: 10, flagEmoji: "🇦🇷" },
  { name: "Armenia", code: "AM", dial_code: "+374", min: 8, max: 8, flagEmoji: "🇦🇲" },
  { name: "Aruba", code: "AW", dial_code: "+297", min: 7, max: 7, flagEmoji: "🇦🇼" },
  { name: "Australia", code: "AU", dial_code: "+61", min: 9, max: 9, flagEmoji: "🇦🇺" },
  { name: "Austria", code: "AT", dial_code: "+43", min: 9, max: 13, flagEmoji: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994", min: 9, max: 9, flagEmoji: "🇦🇿" },
  { name: "Bahamas", code: "BS", dial_code: "+1‑242", min: 7, max: 7, flagEmoji: "🇧🇸" },
  { name: "Bahrain", code: "BH", dial_code: "+973", min: 8, max: 8, flagEmoji: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", min: 10, max: 10, flagEmoji: "🇧🇩" },
  { name: "Barbados", code: "BB", dial_code: "+1‑246", min: 7, max: 7, flagEmoji: "🇧🇧" },
  { name: "Belarus", code: "BY", dial_code: "+375", min: 9, max: 9, flagEmoji: "🇧🇾" },
  { name: "Belgium", code: "BE", dial_code: "+32", min: 8, max: 9, flagEmoji: "🇧🇪" },
  { name: "Belize", code: "BZ", dial_code: "+501", min: 7, max: 7, flagEmoji: "🇧🇿" },
  { name: "Benin", code: "BJ", dial_code: "+229", min: 8, max: 8, flagEmoji: "🇧🇯" },
  { name: "Bermuda", code: "BM", dial_code: "+1‑441", min: 7, max: 7, flagEmoji: "🇧🇲" },
  { name: "Bhutan", code: "BT", dial_code: "+975", min: 8, max: 8, flagEmoji: "🇧🇹" },
  { name: "Bolivia", code: "BO", dial_code: "+591", min: 8, max: 8, flagEmoji: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387", min: 8, max: 8, flagEmoji: "🇧🇦" },
  { name: "Botswana", code: "BW", dial_code: "+267", min: 8, max: 8, flagEmoji: "🇧🇼" },
  { name: "Brazil", code: "BR", dial_code: "+55", min: 10, max: 11, flagEmoji: "🇧🇷" },
  { name: "Brunei Darussalam", code: "BN", dial_code: "+673", min: 7, max: 7, flagEmoji: "🇧🇳" },
  { name: "Bulgaria", code: "BG", dial_code: "+359", min: 8, max: 9, flagEmoji: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", min: 8, max: 8, flagEmoji: "🇧🇫" },
  { name: "Burundi", code: "BI", dial_code: "+257", min: 8, max: 8, flagEmoji: "🇧🇮" },
  // … *continue for all countries/territories alphabetically*
  // Because this list is long, you can generate the remaining entries via an authoritative JSON
  // source such as the "country, dial code, emoji" gist on GitHub. :contentReference[oaicite:1]{index=1}
  { name: "United States", code: "US", dial_code: "+1", min: 10, max: 10, flagEmoji: "🇺🇸" },
  { name: "United Kingdom", code: "GB", dial_code: "+44", min: 10, max: 11, flagEmoji: "🇬🇧" },
  { name: "Canada", code: "CA", dial_code: "+1", min: 10, max: 10, flagEmoji: "🇨🇦" },
  { name: "Nigeria", code: "NG", dial_code: "+234", min: 10, max: 10, flagEmoji: "🇳🇬" },
  // … finish with all remaining entries until Zimbabwe
];
