import { StyleSheet } from "react-native";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export const styles = StyleSheet.create({
	root: {
		...StyleSheet.absoluteFillObject,
		zIndex: 160,
	},
	rootInteractive: {
		pointerEvents: "auto",
	},
	rootPassive: {
		pointerEvents: "none",
	},
	backdrop: {
		...StyleSheet.absoluteFillObject,
	},
	backdropImage: {
		...StyleSheet.absoluteFillObject,
		opacity: 0.28,
	},
	headerGhost: {
		position: "absolute",
		top: 58,
		left: 16,
		right: 16,
		height: 64,
		paddingHorizontal: 14,
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		...squircle(28),
	},
	headerButtonGhost: {
		width: 42,
		height: 42,
		borderRadius: 999,
	},
	headerCopy: {
		flex: 1,
		gap: 8,
	},
	headerLinePrimary: {
		height: 14,
		width: "54%",
		borderRadius: 999,
	},
	headerLineSecondary: {
		height: 10,
		width: "38%",
		borderRadius: 999,
	},
	mapLanePrimary: {
		position: "absolute",
		top: "32%",
		left: "12%",
		width: "62%",
		height: 8,
		borderRadius: 999,
		transform: [{ rotate: "-18deg" }],
	},
	mapLaneSecondary: {
		position: "absolute",
		top: "47%",
		right: "8%",
		width: "48%",
		height: 6,
		borderRadius: 999,
		transform: [{ rotate: "14deg" }],
	},
	mapLaneTertiary: {
		position: "absolute",
		bottom: "34%",
		left: "18%",
		width: "38%",
		height: 6,
		borderRadius: 999,
		transform: [{ rotate: "-10deg" }],
	},
	routeGhostPrimary: {
		position: "absolute",
		top: "35%",
		left: "33%",
		width: 92,
		height: 9,
		borderRadius: 999,
		transform: [{ rotate: "-46deg" }],
	},
	routeGhostCore: {
		position: "absolute",
		top: "35.3%",
		left: "33.6%",
		width: 90,
		height: 3,
		borderRadius: 999,
		transform: [{ rotate: "-46deg" }],
	},
	routeGhostSecondary: {
		position: "absolute",
		top: "39.4%",
		left: "38%",
		width: 36,
		height: 3,
		borderRadius: 999,
		transform: [{ rotate: "-46deg" }],
	},
	userPuckOuter: {
		position: "absolute",
		top: "43.2%",
		left: "44.6%",
		width: 28,
		height: 28,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
	},
	userPuckInner: {
		width: 14,
		height: 14,
		borderRadius: 999,
	},
	hospitalPinGhost: {
		position: "absolute",
		width: 20,
		height: 20,
		borderRadius: 999,
		alignItems: "center",
		justifyContent: "center",
	},
	hospitalPinDot: {
		width: 8,
		height: 8,
		borderRadius: 999,
	},
	mapPinHospital: {
		top: "28%",
		right: "24%",
	},
	mapPinHospitalAlt: {
		top: "40%",
		right: "14%",
	},
	sheetGhost: {
		position: "absolute",
		left: 8,
		right: 8,
		bottom: 8,
		paddingHorizontal: 12,
		paddingTop: 10,
		paddingBottom: 12,
		overflow: "hidden",
		...squircle(44),
	},
	handle: {
		alignSelf: "center",
		width: 48,
		height: 5,
		borderRadius: 999,
		marginBottom: 14,
	},
	loadingCopyBlock: {
		gap: 6,
		marginBottom: 14,
	},
	loadingEyebrow: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "600",
		letterSpacing: -0.1,
	},
	loadingTitle: {
		fontSize: 26,
		lineHeight: 30,
		fontWeight: "900",
		letterSpacing: -0.8,
	},
	loadingMessage: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "400",
		maxWidth: "86%",
	},
	statusRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginBottom: 16,
	},
	statusChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 10,
		paddingVertical: 7,
		borderRadius: 999,
		borderWidth: 0,
	},
	statusDot: {
		width: 7,
		height: 7,
		borderRadius: 999,
	},
	statusChipText: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "600",
	},
	searchRow: {
		height: 52,
		borderRadius: 30,
		marginBottom: 16,
	},
	hospitalCard: {
		height: 72,
		marginBottom: 18,
		...squircle(30),
	},
	sectionLabel: {
		height: 14,
		width: 108,
		borderRadius: 999,
		marginBottom: 12,
	},
	providerStack: {
		gap: 10,
		marginBottom: 16,
	},
	providerRow: {
		height: 58,
		paddingHorizontal: 12,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		...squircle(22),
	},
	providerIcon: {
		width: 26,
		height: 26,
		borderRadius: 13,
	},
	providerCopy: {
		flex: 1,
		gap: 6,
	},
	providerLinePrimary: {
		height: 10,
		width: "52%",
		borderRadius: 999,
	},
	providerLineSecondary: {
		height: 8,
		width: "36%",
		borderRadius: 999,
	},
	providerMeta: {
		width: 38,
		height: 10,
		borderRadius: 999,
	},
	careRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		gap: 10,
	},
	careItem: {
		flex: 1,
		alignItems: "center",
	},
	careOrb: {
		width: 88,
		height: 88,
		borderRadius: 44,
		marginBottom: 10,
	},
	careLinePrimary: {
		width: 66,
		height: 12,
		borderRadius: 999,
		marginBottom: 6,
	},
	careLineSecondary: {
		width: 56,
		height: 10,
		borderRadius: 999,
	},
});
