import { StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export const styles = StyleSheet.create({
	content: {
		flex: 1,
		paddingTop: 0,
		paddingBottom: 0,
		paddingHorizontal: 0,
	},
	scrollContent: {
		paddingHorizontal: 0,
		paddingBottom: 24,
		gap: 12,
	},
	hero: {
		height: 270,
		marginTop: 0,
		marginHorizontal: -14,
		overflow: "hidden",
		justifyContent: "space-between",
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderCurve: "continuous",
	},
	heroImage: {
		borderTopLeftRadius: 34,
		borderTopRightRadius: 34,
		borderCurve: "continuous",
	},
	heroBlend: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 142,
		zIndex: 1,
	},
	heroBadgeRow: {
		paddingTop: 34,
		paddingHorizontal: 14,
		paddingRight: 62,
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
		zIndex: 2,
	},
	heroBadge: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingHorizontal: 9,
		paddingVertical: 6,
		...squircle(999),
	},
	heroBadgeText: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	heroCloseButton: {
		position: "absolute",
		top: 10,
		right: 14,
		zIndex: 4,
	},
	heroCloseButtonSurface: {
		width: 36,
		height: 36,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(8,15,27,0.38)",
		...squircle(18),
	},
	heroCloseButtonSurfacePressed: {
		opacity: 0.88,
		transform: [{ scale: 0.97 }],
	},
	heroFooter: {
		height: 44,
	},
	detailPanel: {
		marginTop: -76,
		marginHorizontal: -14,
		paddingHorizontal: 14,
		paddingTop: 46,
		paddingBottom: 20,
		gap: 12,
		overflow: "visible",
		shadowColor: "#0F172A",
		shadowOpacity: 0.08,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: -6 },
		...squircle(34),
	},
	detailPanelBackgroundClip: {
		...StyleSheet.absoluteFillObject,
		overflow: "hidden",
		...squircle(34),
	},
	detailPanelLowerBlend: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 132,
		borderBottomLeftRadius: 34,
		borderBottomRightRadius: 34,
	},
	detailPanelBottomFade: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: -34,
		height: 54,
	},
	detailPanelContent: {
		gap: 12,
	},
	placeHeader: {
		alignItems: "center",
		paddingHorizontal: 16,
		marginTop: -64,
		gap: 4,
	},
	placeMark: {
		width: 64,
		height: 64,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 6,
		shadowColor: "#0F172A",
		shadowOpacity: 0.22,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.24)",
		...squircle(19),
	},
	placeTitle: {
		fontSize: 23,
		lineHeight: 28,
		fontWeight: "700",
		textAlign: "center",
		letterSpacing: -0.2,
	},
	placeSubtitle: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "500",
		textAlign: "center",
		paddingHorizontal: 10,
	},
	placeActionRow: {
		flexDirection: "row",
		gap: 7,
		paddingHorizontal: 0,
		marginTop: 0,
	},
	placeActionPressable: {
		flex: 1,
		minWidth: 0,
	},
	placeActionButton: {
		minHeight: 48,
		paddingHorizontal: 7,
		paddingVertical: 4,
		alignItems: "center",
		justifyContent: "center",
		gap: 2,
		...squircle(16),
	},
	placeActionButtonPrimary: {
		backgroundColor: COLORS.brandPrimary,
		shadowColor: COLORS.brandPrimary,
		shadowOpacity: 0.22,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 8 },
	},
	placeActionButtonPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.985 }],
	},
	placeActionButtonDisabled: {
		opacity: 0.48,
	},
	placeActionLabel: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		textAlign: "center",
	},
	placeStatsCard: {
		marginTop: 6,
		paddingHorizontal: 10,
		paddingVertical: 0,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 22,
	},
	placeStatItem: {
		alignItems: "center",
		gap: 4,
		minWidth: 58,
	},
	placeStatLabel: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "600",
	},
	placeStatValueRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 4,
	},
	placeStatValue: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
	},
	serviceRail: {
		gap: 9,
		marginTop: 2,
	},
	serviceRailTitle: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
		paddingHorizontal: 2,
	},
	serviceRailScroller: {
		marginHorizontal: -2,
	},
	serviceRailContent: {
		paddingHorizontal: 2,
		gap: 10,
	},
	serviceCard: {
		width: 172,
		minHeight: 228,
		overflow: "hidden",
		shadowColor: "#0F172A",
		shadowOpacity: 0.06,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 5 },
		...squircle(30),
	},
	serviceCardMuted: {
		opacity: 0.58,
	},
	serviceCardImage: {
		flex: 1,
		justifyContent: "space-between",
		...squircle(30),
	},
	serviceCardMedia: {
		...StyleSheet.absoluteFillObject,
		width: undefined,
		height: undefined,
	},
	serviceCardOverlay: {
		...StyleSheet.absoluteFillObject,
	},
	serviceCardHeader: {
		paddingHorizontal: 10,
		paddingTop: 10,
		alignItems: "flex-start",
		zIndex: 2,
	},
	serviceTopPill: {
		borderRadius: 999,
		paddingHorizontal: 9,
		paddingVertical: 5,
		backgroundColor: "rgba(8,15,27,0.42)",
	},
	serviceTopPillText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	serviceTopPillSkeleton: {
		width: 72,
		height: 24,
		borderRadius: 999,
		backgroundColor: "rgba(248,250,252,0.16)",
	},
	serviceCardContent: {
		paddingHorizontal: 12,
		paddingVertical: 12,
		zIndex: 2,
	},
	serviceTitle: {
		fontSize: 17,
		lineHeight: 21,
		fontWeight: "800",
	},
	serviceCardMeta: {
		marginTop: 3,
		fontSize: 12,
		lineHeight: 16,
		fontWeight: "400",
	},
	serviceSkeletonCardInner: {
		flex: 1,
		justifyContent: "space-between",
	},
	serviceSkeletonLineWide: {
		height: 18,
		width: "86%",
		backgroundColor: "rgba(248,250,252,0.22)",
		...squircle(999),
	},
	serviceSkeletonLine: {
		marginTop: 10,
		height: 12,
		width: "58%",
		backgroundColor: "rgba(248,250,252,0.14)",
		...squircle(999),
	},
	serviceInlineSkeleton: {
		marginTop: 3,
		height: 12,
		backgroundColor: "rgba(248,250,252,0.16)",
		...squircle(999),
	},
	serviceInlineSkeletonMeta: {
		width: "52%",
	},
	galleryScroller: {
		marginHorizontal: -2,
	},
	galleryContent: {
		paddingHorizontal: 2,
		gap: 10,
	},
	galleryTile: {
		width: 176,
		height: 128,
		overflow: "hidden",
		backgroundColor: "rgba(148,163,184,0.18)",
		...squircle(24),
	},
	galleryTileImage: {
		...squircle(24),
	},
	actionDock: {
		paddingTop: 10,
		paddingHorizontal: 14,
		paddingBottom: 4,
		gap: 8,
	},
	compactActionRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	callActionPressable: {
		width: 56,
	},
	callActionButton: {
		width: 56,
		height: 56,
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#0F172A",
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 5 },
		...squircle(28),
	},
	callActionIcon: {
		textShadowColor: "rgba(255,255,255,0.18)",
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 1,
	},
	inlinePrimaryPressable: {
		flex: 1,
	},
	inlinePrimaryAction: {
		minHeight: 56,
		paddingHorizontal: 16,
		backgroundColor: COLORS.brandPrimary,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		...squircle(20),
	},
	inlinePrimaryActionPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.99 }],
	},
	inlinePrimaryText: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
		color: "#FFFFFF",
	},
});
