import { StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

const squircle = (radius) => ({
	borderRadius: radius,
	borderCurve: "continuous",
});

export const styles = StyleSheet.create({
	content: {
		paddingTop: 0,
		paddingBottom: 8,
		gap: 10,
	},
	specialtyRailContent: {
		paddingHorizontal: 2,
		paddingRight: 8,
		paddingBottom: 14,
		gap: 10,
	},
	specialtyPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingLeft: 10,
		paddingRight: 10,
		paddingVertical: 8,
		...squircle(18),
	},
	specialtyPillLabel: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "700",
		maxWidth: 132,
	},
	specialtyPillCount: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "700",
	},
	row: {
		paddingHorizontal: 16,
		paddingVertical: 15,
		minHeight: 76,
		borderWidth: 0,
		marginBottom: 14,
		...squircle(24),
	},
	rowTop: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	rowHeading: {
		flexDirection: "row",
		alignItems: "flex-start",
		flex: 1,
		gap: 12,
	},
	sheetIconShell: {
		width: 40,
		height: 40,
		padding: 1,
		shadowColor: "#0F172A",
		shadowOpacity: 0.05,
		shadowRadius: 6,
		shadowOffset: { width: 0, height: 3 },
		...squircle(16),
	},
	sheetIconFill: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		...squircle(15),
	},
	sheetIconHighlight: {
		position: "absolute",
		left: 1,
		right: 1,
		top: 1,
		height: "42%",
		backgroundColor: "rgba(255,255,255,0.2)",
		...squircle(14),
	},
	titleBlock: {
		flex: 1,
	},
	rowTitleLine: {
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 8,
	},
	rowTitle: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: "800",
		flexShrink: 1,
	},
	recommendedBadge: {
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 999,
	},
	recommendedBadgeText: {
		fontSize: 10,
		lineHeight: 12,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.4,
	},
	rowSubtitle: {
		marginTop: 4,
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "400",
	},
	rowActions: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	etaPill: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
		backgroundColor: "rgba(134,16,14,0.10)",
	},
	etaText: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "700",
		color: COLORS.brandPrimary,
	},
	selectionRing: {
		width: 18,
		height: 18,
		borderRadius: 999,
		borderWidth: 1.5,
	},
	metaRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginTop: 14,
	},
	metaChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		borderRadius: 999,
		paddingHorizontal: 10,
		paddingVertical: 7,
	},
	rowMeta: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "400",
	},
	emptyCard: {
		paddingHorizontal: 18,
		paddingVertical: 22,
		alignItems: "center",
		...squircle(28),
	},
	emptyIconWrap: {
		marginBottom: 14,
	},
	emptyTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: "700",
		textAlign: "center",
	},
	changeLocationButton: {
		marginTop: 16,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 14,
		paddingVertical: 12,
		borderRadius: 999,
	},
	changeLocationText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: "600",
	},
});
