import { StyleSheet } from "react-native";
import { COLORS } from "../../../../constants/colors";

export const styles = StyleSheet.create({
	content: {
		flex: 1,
		paddingTop: 0,
		paddingBottom: 0,
		paddingHorizontal: 0,
	},
	scrollContent: {
		paddingHorizontal: 0,
		paddingBottom: 10,
		gap: 10,
	},
	hero: {
		height: 216,
		borderRadius: 30,
		overflow: "hidden",
		justifyContent: "space-between",
		shadowColor: "#0F172A",
		shadowOpacity: 0.16,
		shadowRadius: 22,
		shadowOffset: { width: 0, height: 12 },
	},
	heroImage: {
		borderRadius: 30,
	},
	heroBadgeRow: {
		paddingTop: 12,
		paddingHorizontal: 12,
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
		paddingRight: 62,
	},
	heroCloseButton: {
		position: "absolute",
		top: 12,
		right: 12,
		zIndex: 3,
	},
	heroCloseButtonSurface: {
		width: 38,
		height: 38,
		borderRadius: 19,
		backgroundColor: "rgba(8,15,27,0.42)",
		alignItems: "center",
		justifyContent: "center",
	},
	heroCloseButtonSurfacePressed: {
		opacity: 0.88,
		transform: [{ scale: 0.97 }],
	},
	heroBadge: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingHorizontal: 9,
		paddingVertical: 6,
		borderRadius: 999,
	},
	heroBadgeText: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	heroFooter: {
		paddingHorizontal: 14,
		paddingVertical: 12,
		justifyContent: "flex-end",
	},
	heroTitle: {
		fontSize: 24,
		lineHeight: 28,
		fontWeight: "800",
		color: "#F8FAFC",
	},
	quickFactRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	quickFactPill: {
		minHeight: 50,
		borderRadius: 18,
		paddingHorizontal: 10,
		paddingVertical: 8,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		flexGrow: 1,
		minWidth: 102,
	},
	quickFactPillPrimary: {
		backgroundColor: COLORS.brandPrimary,
	},
	quickFactPillPrimaryPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.99 }],
	},
	primaryQuickFactPressable: {
		flexGrow: 1,
		minWidth: 132,
	},
	primaryQuickFactIconWrap: {
		width: 28,
		height: 28,
		borderRadius: 14,
		backgroundColor: "rgba(255,255,255,0.16)",
		alignItems: "center",
		justifyContent: "center",
	},
	quickFactCopy: {
		flex: 1,
		gap: 1,
	},
	primaryQuickFactChevron: {
		marginLeft: 2,
	},
	quickFactLabel: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.3,
	},
	quickFactText: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "800",
	},
	minimalCard: {
		borderRadius: 22,
		paddingHorizontal: 12,
		paddingVertical: 12,
		gap: 10,
		shadowColor: "#0F172A",
		shadowOpacity: 0.05,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
	},
	routePressable: {
		marginTop: -2,
	},
	routeShell: {
		height: 222,
		borderRadius: 26,
		overflow: "hidden",
		backgroundColor: "rgba(255,255,255,0.04)",
	},
	routeShellPressed: {
		opacity: 0.96,
		transform: [{ scale: 0.997 }],
	},
	routeCanvasHeader: {
		position: "absolute",
		top: 12,
		left: 12,
		right: 12,
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 8,
	},
	routeSummaryPill: {
		flex: 1,
		borderRadius: 18,
		paddingHorizontal: 12,
		paddingVertical: 10,
		gap: 2,
	},
	routeSummaryText: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: "800",
		color: "#F8FAFC",
	},
	routeAddressText: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: "500",
		color: "rgba(248,250,252,0.82)",
	},
	routeMapsPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		borderRadius: 999,
		paddingLeft: 6,
		paddingRight: 10,
		paddingVertical: 6,
	},
	routeMapsText: {
		fontSize: 12,
		lineHeight: 14,
		fontWeight: "700",
		color: "#F8FAFC",
	},
	tagRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	tagChip: {
		borderRadius: 999,
		paddingHorizontal: 10,
		paddingVertical: 7,
	},
	tagText: {
		fontSize: 12,
		lineHeight: 15,
		fontWeight: "600",
	},
	roomList: {
		gap: 8,
	},
	roomRow: {
		borderRadius: 16,
		paddingHorizontal: 11,
		paddingVertical: 10,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 8,
	},
	roomCopy: {
		flex: 1,
	},
	roomLabel: {
		fontSize: 13,
		lineHeight: 17,
		fontWeight: "700",
	},
	roomMeta: {
		marginTop: 3,
		fontSize: 11,
		lineHeight: 15,
		fontWeight: "500",
	},
	roomPrice: {
		fontSize: 11,
		lineHeight: 15,
		fontWeight: "700",
	},
	sheetIconShell: {
		width: 28,
		height: 28,
		borderRadius: 14,
		padding: 1,
		shadowColor: "#0F172A",
		shadowOpacity: 0.05,
		shadowRadius: 6,
		shadowOffset: { width: 0, height: 3 },
	},
	sheetIconShellStrong: {
		shadowOpacity: 0.09,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
	},
	sheetIconFill: {
		flex: 1,
		borderRadius: 13,
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
	},
	sheetIconHighlight: {
		position: "absolute",
		left: 1,
		right: 1,
		top: 1,
		height: "44%",
		borderRadius: 12,
		backgroundColor: "rgba(255,255,255,0.22)",
	},
	actionDock: {
		paddingTop: 10,
		paddingHorizontal: 14,
		paddingBottom: 4,
		gap: 8,
	},
	compactActionRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	callActionPressable: {
		width: 56,
	},
	callActionButton: {
		width: 56,
		height: 56,
		borderRadius: 28,
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#0F172A",
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 5 },
	},
	callActionIcon: {
		textShadowColor: "rgba(255,255,255,0.18)",
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 1,
	},
	inlinePrimaryPressable: {
		flex: 1,
	},
	inlinePrimaryAction: {
		minHeight: 56,
		borderRadius: 20,
		paddingHorizontal: 16,
		backgroundColor: COLORS.brandPrimary,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	inlinePrimaryActionPressed: {
		opacity: 0.94,
		transform: [{ scale: 0.99 }],
	},
	inlinePrimaryText: {
		fontSize: 15,
		lineHeight: 19,
		fontWeight: "800",
		color: "#FFFFFF",
	},
});
