export const INSURANCE_SCREEN_COPY = {
  screen: {
    title: "Coverage",
    subtitle: "Insurance",
  },
  center: {
    title: "Coverage on file",
  },
  context: {
    title: "Coverage ready",
    body: "Keep active policies and payment links current.",
    countLabel: "Policies on file",
    defaultLabel: "Default policy",
    lastUpdatedLabel: "Last updated",
    primaryAction: "Add coverage",
  },
  island: {
    title: "Coverage actions",
    linkedPaymentLabel: "Linked payment",
    imageLabel: "Card images",
  },
  editor: {
    createTitle: "Add coverage",
    editTitle: "Update coverage",
    steps: ["Coverage provider", "Policy details", "Card images"],
    next: "Next",
    back: "Back",
    cancel: "Cancel",
    saveCreate: "Add coverage",
    saveEdit: "Save changes",
    providerLabel: "Insurance provider",
    providerPlaceholder: "e.g. Aetna",
    policyLabel: "Policy number",
    policyPlaceholder: "e.g. ABC-123456789",
    groupLabel: "Group number",
    groupPlaceholder: "e.g. GRP-12345",
    holderLabel: "Policy holder",
    holderPlaceholder: "Full name",
    scanTitle: "Scan insurance card",
    scanPending: "Scanning card...",
    scanBody: "Take a photo to fill the policy details faster.",
    imagesBody: "Card images help speed up verification.",
    frontLabel: "Front",
    backLabel: "Back",
  },
  policyCard: {
    hint: "Tap to reveal details.",
    holderLabel: "Policy holder",
    groupLabel: "Group number",
    paymentLinkedLabel: "Linked payment",
    defaultPill: "Default",
    setDefault: "Set default",
    linkPayment: "Link payment",
    updateCard: "Update card",
    edit: "Edit",
    remove: "Remove",
    removeDisabled: "Default policy",
  },
  empty: {
    title: "No coverage on file",
    body: "Add a policy to speed up billing and verification.",
    primaryAction: "Add coverage",
  },
  messages: {
    syncFallback: "Coverage may be showing cached details. Pull to refresh.",
    noDefaultPolicy: "Choose a default policy",
    noLinkedPayment: "No linked payment",
    noCardImages: "Add card images",
    defaultUpdated: "Default coverage updated.",
    saved: "Coverage saved.",
    deleted: "Coverage removed.",
    saveFailed: "Unable to save coverage right now.",
    deleteFailed: "Unable to remove coverage right now.",
    scanSuccess: "Card scanned. Review the details before saving.",
    scanPartial: "Image saved. Add the missing details manually.",
    scanFailed: "Unable to scan the card right now.",
    cameraPermissionTitle: "Camera permission required",
    cameraPermissionBody: "Enable camera access to scan your insurance card.",
    libraryPermissionTitle: "Photo library permission required",
    libraryPermissionBody:
      "Enable photo access to choose images from your library.",
    deleteDefaultBlocked:
      "Set another policy as default before removing this one.",
    deleteTitle: "Remove coverage",
    deleteBody:
      "Are you sure you want to remove this insurance policy? This cannot be undone.",
  },
};
